### ISSUE TITLE
REQ: Provide weapon-cycling functionality with weapon pre-selection

### ISSUE THREAD

**Issue by ellisgl** [ezQuake/ezquake-source#100]
I've tried binding Impulse 10 / 12 to my mouse wheel and to keys, but it doesn't switch weapons.

Using the 2016-06-16-62be229 build.

**Comment by meag** [comment]
Impulses 10 & 12 are currently incompatible with weapon pre-selection, can you confirm that this behaviour exists when cl_weaponpreselect is set to 0?

**Comment by ellisgl** [comment]
Yup /cl_weaponpreselect 0 did the trick.

**Comment by ellisgl** [comment]
Well I did that, now when I fire - it fires the weapons I selected, but when I stop firing, it switches back to shotgun...

**Comment by meag** [comment]
"/cl_weaponhide 0" should disable auto-switching back to shotgun/axe

(please leave open either way - I think the menu selections need tidied up.  getting back to non-competitive quake behaviour is currently quite difficult)

**Comment by ellisgl** [comment]
Yeah found the answer right after posted. Now how would auto switch on pickup (if weapon is better)?

**Comment by meag** [comment]
/w_switch 8

The number is the highest weapon that you would switch to after picking it up, so 8 = LG, 7 = RL, etc.  1 = axe, and so essentially turns the behaviour off.

**Comment by ellisgl** [comment]
Thanks!

**Comment by meag** [comment]
Closing, should be fixed by: https://github.com/ezQuake/ezquake-source/commit/313f64be22f75eda8a6c2294b4fea5158f35a0f7

/weapon 10 & 12 now performs client-side weapon-cycling, menus have been updated to match.
