### ISSUE TITLE
BUG: Console Key in Serverbrowser filters whole serverlistlist away

### ISSUE THREAD

**Issue by onethree7** [ezQuake/ezquake-source#102]
Hi Team Ezquake :dancer: 

well the title basically sais it.
Also i wasnt sure if REQ or BUG 

If i could request something to fix this bug^^, it probably would be:
Could you please disable the Serverbrowser from accepting "console key" in my case "^" as a valid filter option? 

link to thread http://www.quakeworld.nu/forum/topic/6780/server-browser-issue

**Comment by meag** [comment]
On the latest version the search filter shows even when there are no servers matching, so this should be clearer.
