### ISSUE TITLE
ezQuake depends on Growl?

### ISSUE THREAD

**Issue by amatecha** [ezQuake/ezquake-source#103]
Installed nQuake (ezQuake), tried to run it, and it crashes with the following error:

```
Process:               EZQuake-GL [51086]
Path:                  /Users/USER/*/EZQuake-GL.app/Contents/MacOS/EZQuake-GL
Identifier:            net.sf.ezquakegl
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           EZQuake-GL [51086]
User ID:               504

Date/Time:             2016-06-22 21:48:56.573 -0700
OS Version:            Mac OS X 10.10.5 (14F1021)
Report Version:        11
Anonymous UUID:        E77358BA-B254-B53F-E419-BC9920A02B6B

Sleep/Wake UUID:       E973E0B9-6B6A-4BE2-BCEB-69E8A7F0CC69

Time Awake Since Boot: 49000 seconds
Time Since Wake:       1900 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/Growl.framework/Versions/A/Growl
  Referenced from: /Users/USER/*/EZQuake-GL.app/Contents/MacOS/EZQuake-GL
  Reason: image not found
```

If I'm reading this right, it appears to be quitting because it depends on Growl (which isn't installed)?!

**Comment by AAS** [comment]
Same here
```
Process:               EZQuake-GL [37976]
Path:                  /Users/USER/*/EZQuake-GL.app/Contents/MacOS/EZQuake-GL
Identifier:            net.sf.ezquakegl
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           EZQuake-GL [37976]
User ID:               501

Date/Time:             2016-06-23 10:03:18.705 +0500
OS Version:            Mac OS X 10.11.5 (15F34)
Report Version:        11
Anonymous UUID:        E13C0A01-5120-C2E2-4ECE-0F49504745E2

Sleep/Wake UUID:       9061E8F3-98CF-4983-BB36-1D93470B8894

Time Awake Since Boot: 480000 seconds
Time Since Wake:       820 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/Growl.framework/Versions/A/Growl
  Referenced from: /Users/USER/*/EZQuake-GL.app/Contents/MacOS/EZQuake-GL
  Reason: image not found

Binary Images:
0x8fe64000 - 0x8fe98727  dyld (360.22) <F2FF555F-3F89-3F21-8761-25A0E3F8282F> /usr/lib/dyld
0x93a95000 - 0x93ae9ff3  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <5B75F000-34E7-3884-8451-F1BDF216865F> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
0x96088000 - 0x96109ff3  com.apple.framework.IOKit (2.0.2 - 1179.50.2) <64742932-B2AC-3560-9508-C2F7CC08B6A6> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x96b7d000 - 0x96b8bff7  libz.1.dylib (61.20.1) <34A8BA7F-AA56-322E-AC39-ADF8DDE53FF1> /usr/lib/libz.1.dylib
0x97060000 - 0x97060fff  com.apple.Cocoa (6.11 - 22) <5DE99658-0C2F-3DB0-8741-B9D36FCF04D8> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
0x97bdb000 - 0x97bdbfff  com.apple.ApplicationServices (48 - 48) <254BB3C1-738A-3A40-92E4-F595ED0EC7EC> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
0x9b16a000 - 0x9b178ff3  com.apple.opengl (12.1.0 - 12.1.0) <47893C04-DCA1-3512-BA5A-2AE812E2E6DE> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
0x9c3e6000 - 0x9c664fef  com.apple.QuickTime (7.7.3 - 2943.10) <72F3E946-0ABF-3A83-B1AA-FF79C80252F5> /System/Library/Frameworks/QuickTime.framework/Versions/A/QuickTime
```

**Comment by meag** [comment]
Can you confirm if this happens on v3.0?  You can download from the [releases](https://github.com/ezQuake/ezquake-source/releases) page.

**Comment by amatecha** [comment]
It's worth noting I used the nQuake installer.  I don't have access to the same machine I tried with earlier, but running ezQuake 3.0 on my main MacBook Pro gives a different error (probably lacking SDL or something?) -- this machine also doesn't have Growl, so maybe you will know offhand if this error would come before or after the Growl error.  Sorry, I'll see if I can get on that other machine again... >_>

```
Process:         ezquake-darwin-x86_64 [33785]
Path:            /Users/USER/Downloads/ezQuake.app/Contents/MacOS/ezquake-darwin-x86_64
Identifier:      net.sf.ezquake
Version:         3.0.0
Code Type:       X86-64 (Native)
Parent Process:  launchd [279]
Responsible:     ezquake-darwin-x86_64 [33785]
User ID:         501

Date/Time:       2016-06-22 23:40:24.716 -0700
OS Version:      Mac OS X 10.9.5 (13F1096)
Report Version:  11
Anonymous UUID:  45C64172-6555-70AA-793D-D8DEE583C520

Sleep/Wake UUID: C428B3BF-8C1B-4F21-B14F-9D7824C4CBFD

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Dyld Error Message:
  Symbol not found: _AudioUnitSetProperty
  Referenced from: /Users/USER/Downloads/ezQuake.app/Contents/MacOS/../Frameworks/libSDL2-2.0.0.dylib
  Expected in: /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox

```

**Comment by fzwoch** [comment]
ezQuake 2.x on mac is horrific broken in that regard - and probably in any other aspect as well. It cannot even be correctly build with the latest Xcode version. No way I will even try to look at it on how to fix it. ezQuake 3.x is the way to go on macOS. If that one fails you as well I may take care of your issues..

That nQuake currently does not ship with ezQuake 3.x is unfortunate - but this is a another project altogether.

**Comment by meag** [comment]
We think this might be down to a newer version of xcode being used to compile the binary.

I have recompiled the osx version on xcode 6.2 (10.9) and uploaded [here](https://github.com/ezQuake/ezquake-source/releases/download/v3.0/ezquake3.0-osx-update-xcode62.zip), can you try that version and see how you get on?

**Comment by amatecha** [comment]
Yup, I can give that a try tonight, thanks

**Comment by meag** [comment]
Did you get a chance to try the new binary?  Any luck?

**Comment by amatecha** [comment]
Sorry, been a really busy week!  I just tested it and it runs just fine!  Interesting...  I assume that compiling it with that version of XCode means it'll run in 10.9 *and newer* , right?  :)

**Comment by fzwoch** [comment]
Of course :-)

And indeed it does work for me too. ezQuake itself is compiled with 10.8 support btw. The problem is that its dependencies (in this case SDL2) was compiled with 10.11 previously. Now at least with 10.9. Thanks for reporting and testing.

**Comment by amatecha** [comment]
Aahhh I see, makes sense.  Glad to help!

**Comment by amatecha** [comment]
But this bug was about Growl being a dependency -- is that fixed?

**Comment by fzwoch** [comment]
The original bug refers to ezQuake 2.x. This is not fixed and will never be. ezQuake 3 is not affected by this bug as it does not depend on the Growl framework.

**Comment by fzwoch** [comment]
On another note, the 2.1 version downloaded form sf.net does still work. It behaves clunky but it also does bundle a version of the Growl framework. So it may be an issue to nQuake specifically.

**Comment by amatecha** [comment]
Ah, okay, good to know.  Too bad - PC Gamer had an article about Quake's 20-year anniv and linked to nQuake and mentioned their server IPs for everyone to play on.  Ah wellz, I'm glad to see ezQuake is still nicely-maintained!  :)

Looks like someone has filed a bug on nQuake @ sf.net regarding the Growl issue.  https://sourceforge.net/p/nquake/bugs/10/  Seems like it's pretty ill-maintaned tho, last update in March 2014...   /shrug
