### ISSUE TITLE
REQ: Option to disable dynamic lightning on powerup items

### ISSUE THREAD

**Issue by daffymahman** [ezQuake/ezquake-source#105]
In vanilla Quake the powerup (Quad, Pent) items have no dynamic lightning, it is only when they are picked up that the player itself is surrounded by it.

Please add an option to disable dynamic lightning on the items themselves.

**Comment by meag** [comment]
Hi there

I've had a look at this, it seems to be the game mod that decides which items have the lighting effect.  For example in single player mode ezquake won't show the quad glowing, but in KTX the effect is always on.  Maybe log this as a KTX request?

I'll close for now, feel free to re-open if I've misunderstood.

Thanks
