### ISSUE TITLE
BUG: Does not compile on Linux (libpng12 not found)

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#106]
Dev version of ezquake does not compile on Debian  testing.
Debian switched to libpng16 and png.h is now in /usr/include/libpng16/png.h
but I get this in console:

make: **\* No rule to make target '/usr/include/libpng12/png.h', needed by '.ezquake/cl_main.o'.  Stop.

**Comment by SH0xas** [comment]
I can confirm that debian 9 uses libpng16 and ezquake requires libpng12, so installation can not be completed.

**Comment by meag** [comment]
Believe this is no longer the case, please re-open if still an issue
