### ISSUE TITLE
BUG: Thread handles not closed on Windows

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#112]
Bogo fixed this for posix: https://github.com/ezQuake/ezquake-source/commit/69260467df6191a79a5ad01bcb89b223f57d5068

Windows still has this problem.  Currently only used for server browser & match tools, both of which are being reviewed soon anyway.

**Comment by jite** [comment]
Solved by 16d568b328aa4880389c8eb553feeec97d56641d ?
