### ISSUE TITLE
BUG: Numpad isnt workning

### ISSUE THREAD

**Issue by ok98** [ezQuake/ezquake-source#113]
Numpad isnt workning in last build.
If i change to in_builtinkeymap to 0 i can write witn the numpad in console, but still cant use it as teamsays.

**Comment by meag** [comment]
Gave this a quick test and can't replicate here, can you confirm:

Your operating system keyboard layout (swedish?)
The bind command you're using?  (bind kp_8 "say_team testing @ %l")

Do you know what build you last had this working?

**Comment by meag** [comment]
Hi there - would like to get this fixed for 3.0.1 release, if it's still a problem?

**Comment by ok98** [comment]
Hello,
I used 2.2 stable when i worked. Tested it again, and it still works in 2.2.
I use swedish keyboard layout.
bind  *             ".droppedpack"
bind  -             ".attack"
bind  +             "tracklist"
alias .attack                        "say_team {&cf00$\$nick2 attack&cfff} {&cf00[&cfff}{%d}{&cf00]&cfff} {%E}"
alias .droppedpack                   "say_team $\$nick {&cf0fborepack&cfff} $[{%d}$] e:{%E}"

noone of these works.

Even Enter doesent work.
Enter dont even work with in_builtinkeymap 0, but then i can type - + and numbers in the console.

**Comment by meag** [comment]
Okay, it looks like cl_keypad was removed, this converted keypad buttons to standard buttons.  Can you try instead:

bind kp_star ".droppedpack"
bind kp_minus ".attack"
bind kp_plus "tracklist"

Also: kp_enter, kp_3, kp_4, etc.

**Comment by meag** [comment]
Okay, I've added cl_keypad support back in, so your old config should work if you set cl_keypad 0 (it was probably set this way in 2.2).  Hopefully stops one more 2.2 -> 3.0 upgrade issue :)

Thanks for reporting.
