### ISSUE TITLE
BUG: s_show 2 only available in DEBUG builds (doesn't match documentation)

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#119]
I set  "s_show 2", but it only prints the number of files playing, and not the names and left/right speaker info as the doc says.

OS: Linux. Both latest git build and 3.0 are affected.

**Comment by jite** [comment]
Thanks for reporting but please read the wiki about prefixing your issues, the other issues might give a hint ;)

**Comment by meag** [comment]
Can confirm that `s_show 2` currently only works in debug builds, as per https://github.com/ezQuake/ezquake-source/commit/5e21df9ea15834274e8f1cad89f42d252da68dbc

Is there any advantage to be gained from having it enabled during a game?  It would make very quiet noises easier to identify, or give away position based on left/right volume?  The player would need to have quicker reflexes than me to pick up on it.

**Comment by mmavova** [comment]
I found this cause I was trying to understand why suddenly sounds became a
bit distorted
after a resent "apt-get update", and I was just trying all possible sound
variables.

By the way, does QW have a weird sound subsystem? It is the only game
that I know of that constantly has sound distortion issues.

**Comment by meag** [comment]
Have you tried increasing s_desiredsamples to 1024/2048/4096?
There are some things to try listed at https://github.com/ezQuake/ezquake-source/wiki/Common-Issues

**Comment by mmavova** [comment]
Yep, I tried everything, s_desiredsamples, s_khz, etc.
Nothing helps.

I will see which packages got updated in the last several days,
and try to downgrade.


On 07/14/2016 02:32 PM, meag wrote:
> Have you tried increasing s_desiredsamples to
> 1024/2048/4096? There are some things to try listed at
> https://github.com/ezQuake/ezquake-source/wiki/Common-Issues
>
>  — You are receiving this because you authored the
> thread. Reply to this email directly, view it on GitHub
> <https://github.com/ezQuake/ezquake-source/issues/119#issuecomment-232752472>,
>
>
or mute the thread
> <https://github.com/notifications/unsubscribe/ATaoEIrCMLiGpbnricsyLDHjcAEaz2lUks5qVoDZgaJpZM4JMb0T>.
>

**Comment by mmavova** [comment]
I downgraded from 9.0 to 8.0 the following packages:

pulseaudio-esound-compat
pulseaudio-module-x11
libpulse0_8.0-2
libpulse-dev
libpulsedsp
libpulse-mainloop-glib
pulseaudio
pulseaudio-utils

QW sound went back to normal. No idea what to do now.

On 07/14/2016 02:32 PM, meag wrote:
> Have you tried increasing s_desiredsamples to
> 1024/2048/4096? There are some things to try listed at
> https://github.com/ezQuake/ezquake-source/wiki/Common-Issues
>
>  — You are receiving this because you authored the
> thread. Reply to this email directly, view it on GitHub
> <https://github.com/ezQuake/ezquake-source/issues/119#issuecomment-232752472>,
>
>
or mute the thread
> <https://github.com/notifications/unsubscribe/ATaoEIrCMLiGpbnricsyLDHjcAEaz2lUks5qVoDZgaJpZM4JMb0T>.
>

**Comment by meag** [comment]
Can you try `/s_listdrivers` in the console and see what options it gives you?
It should be possible to set SDL_AUDIODRIVER to the desired audio driver before launching, that might let you experiment with different drivers?  A list of options is available [here](https://wiki.libsdl.org/FAQUsingSDL)

**Comment by mmavova** [comment]
It gives me

pulseaudio
alsa
sndio
dsp
disk
dummy

dsp and sndio result in no sound, alsa and pulseaudio result 
in some sounds being distorted. Did not try disk and dummy.

Anyway, I just downgrade to pulseaudio 8.0 for now.



On 07/16/2016 03:03 AM, meag wrote:
> Can you try |/s_listdrivers| in the console and see what
> options it gives you? It should be possible to set
> SDL_AUDIODRIVER to the desired audio driver before
> launching, that might let you experiment with different
> drivers? A list of options is available here
> <https://wiki.libsdl.org/FAQUsingSDL>
>
> — You are receiving this because you authored the
> thread. Reply to this email directly, view it on GitHub
> <https://github.com/ezQuake/ezquake-source/issues/119#issuecomment-233115515>,
>
>
or mute the thread
