### ISSUE TITLE
BUG: shows your cameraview twice if you are the only player

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#126]
Watch an  mvd demo (say, a trick one), where there is only one player.
If you have multiview turned on, then the second camera window shows you again.

If there is only one player, the second window should not appear.
See the screenshot attached.

![ezquake008](https://cloud.githubusercontent.com/assets/20359184/17104935/0d6a9f38-5253-11e6-86f5-774beac2fd28.png)

**Comment by meag** [comment]
Looked into this a while back, and found code to do with powerup cams - but then I remember Ake asking about them before and not being able to get them to work then either.... when fixing this will need to make it an option as then the inset view could be a fixed perspective (not tracking a player)
