### ISSUE TITLE
BUG: when pausing multiview is broken, it shows player 1 in both cams

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#130]
Play an mvd demo with multiview. I was using 2 cams on a duel mvd in this case.
It works fine.

But when you press pause the smaller cam switches to player 1 for the duration of the pause.
See the attached screenshot.

![ezquake010](https://cloud.githubusercontent.com/assets/20359184/17199250/7b844896-5449-11e6-95eb-2abbc09433c8.png)

**Comment by mmavova** [comment]
By the way, when you switch to player 2 in replay, console messages are still printed from the first player's point of view. Should I open another bug for this as well?

**Comment by meag** [comment]
Hi there

Yes, please open another bug for the console messages, we can discuss there.

For this one, can you also supply the console variables you set to get the configuration shown in the screenshot?  Just to make it easier to give us a simple test case so we can replicate here.

Thanks for reporting!

**Comment by liback** [comment]
To get the multiview setup as in the screenshot:
cl_multiview 2
cl_mvinset 1

**Comment by mmavova** [comment]
The bug is reproducible even with cl_mvinset 0.

My config.cfg is attached. (had to rename it to .txt b/c github interface does not allow .cfg file names)

[config.txt](https://github.com/ezQuake/ezquake-source/files/390661/config.txt)
