### ISSUE TITLE
BUG: Tracker can cause local lag as images are loaded

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#132]
Seems to load images as required, rather than as fragfile.dat is loaded.  This causes very slight delays when loading images from hard drive (in case seen last night, after playing for so long the hard drive spun down, then the nailgun/slime icon being required).

**Comment by jite** [comment]
Just want to add a note that this is true for many other things too. Menu, demo controls, rankings (scoreboard), hud groups (until hud_groupX_show is set to 1). Some things could definitly be loaded at startup and kept in memory.

**Comment by meag** [comment]
Closing: this has been fixed in 3.5
