### ISSUE TITLE
BUG: messages from a different pov in multiview

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#133]
Let's say you are watching a replay Griffin-Reppie, for example, from reppie's point of view.
Sometimes when reppie is killed (not every time though, I dunno why)
I see messages like "You killed reppie". And there are no messages at all from Griffin's point of view.
I think to reproduce this you need to switch pov once to the second player.

See the screenshot attached.
![ezquake012](https://cloud.githubusercontent.com/assets/20359184/17296538/c2c94056-57cf-11e6-97f6-d44bdb897dcc.png)

**Comment by meag** [comment]
Should be fixed with https://github.com/meag/ezquake-source/commit/41dff6a37cd2f9a0eb7f30892d79dd09dc040107
