### ISSUE TITLE
BUG: Numerous multiview issues

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#136]
I was watching this replay.
I have headbars (nick and health to be shown above the head) turned on,
but they are not shown for your teammate.
See the screenshots attached.

Rikoll has it, where as "my" teammate Locktar does not.

![ezquake013](https://cloud.githubusercontent.com/assets/20359184/17463117/79739100-5c8d-11e6-919a-60101c5c4353.png)
![ezquake014](https://cloud.githubusercontent.com/assets/20359184/17463118/7975b44e-5c8d-11e6-9aa6-ea34bffc064f.png)

[2on2_rune_vs_raga[dm2]160805-1601.mvd.gz](https://github.com/ezQuake/ezquake-source/files/405551/2on2_rune_vs_raga.dm2.160805-1601.mvd.gz)

I mention some additional bugs in the comments

**Comment by mmavova** [comment]
Additional bugs:
1. Probably should not draw headbars for your own player (the POV you are on). Sometimes when the player looks straight up/down they are visible.

2. For some reason teamskin/enemyskin does not work anymore: when I switch povs skins also switch. For example, when I view the attached replay team Rune is always green, and team Ragnarok is always white, regardless of the POV I am watching. 

3. Press and hold TAB. For some replays there is an indicator in the scoretable that shows which POV I am on, and for some replays (like this one!) there is not. This is another bug. 

By the way, is there a quick way to figure out who I am watching?


[config.txt](https://github.com/ezQuake/ezquake-source/files/405560/config.txt)

**Comment by meag** [comment]
After quick test, it seems these are all multiview-related bugs.  The skin changing one is interesting, for example:

> Turn autotrack off
> Play demo, `/cl_demospeed 0`, then `/track carapace`
> `/demo_jump 126` (cara can see locktar, locktar & milton can see each other, inset view is locktar)

locktar is green (teammate), milton is in locktar's view as white (enemy).  Cycle through slowly and the skins will break, you'll end up with carapace looking at a white/enemy locktar and milton being in green.

I'll try and get through all the mvd bugs this week.

**Comment by mmavova** [comment]
Thank you, meag.
Many things in demo replay are borked. :(

**Comment by mmavova** [comment]
Another thing I just noticed: the kill messages you see on the screen are coloured.
But the colour is random. Sometimes it colours you as red, and the opponent as green, and at other times the colours are reversed. This even happens if it is always one person killing the other.

I expected my name / my team to be always green, and the opponent always red.

**Comment by mmavova** [comment]
I am not sure if it is the same bug as meag mentioned earlier, but if I change enemyskin several times, it stops changing after I do it several times.

**Comment by meag** [comment]
Again, they should always be consistent as long as you don't have multiview on - maybe then they depend on the order they're stored in the .mvd file?  I'll add it to the list...
