### ISSUE TITLE
BUG: max path is too short

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#141]
I cannot replay many demos, I get roughly the following error message:
path (length 135) is too long (max path length 124)

Why do we limit path to 64/128?
# define MAX_QPATH                       64              // max length of a quake game pathname
# define MAX_OSPATH                      128             // max length of a filesystem pathname

How about increasing it to 1024?

**Comment by mmavova** [comment]
I naively tried to increase the length only and recompile, now I get this crash:
./latest_dev_ezq.bin +set cl_independentPhysics 1 +exec s.cfg  -ruleset smackdown -mem 128
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Error: Hunk_AllocName: Not enough RAM allocated.  Try using "-mem 128" on the ezQuake command line.

**Comment by mmavova** [comment]
Ok, 1024 was too big, but changing MAX_OSPATH to 160 does not cause a crash 
and allows me to replay duelmania demos.

**Comment by meag** [comment]
I didn't understand why it was 128, I thought maybe it was for some historical reason or maybe to do with .pak handling etc.

On Windows, I believe the maximum path length allowed is 260, unless we switch over to using unicode API functions instead of fopen() etc.

**Comment by mmavova** [comment]
I use this now:

#define	MAX_QPATH			64		// max length of a quake game pathname
#define	MAX_OSPATH			512		// max length of a filesystem pathname


if I set MAX_QPATH 256
then it crashes.

**Comment by jite** [comment]
MAX_OSPATH 512 is not OK for Windows, it's as meag said: 260 for Windows.
