### ISSUE TITLE
BUG: alt-tab is broken in the latest dev build

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#142]
In the recent builds (happened before 3.0.1) alt-tab on Linux was broken.

Dev build that reports f_version  as R4799~2096700 works fine

Dev build that reports f_version as R4866~2556BB7 has alt-tab broken.

**Comment by mmavova** [comment]
I hope somebody can commit a fix soon, cause this one is annoying.

**Comment by jite** [comment]
There was a change to grab the keyboard that causes this. It solves the issue that some ppl can't use the win-key if keyboard isn't grabbed.

I'm thinking of two solutions:
1) Disable keyboard grabbing by default and add a cvar to enable it
2) Make alt-tab call SDL_MinimizeWindow (however this will most likely require a release + repress of alt-tab to continue tabbing...) Allowing keyboard to be grabbed.

Not sure which solution would be best...

**Comment by mmavova** [comment]
Oh, by the way, I do not even use Alt-Tab. In my window manager my bind is Win-Tab to switch windows. 
I

**Comment by meag** [comment]
Believe I broke this with commit https://github.com/ezQuake/ezquake-source/commit/e67c62fe8509f0e7802baf2cd5a10b8c2a877860

**Comment by mmavova** [comment]
Yes, commenting out line
SDL_SetHint(SDL_HINT_GRAB_KEYBOARD, "1");

fixes the issue for me.

**Comment by jite** [comment]
vid_grabkeyboard 0/1

0: Don't grab, let's alt-tab work but window manager binds may override ezquake binds
1: Grab keyboard, ezquake overrides window manager binds but that may include alt-tab.

See: 10a07c955c5e3cdf5d9adeac21c723b5c90e8640
