### ISSUE TITLE
BUG: ColorCorrection - Small issue with redshift

### ISSUE THREAD

**Issue by joemaro** [ezQuake/ezquake-source#143]
# hey beloved devs!

very minor (linux) issue here:
i'm using redshift, a tool which decreases the color temperature when the sun goes down. i think it makes it's change via x.org, but spare me the details :P so when playing ezQuake in the evenings there's this weird behaviour:
when dying, the color-temperature changes back to "cold" (blue-ish) and then after 2 seconds or so, it's back to the "warm" (red-ish) colors (that redshift applies). 
It's as if in the background red-shift and ezquake would be 'fighting' for color correction, but only in the moment of spawning :)

manjaro linux (arch based) / latest ezquake / xorg version 1.17.4-3.1 / redshift 1.11

cheers <3

**Comment by joemaro** [comment]
adding: same thing happens not only after respawning but also after coming out of the water and going in, and when grabbing quad.

**Comment by meag** [comment]
Hi there

Can you confirm your values of /gl_polyblend & /gl_hwblend please?

Thanks,

**Comment by jite** [comment]
@joemaro I think disabling what @meag suggests will fix the issue.
Yes they are sort of fighting over hwgamma :)

**Comment by meag** [comment]
Merging with #178 (request for shader gamma)
