### ISSUE TITLE
BUG: ezquake is still reading mouse movements after I alt-tab out of it

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#144]
sit on a server, 
point at something, 
alt-tab to any other window. 
move the mouse
alt-tab back in
you are now pointing in some other direction

**Comment by mmavova** [comment]
OK, to clarify, to reproduce this:

1) do not alt-tab. Switch to a different desktop when ezq window is active. 
2) Move the mouse
3) switch back to desktop with ezq.

**Comment by fzwoch** [comment]
I wonder if this macOS? I could image this is related to `in_raw 1` where input is still read because it is not handled by SDL2?

**Comment by meag** [comment]
Cannot replicate this in Ubuntu 20 (switching to another desktop, or another workspace) - sounds like a bug related to your window manager, rather than ezquake?
Please re-open with exact steps to reproduce, which window manager etc
