### ISSUE TITLE
BUG: alt-tab works incorrectly on Linux

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#145]
Instead of switching focus to another window, it also minimizes QW window,
so on a dual monitor setup, I can never have QW visible, and work in another window at the same time :(

Again, this is on Linux, I dunno what happens in Windows/MacOS.

**Comment by joemaro** [comment]
i can't ever switch out of ezquake (manjaro=arch based, using intel gfx via mesa-drivers)
doesnt matter which windowmanager i'm using, it doesnt let any keys pass to the windowmanager.
Don't know if thats a bug though or desired behaviour.

**Comment by Calinou** [comment]
Alt-Tab works only when the console is opened, for some reason, in windowed mode. I'd like it to work regardless, just like in Xonotic.

Also, on Linux, fullscreen should probably just use a borderless window, it's way less troublesome this way (it's the way most SDL 2 games use).

**Comment by jite** [comment]
I got fixes for both alt-tab not working and that losing focus meant window minimized.

Both are togglable, there are two problems regarding alt-tab, or rather you can have one of:
1) Alt-tab working but it also means that other window manager binds will result in whatever they are bound to (say you bound windows key to something, then the window manager bind will take precedance).

2) Have ezQuake grab keyboard meaning that ezQuake is in control of all keys pressed. This is good for some ppl using window manager binds that conflict with their ingame binds. Now we could map alt-tab to like minimize window, but not really simulate a real alt-tab...

So I've made two cvars:
vid_minimize_on_focus_loss 0/1
vid_grab_keyboard 0/1 (use 0 to have alt-tab working, use 1 if using "conflicting" keys)

Will push to master in the near future.

**Comment by jite** [comment]
It's pushed: 10a07c955c5e3cdf5d9adeac21c723b5c90e8640
