### ISSUE TITLE
BUG: garbage in QW console when switching desktops on Linux 

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#146]
When I switch desktops on Linux (Win-N, for example Win-2 for the second desktop),
and then switch back to QW on the first desktop by pressing Win-1, 
then I get "11" added to console, if I am in console at the time. To reproduce:
1. Have QW on the first desktop, open console.
2. Switch away to desktop 2, for example, via Win-2 shortcut.
3. Now switch back to the first desktop via Win-1.
4. "11" gets appended to the string in QW console.

This is annoying when trying to type a server ip that you can only see in a browser on a different desktop :)

This bug was introduced some time this year.

**Comment by mmavova** [comment]
I could not make copy-paste work either. Another ticket? :(

**Comment by VVD** [comment]
Try to use Alt+Enter.

**Comment by mmavova** [comment]
Thank you, Alt-Enter works is a  workaround.

**Comment by mmavova** [comment]
To achieve what? Even if QW is not full-screen, "11" is still printed in QW console.

**Comment by mmavova** [comment]
This is not really fixed. It is just instead of two "11" I get "1" in the console.

**Comment by ciscon** [comment]
give in_ignore_unfocused_keyb 1 a shot

**Comment by mmavova** [comment]
> give in_ignore_unfocused_keyb 1 a shot

That works, thanks.
