### ISSUE TITLE
BUG: ezquake does not compile with -O0

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#150]
Replace -O2 with -O0 in the Makefile. recompile. I get

.ezquake/common.o: In function COM_GetUniqueTempFilename':
...QW/other_stuff/dimman_workspace/ezquake-source/common.c:372: warning: the use oftempnam' is dangerous, better use mkstemp'
.ezquake/ez_slider.o: In functionEZ_slider_OnMaxValueChanged':
...QW/other_stuff/dimman_workspace/ezquake-source/ez_slider.c:275: undefined reference to EZ_slider_CalculateGapSize'
.ezquake/ez_slider.o: In functionEZ_slider_OnMinValueChanged':
...QW/other_stuff/dimman_workspace/ezquake-source/ez_slider.c:293: undefined reference to EZ_slider_CalculateGapSize'
.ezquake/ez_slider.o: In functionEZ_slider_OnSliderPositionChanged':
....QW/other_stuff/dimman_workspace/ezquake-source/ez_slider.c:308: undefined reference to EZ_slider_CalculateRealSliderPos'
.ezquake/ez_slider.o: In functionEZ_slider_OnResize':
...QW/other_stuff/dimman_workspace/ezquake-source/ez_slider.c:428: undefined reference to EZ_slider_CalculateGapSize'
...QW/other_stuff/dimman_workspace/ezquake-source/ez_slider.c:429: undefined reference toEZ_slider_CalculateRealSliderPos'
collect2: error: ld returned 1 exit status
Makefile:423: recipe for target 'ezquake-linux-x86_64' failed
make: *** [ezquake-linux-x86_64] Error 1

Need to remove __inline?

**Comment by jite** [comment]
Fixed by 17e9a268053b326e54fc04bc76e7093eed5a8a34

Thanks
