### ISSUE TITLE
BUG: score_difference is borked in multiview and sometimes while speccing too

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#158]
There is a hud element called score_difference. It is supposed to show "you team score - enemy team score". 

I have noticed that often in demos it is borked, as it shows the negative of what it is supposed to show.

Same happens while  speccing live games, but much harder to reproduce, obviously. 

I am attaching a replay that reproduces the issue and some screenshots.
Use demo_jump 7:50.

![ezquake022](https://cloud.githubusercontent.com/assets/20359184/18007238/2d2ffa20-6b71-11e6-9f2c-cee7b72fb5fd.png)
![ezquake023](https://cloud.githubusercontent.com/assets/20359184/18007244/34eef69e-6b71-11e6-85cb-1291c7a6bdcd.png)
![ezquake023](https://cloud.githubusercontent.com/assets/20359184/18007285/67fae5c0-6b71-11e6-9b56-99b9ee673253.png)
[duel_doctor_vs_bulat[dm4]160801-1238.mvd.gz](https://github.com/ezQuake/ezquake-source/files/439397/duel_doctor_vs_bulat.dm4.160801-1238.mvd.gz)

**Comment by meag** [comment]
Hopefully fixed with https://github.com/ezQuake/ezquake-source/commit/b74c575169538b5bc53afd0af02146c5b68d8f8b

**Comment by mmavova** [comment]
I can confirm that it is fixed both in watching demos and while watching qtv (qtv was broken).
