### ISSUE TITLE
BUG: multiview shows the same player at the start of a demo 

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#160]
This bug is a big hard to reproduce, cause it does not happen every time for me:
Steps to reproduce:
1. Start playing a demo in multiview. See if the players are the same or not in both windows
2. If they are not, pick a different demo and go to step 1. :)

If the bug is triggered, the second window does not even draw HUD, see the screenshots attached.
![ezquake025](https://cloud.githubusercontent.com/assets/20359184/18035126/f07d69f2-6d1c-11e6-9bec-4df779396970.png)
![ezquake024](https://cloud.githubusercontent.com/assets/20359184/18035128/fcc33598-6d1c-11e6-83d1-c33958551be6.png)

**Comment by meag** [comment]
Multiview has been vastly changed since this bug reported (all views in one frame).  Am now personally using this feature regularly and haven't seen it, closing for now.
