### ISSUE TITLE
BUG: we should delete temp files, gentlemen

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#161]
I see a bunch of temp files left from ezquake under /tmp:
tmp/ezqAKot7v.mvd  /tmp/ezqaV5RAp.mvd  /tmp/ezqBeCdyS.mvd  /tmp/ezqNE9FKQ.mvd  /tmp/ezqQVSBJF.mvd  /tmp/ezqsE0ToR.mvd   /tmp/ezqwquh5l.mvd

/tmp/ezq0ddOso/THRESH0.DEM
/tmp/ezq1Y8zoT/kc_smack.dem
/tmp/ezq20u2IO/kc_smack.dem
/tmp/ezqBuojio/kc_smack.dem
/tmp/ezqcCI61T/kc_smack.dem
/tmp/ezqejl7sg/kc_smack.dem
/tmp/ezqn0mpb5/kc_smack.dem
/tmp/ezqqclFMC/kc_smack.dem
/tmp/ezqqqfA3H/kc_smack.dem
/tmp/ezqsg84sT/kc_smack.dem
/tmp/ezqvRvDXC/kc_smack.dem

Also, here is a comment from fs.c:
/*
[19:23:40] <@disconnect|bla> Cokeman: how do you delete temporary files on windows? =:-)
[19:23:51] @Cokeman I don't :D
[19:23:52] Cokeman hides
[19:23:55] <@disconnect|bla> zomfg :E
[19:24:04] <@disconnect|bla> OK. Linux have same behavior now.
*/

**Comment by meag** [comment]
Should be fixed by https://github.com/ezQuake/ezquake-source/commit/d02add0d31e49e713f758305ca0559856c9186e2
