### ISSUE TITLE
REQ: make r_powerupglow work even with r_dynamic 0

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#165]
powerup glow is an important gameplay feature,
but r_dynamic adds some useless lights that at least I turn off.

**Comment by mmavova** [comment]
Hm, I found out that 
cl_muzzleflash 0
r_explosionLight 0
r_rocketLight 0
r_dynamic 1

works for me.

**Comment by jite** [comment]
I think what you want otherwise is gl_flashblend 1 or 2. In these cases please ask for help first and then file a bug report if it turns out there's no option available.
