### ISSUE TITLE
BUG: cl_gibfilter 1 draws head sometimes

### ISSUE THREAD

**Issue by Matrix-QW** [ezQuake/ezquake-source#167]
I notice this during games. Doesn't happen in all frags that involve gibs.

**Comment by mmavova** [comment]
You are right. 
Proofs:
![ezquake029](https://cloud.githubusercontent.com/assets/20359184/18231541/f131a97c-7289-11e6-867e-6803293f26d4.png)
![ezquake030](https://cloud.githubusercontent.com/assets/20359184/18231542/f132520a-7289-11e6-8f6e-29c59e66e345.png)
![ezquake031](https://cloud.githubusercontent.com/assets/20359184/18231543/f132f232-7289-11e6-9342-dda13471aae7.png)

**Comment by meag** [comment]
Text on commit referenced incorrect bug.
Should be fixed by https://github.com/ezQuake/ezquake-source/commit/c65b115a2dc788da6f2afc170ccd0159bf6b9f69
