### ISSUE TITLE
BUG: game closes with an error on treerace.bsp

### ISSUE THREAD

**Issue by mmavova** [ezQuake/ezquake-source#171]
1. Connect to a server.
2. Type "treerace" to change map. This map is from here:
   https://github.com/mattbailey/quake-slide/tree/master/maps
3. Ezquake closes with an error message:
   Error: AllocBlock: full

Both 3.0 and dev branch.

**Comment by mradrian001** [comment]
I was able to reproduce this issue. 

The map "treerace" has 160 lightmaps however MAX_LIGHTMAPS is set to 128. Setting MAX_LIGHTMAPS to a value greater than 160 solves this problem.

The question is, what value should we set for MAX_LIGHTMAPS? (256?)

**Comment by mmavova** [comment]
I changed MAX_LIGHTMAPS to 256, but I do not think the map renders correctly. If you walk past the first room, it looks wrong still.

**Comment by meag** [comment]
I've upped it to 192 lightmaps in https://github.com/ezQuake/ezquake-source/commit/c113a05c365d15dbeebb65958dc3fd7fa5dede1e - I believe there are other plans to get rid of the limitation altogether.
The map rendering incorrectly - it looks like that weird sky room is deliberate.
