### ISSUE TITLE
REQ: msg/msg_filter option to filter out weapon messages

### ISSUE THREAD

**Issue by ciscon** [ezQuake/ezquake-source#183]
It appears that the only way to avoid seeing messages like "no weapon" is to also filter out frags which means that you can no longer parse them for display in the tracker.  It would be nice if the tracker were to parse the frag messages before filtering and then have a filtering option that only left chat messages and/or higher level messages to be displayed.

**Comment by meag** [comment]
I think you mean the `msg` option - that filters server-side, so if it's set too high then we don't get death messages.  KTX uses PRINT_HIGH for "no weapon" messages, but also for all other mod messages that aren't to do with chat or deaths (map voting etc) ...

Do you want to filter out those messages too?  Or do you mean you want to say "no weapon" should be considered low priority and filtered out server-side?
