### ISSUE TITLE
BUG: "hud_score_bar_fixed_order" - sometimes "leading player/team" aren't %t

### ISSUE THREAD

**Issue by ViantriZ** [ezQuake/ezquake-source#184]
No idea about how to reproduce that (read title again).
Doesn't matter when - watching demos, observing~

ezQuake 3.1-dev r4932~ad6618c
![ezquake 2016-12-05 00-13-27-265](https://cloud.githubusercontent.com/assets/19425141/20868609/336d8aa4-ba92-11e6-8340-09572aeae450.jpg)
![ezquake 2016-12-05 01-14-21-334](https://cloud.githubusercontent.com/assets/19425141/20868610/3372b934-ba92-11e6-9e5b-d4b586c93b1d.jpg)
![ezquake 2016-12-05 00-54-20-406](https://cloud.githubusercontent.com/assets/19425141/20868611/38710878-ba92-11e6-81c9-116076966af1.jpg)

UPD1 December 5, 15:41 (GMT+6)
Oops... it seems like this "bug" report is due to misleading string in "/describe hud_score_bar_fixed_width":
> 1 - When spectating, leading player is always %t

**Comment by meag** [comment]
%t should be the current point of view, not the leading team - is this not happening?

This is how I use it:
```
hud_score_bar_fixed_order             "1"
hud_score_bar_format_reversed_small   "&c0f0%T&r %t |[%e]&cf00%E&r"
hud_score_bar_format_small            "&c0f0%T&r[%t]| %e &cf00%E&r"
hud_score_bar_frag_length             "2"
```

This keeps the names in the same order regardless of POV, but highlights the fragcount of the person/team being tracked.

Thanks,
meag
