### ISSUE TITLE
BUG: impossible to make pixel to pixel any crosshair

### ISSUE THREAD

**Issue by petska** [ezQuake/ezquake-source#189]
impossible to make pixel to pixel any crosshair. I've tried different gl_texturemode2d values.
Here's example with gl_texturemode2d gl_nearest & crosshairsize 1.
croz.tga - custom crosshair can be downloaded with goo [dot] gl [slash] couxeO
png screenshot by ezquake. If it looks ok to you then crop 32x32 and look again on red parts length.
![ezquake003](https://cloud.githubusercontent.com/assets/5527771/21746938/f7dcfad4-d566-11e6-8256-530362bbd94f.png)
This issue was at ezquake v2 & still exist at ezquake latest nightly build 2017-01-07-ec7f207.

**Comment by meag** [comment]
Can confirm this and have a branch with a fix - need to test it has no impact on fps before including though.
