### ISSUE TITLE
BUG: macOS Sierra does not support trackpad with in_raw = 1

### ISSUE THREAD

**Issue by fzwoch** [ezQuake/ezquake-source#192]
```
IOHIDManagerSetDeviceMatching(mdata->hid_manager, NULL);
```
Handing NULL in here is supposed to enumerate all devices. Seem like on macOS Sierra this does not include the trackpad anymore.

Can't see a way to fix this atm..

**Comment by siberex** [comment]
Mac OS Catalina 10.15.4 works fine with trackpad. Probably fixed?

**Comment by fzwoch** [comment]
Is that with `in_raw` set to `1`? Can anyone else confirm that (as I have no mac)?

Perhaps "fixed" or changed it again. It definitely wasn't us changing anything in the code.

**Comment by siberex** [comment]
@fzwoch in_raw is set to 1, yes

**Comment by blaps** [comment]
I'm on Catalina 10.15.5
Touchbar won't work with either in_raw 1/0
Fresh nquake install with ezQ 3.2.1

**Comment by fzwoch** [comment]
What the hell is the touchbar supposed to do?!

**Comment by meag** [comment]
Closing (siberex reports this as fixed)
Touchbar seems to be a different issue, open in #354
