### ISSUE TITLE
REQ: HUD - "ammo show_always", coop HUD elements and "clock format 4"

### ISSUE THREAD

**Issue by VianTORISU** [ezQuake/ezquake-source#206]
~~Removes `scr_newhud 2` "curse" that way; still using it for a years.~~

`hud_ammo_show_always`
Literally. Could be useful in (Mega/Custom/You_name_it)TF and other gamedirs.
// hud262 for this is not an option: there's no `hud262_scale`

Coop HUD elements:
`kills` and `secrets`

`hud_clock_format 4`
Similar to `cl_clock 1`. `hud_clock_format 5` for no hours.

**Comment by meag** [comment]
Hi - what would `hud_ammo_show_always` fix?

**Comment by VianTORISU** [comment]
`hud_ammo_show_always` would rather replicate classic HUD's "feature" than "fix" - showing ammo even when using axe/melee

**Comment by meag** [comment]
What would it show, just blank space?  Is the problem that any other hud items depending on those elements also disappear?

**Comment by VianTORISU** [comment]
"Just blank space" sounded like a fix, but I didn't mean that. You thought about `iammo` instead?
Classic HUD's "feature" about `ammo` is... even when using melee, it still displays ammo - just 0... or cells without icon when using, let's say, spanner in TF but something lagged. New HUD's `ammo` wouldn't display that

**Comment by meag** [comment]
@VianTORISU so you want a 0 instead of a blank space for ammo count, but blank space for iammo?

**Comment by VianTORISU** [comment]
> 0 instead of a blank space for ammo count

Almost... and I'm kinda confused. Looks like I forgot to mention about that, thus current `ammo show_always` isn't what I expected: `ammo show_always` always displays ammo count no matter what, just like classic HUD does.

**Comment by meag** [comment]
Hi

Sorry can you explain this one last time (I haven't looked at it for a while) and we can get this closed off?

Thanks,
meag

**Comment by VianTORISU** [comment]
Seems like I omitted some detail about `ammo show_always`, thus current implementation of it (blank space) isn't what I expected and it confused me.

In Classic HUD, ammo count is always displayed no matter which ammo type is used; some mods use that to display custom ammo.
Basically, I wanted `ammo show_always` to... always display ammo count

**Comment by meag** [comment]
@VianTORISU can you check if the HUD ammo is working as expected now?

**Comment by VianTORISU** [comment]
Yep, it works as expected... _(finally)_ Thanks

**Comment by meag** [comment]
Closing - have created discussion for the remaining items (hud elements for secrets & monsters killed - will probably implement as multiple static_text hud elements and add $sp_kills or somesuch)
