### ISSUE TITLE
BUG: Crosshair becomes smaller with larger `vid_conscale` and vice versa

### ISSUE THREAD

**Issue by Calinou** [ezQuake/ezquake-source#214]
See screenshots below. `vid_conscale` is set to 1, then 3, then 5. The crosshair becomes smaller as it is increased, which is probably not expected – it should become larger as it is increased.

Other settings are exactly the same (including crosshair settings) – however, this was tested only with the classic HUD.

![conscale_1](https://cloud.githubusercontent.com/assets/180032/25502120/a84f6e7c-2b95-11e7-803b-c32a5fc98ec5.jpg)
![conscale_3](https://cloud.githubusercontent.com/assets/180032/25502121/a87149de-2b95-11e7-85bf-4cef989167a4.jpg)
![conscale_5](https://cloud.githubusercontent.com/assets/180032/25502122/a88708b4-2b95-11e7-9053-e6bd86244a89.jpg)

**Comment by ciscon** [comment]
I cannot replicate this in my client, which build/os are you using?

**Comment by Calinou** [comment]
> I cannot replicate this in my client, which build/os are you using?

I'm using a self-compiled ezQuake at commit https://github.com/ezQuake/ezquake-source/commit/6fc2946c6f4b912053bff0927a4e6b136f830a54 with nQuake data, on Linux.

However, I tested this on my laptop too (which also is on Linux, but has a 4K display), and it's a bit strange, actually. The crosshair size does not vary between `vid_conscale` 1, 2 and 3, but starting from 4, it becomes larger or smaller in a seemingly random pattern, although it's always the same size for a given value. (I typically use `vid_conscale 5` on my laptop due to it having a hiDPI display.)

**Comment by meag** [comment]
I can replicate this, I think it's down to vid_conscale causing the effective console resolution to not be a multiple of 320 (?)  The built-in crosshairs aren't images, they're scaled to the size of a character.  I'll look into it when finishing off fix to #189.

**Comment by meag** [comment]
Can you try again with the latest nightly?  There are some extra cvars to play with: `/crosshairscale` and `/crosshairscalemethod` (if the crosshair disappears when this is enabled, you need to increase `/crosshairsize` too)

**Comment by meag** [comment]
Closing, believe this is now fixed.

**Comment by meag** [comment]
(whoops... actually closing)
