### ISSUE TITLE
BUG: tempnam() is deprecated

### ISSUE THREAD

**Issue by SauliusGe** [ezQuake/ezquake-source#233]
[LD] ezquake-linux-x86_64
.ezquake/common.o: In function `COM_GetUniqueTempFilename':
/home/s/ezquake-source/common.c:372: warning: the use of  `tempnam' is dangerous, better use `mkstemp'

**Comment by meag** [comment]
Thanks for this - it isn't an error, just a warning about a deprecated function.  It affects all linux systems, unfortunately the functions need quite a bit of changing to make the switch.  We'll get round to it eventually :)

**Comment by Eonfge** [comment]
This issue is getting a bit more urgent. Newer versions of GCC will no longer compile EZQuake:
https://flathub.org/builds/#/builders/32/builds/26248

**Full log**
https://flathub.org/builds/#/builders/48/builds/3061/steps/6/logs/stdio

**Comment by jite** [comment]
The errors seen above are not related to tempnam() though, it’s still a warning only (and will most likely remain so, as there’s nothing wrong with tempnam() if used correctly)

**Comment by meag** [comment]
This should have been fixed in https://github.com/ezQuake/ezquake-source/commit/d02add0d31e49e713f758305ca0559856c9186e2#diff-a7bcf42d6e08aeaa7b8525d5f726e351fe8feb0d07c85390ec46cbbd66689a83L381-L401
