### ISSUE TITLE
msg_badread in packet entities when someone else is on Facebook

### ISSUE THREAD

**Issue by mjb2010** [ezQuake/ezquake-source#241]
When someone else on my local network is doing ordinary stuff online, like browsing the web, scrolling through their Facebook feed, or even sometimes when they just send me an IM, my ezQuake connection to a remote server will sometimes get very laggy and then die with "msg_badread in packet entities", sometimes within a matter of seconds.

It seems that the WiFi user's activity should not be causing such interference.

I am using a current nightly build on Win7 Pro 64-bit. It is a Core i5 desktop (not heavily loaded) on a wired connection to the router (an AirPort Time Capsule) and the other person on my network is using WiFi via the same router. Let me know if you need more info or want me to test something.

**Comment by jite** [comment]
Hehe, sorry but this entirely on your side. Please have a look at your network equipment and consider an upgrade. If ezQuake gets msg_badread it means that something went wrong during transfer of packets, and that's completely outside of our control and totally within your networking environment (ISP included).
