### ISSUE TITLE
REQ: Please provide a release tarball

### ISSUE THREAD

**Issue by tdm4** [ezQuake/ezquake-source#248]
Hi there,

I'm attempting to create an ezquake OpenBSD port.

Please consider adding a source release tarball, the automatically generated github source downloads are not guaranteed to be immutable and are an issue for systems packaging ezquake from source (like OpenBSD and possibly others) that need checksums.

More information on the issue caused by automatic downloads:
https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

Thanks!

**Comment by jite** [comment]
Thanks, we'll definitly consider this for the 3.1 release (coming soon).

**Comment by tdm4** [comment]
@jite - Just wondering how long before 3.1 gets released? I'm really eager to submit this port to the official OpenBSD repos. I had been testing specific commits and I'm really happy with it. Just curious how far away are we? Thanks!

**Comment by meag** [comment]
Hi there - can you confirm if it's enough for me to just download the automatically generated github download then re-upload it and attach it to the release?

**Comment by tdm4** [comment]
Hi @meag - Sure that's fine! As long as the release tarball doesn't change or get 'recreated'. That is perfect.

**Comment by tdm4** [comment]
Hi @meag - can you upload a source tarball into the releases rather then the autogenerated one?
Thanks!

**Comment by tdm4** [comment]
@meag - That works a treat! Thanks very much for doing this! The OpenBSD port is updated now. :+1:

**Comment by meag** [comment]
No problem at all, thanks for this.
