### ISSUE TITLE
BUG: Screen is frozen

### ISSUE THREAD

**Issue by drzel** [ezQuake/ezquake-source#252]
After compiling from source on Debian testing, I'm able to launch the binary, it displays the menu, and the game is playing sounds and responding to keyboard movements, but the screen doesn't update, just a stilll image of the menu.

If I alt-tab and return to the game, the video output is updated to the current state but the video doesn't move.

Not sure exactly what information is helpful in debugging this issue but can provide whatever is needed. :)

**Comment by ciscon** [comment]
I'll blame compositing, disable compositing in your window manager and see if that helps.

**Comment by fzwoch** [comment]
Debian/Sid, Intel GPU, under GNOME Wayland - not having such issue.

**Comment by deathtrip** [comment]
I have the same problem under KDE on Arch Linux. It only happens when the game is in full screen mode, when i change the window size or put the window below others it works.

**Comment by meag** [comment]
Does this happen with `/vid_usedesktopres 0`?

**Comment by drzel** [comment]
> I have the same problem under KDE on Arch Linux. It only happens when the game is in full screen mode, when i change the window size or put the window below others it works. Using AMD open source driver.

I have the same experience. Game works fine in a window. Also on the AMD open source drivers.

**Comment by deathtrip** [comment]
I can get it to work in fullscreen with /vid_usedesktopres 0 and /vid_restart. But when i try to change the resolution to my native one after that, the game becomes unresponsive again. So it only works with lower resolution.

**Comment by drzel** [comment]
> I can get it to work in fullscreen with /vid_usedesktopres 0 and /vid_restart. But when i try to change the resolution to my native one after that, the game becomes unresponsive again. So it only works with lower resolution.

I have the same issue.

**Comment by ezzzzq** [comment]
I have this trouble in client ezquake 3.2 - dev 5232, Linux Ubuntu 16.04 + ATI. This freeze only in resolution 1920x1080, after change resolution to 1600x900 all is work without freeze

**Comment by meag** [comment]
Is this problem still active?  If it's still a problem in 3.2, can someone try the latest 3.6 and see if it's an issue there?

Is everyone on the same AMD driver?

**Comment by fzwoch** [comment]
Running Debian sid / GNOME on AMD now as well. Never had seen this behavior in the last year or so. I have seen similar report of OBS capturing GNOME windows not updating. So I would blame this on old/buggy version of GNOME/wayland/sdl2, but I don't think this is a problem originating from ezQuake.

**Comment by deathtrip** [comment]
It stopped happening to me some time ago.

**Comment by meag** [comment]
Thanks @fzwoch & @deathtrip, I'll close this for now.
