### ISSUE TITLE
REQ: support directories in cfg_save

### ISSUE THREAD

**Issue by mushis** [ezQuake/ezquake-source#254]
example: `/cfg_save samples/moo.cfg`
would save moo.cfg in: `/ezquake/configs/samples/`

this would be useful to "categorize" configs. like "samples" exist in nQuake, other "categories" can exist also.
and for example for config backups. a fool proof backup:
`/cl_onload "cfg_save backups/config-backup-$date"`

**Comment by meag** [comment]
Should be fixed by https://github.com/ezQuake/ezquake-source/commit/b60d85b5df821f9e6a44b4d5b76ee777d44a85a8
