### ISSUE TITLE
BUG: OS display scaling setting not restored on exit in Gnome Shell 3.28

### ISSUE THREAD

**Issue by drzel** [ezQuake/ezquake-source#262]
I'm using Debian Unstable. AMD open source drivers. 4K monitor.

To replicate:
- In Debian Settings > Devices > Displays > Scale > 200%
- Launch ezquake ensuring that `vid_usedesktopres 0`
- Quit
- Debian's scaling is now 100%.

**Comment by drzel** [comment]
After further testing, the above is true when using X11.

On Wayland it seems to work as expected.

**Comment by jite** [comment]
Unfortunately I think that’s an SDL2 bug rather than ezQuake bug. We (actually SDL2) create a new window that we operate on, when it’s closed SDL2 should restore settings. The only thing we do separatly in some cases is deal with hw gamma. Which SDL2 version are you using?

**Comment by meag** [comment]
Closing, please re-open if still an issue.  (suspect library issue rather than ezquake)
