### ISSUE TITLE
BUG: Launching game with `-game fortress` doesn't exec cfgs in gamedir

### ISSUE THREAD

**Issue by drzel** [ezQuake/ezquake-source#263]
Launching game with `-game fortress` doesn't exec cfgs in gamedir, but `gamedir fortress` from the console does.

**Comment by jite** [comment]
Thanks for reporting, next time please add the correct prefix as according to the wiki :)

Can you please elaborate more: OS? ezQuake version? Which configs do you expect it to exec?

I've tested both Linux and Windows on latest master with both `-game fortress` and `+gamedir fortress` having `autoexec.cfg` doing a simple `echo hello`, and they've both been executed automatically.

**Comment by drzel** [comment]
Will prefix future reports!

On windows 10 and expecting config.cfg to execute (as it does for `gamedir fortress`).

**Comment by drzel** [comment]
Neither `fortress/default.cfg` or `id1/default.cfg` is executed when launching with `-game fortress` also.

**Comment by gmtandi** [comment]
on OS X returns "Segmentation fault: 11" when with -game or +gamedir args

**Comment by meag** [comment]
Hi @drzel 

Looking at the init code, I can see:

- file system is initialised (-game command kicks in here)
- `default.cfg` is loaded into buffer
- `cfg_load config.cfg` (or equivalent `+cfg_load` in command line) loaded into buffer
- buffer executed
- `+set x y` in command line added to buffer
- buffer executed
- (internal system startup)
- `autoexec.cfg` loaded

So I think you would have to set `/cfg_use_gamedir 1` in `./fortress/default.cfg` and that would load the config from the fortress directory?  (working here).  Or you could specify another `cfg_load` in autoexec but that would break the +cfg_load being parsed from the command line.

Does this help at all?

- meag

**Comment by drzel** [comment]
It does help - thanks!
