### ISSUE TITLE
BUG: cannot fire weapon after loading saved game

### ISSUE THREAD

**Issue by deathtrip** [ezQuake/ezquake-source#283]
Sometimes randomly when playing single player and loading a saved game after dying, i cannot fire any weapon. Only loading the save again or restarting the game seems to help. I use the 64-bit Linux version.

**Comment by meag** [comment]
Could you attach an example save game file that has that problem?  You should see the location of the  .sav file in the console when saving.

And just to confirm: you die, load the saved game while still dead, and can't fire?

**Comment by deathtrip** [comment]
Yes, i load while still dead. It happens randomly, not with  just one save.
I will try to attach one file after it happens again.

**Comment by meag** [comment]
INFO: This has been reported previously @ https://sourceforge.net/p/ezquake/bugs/281/

**Comment by deathtrip** [comment]
I save using the default key, and when i die, i let the game load the last save automatically.

**Comment by deathtrip** [comment]
The default key to save is F5. However since version 3.1 came out, it hasn't happened again. I'll post if the bug reappears.

**Comment by meag** [comment]
I'm going to close this as I managed to replicate this behaviour (which was then fixed by that commit) when investigating https://github.com/ezQuake/ezquake-source/issues/297

If it comes up again we will re-open.
