### ISSUE TITLE
REQ: add /aliasprint command

### ISSUE THREAD

**Issue by mushis** [ezQuake/ezquake-source#287]
there is one command missing from alias commands.

![image](https://user-images.githubusercontent.com/3011167/43394546-07a01428-93f3-11e8-8c60-7bc1b4139fb3.png)

one command to just print the alias content (show). `/aliasprint <alias>`? 
similar to /_aliasedit_ but without editing. the user could use that command to see what the alias contains without risking to delete it.

**Comment by meag** [comment]
Anyone have objection to `/alias x` printing the content of the alias, `/alias x ""` to clear it?

**Comment by meag** [comment]
Up2 has pointed out the /viewalias command which does exactly what you're after... :)

**Comment by meag** [comment]
`/alias x` now prints the contents, fixed in 3.1
