### ISSUE TITLE
messagemode2 seems broken

### ISSUE THREAD

**Issue by lordee** [ezQuake/ezquake-source#293]
https://imgur.com/a/js61K65

"hi" is messagemode
"team" is messagemode2 - my name comes up as pla.  No brackets to indicate team talk, not sure if teammates could see it or if it broadcasts to all

**Comment by meag** [comment]
Hi there

Check `cl_fakename`.  It's so common for teambinds to use line-feed to replace the player's name, it's built in to the client.

As BLooD_DoG pointed out, it's part of the nquake readme.txt:
```
5. My teamsays get displayed with a "pla" in front of them. How do I change this?

It is changed by either issuing "/cl_fakename <name>" (three letter abbreviations
are usually used as fakename), or by changing the setting in the ezQuake menus
(Options -> Player -> Player Settings -> Teamchat Name).
```

It only affects MM2, so only your teammates would have seen it.
