### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by aaleonov** [ezQuake/ezquake-source#303]
Hello.
I compiled a client with these keys: make -j2 CFLAGS=-g
With a different period of time the client falls. (20-90 min). What the client console writes:
>Received signal 11, exiting...
DOUBLE SIGNAL FAULT: Received signal 11, exiting...
munmap_chunk(): invalid pointer
DOUBLE SIGNAL FAULT: Received signal 6, exiting...
Segmentation fault (core dumped)

I'm trying to use for debugging **gdb**. Here is my result:

> (gdb) attach 5224
Attaching to process 5224
[New LWP 5234]
[New LWP 5235]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
0xb7f49d09 in __kernel_vsyscall ()
(gdb) continue 
Continuing.
[New Thread 0x8988fb40 (LWP 5569)]
[New Thread 0x88effb40 (LWP 5570)]
[Thread 0x88effb40 (LWP 5570) exited]
[Thread 0x8988fb40 (LWP 5569) exited]
[New Thread 0x8988fb40 (LWP 5571)]

>Thread 1 "ezquake-linux-i" received signal SIGSEGV, Segmentation fault.
0xad3db696 in ?? () from /usr/lib/i386-linux-gnu/dri/i915_dri.со

I think that this is not all the information that I can get from the **gdb**.
What actions do I need to do with **gdb** and what other information I should provide for a full error report.

**Comment by ciscon** [comment]
This is almost certainly a problem in i915 rearing its ugly head.  Which version/release of linux are you using and which window manager/desktop environment?

**Comment by ciscon** [comment]
To get a full trace make sure you haven't let make strip the binary.  You may also want to run it with valgrind to see if that gives you any useful information.

**Comment by aaleonov** [comment]
>release of linux

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
>desktop environment

Name: Openbox
Class: 
PID: N/A
Window manager's "showing the desktop" mode: OFF
>To get a full trace make sure you haven't let make strip the binary.

how can I make sure of it?
Now I will try to understand valgrind.

**Comment by aaleonov** [comment]
Here is what I managed to get from valgrind.
[valgrind.txt](https://github.com/ezQuake/ezquake-source/files/2609175/valgrind.txt)

**Comment by ciscon** [comment]
It certainly looks that way, though why it's only happening on 32 bit is a bit beyond me, I'm not seeing it.  Hopefully someone else will see something I'm not.  You may want to try compiling it with O0 to see if that makes a difference, if so it could be an optimization not working properly (this is why tree vectorize is disabled by default, before gcc 8 it would attempt to pass unaligned variables into sse because documentation says you can, but you can't)

**Comment by aaleonov** [comment]
I have no knowledge in this area. Tell me please, these parameters will be valid for compilation:
make -j2 CFLAGS='-g -O0'
You can answer in simple language, it is difficult for me to understand the translation. Thank you very much.
After compiling, I need to debug with the help of GDB, as I did before?

**Comment by jite** [comment]
Hi,

Try compiling with the provided build-linux.sh instead and see if makes a
difference. I haven't gone through the Makefile, but it's possible that you
are overwriting default CFLAGS.

**Comment by meag** [comment]
Is it a particular map that causes the crash, or all maps?

**Comment by aaleonov** [comment]
> Is it a particular map that causes the crash, or all maps?

I did not pay attention, but the crash on different maps.

I will ask in another forum about analyzing methods using gdb. And find out the causes of the fall.

**Comment by meag** [comment]
Any progress on this?

**Comment by meag** [comment]
Closing for now, please re-open if this is still an issue
