### ISSUE TITLE
BUG: display of hud_score_difference is never negative

### ISSUE THREAD

**Issue by qirex-rd** [ezQuake/ezquake-source#304]
The score difference HUD element always displays a non-negative number, even if the player currently a negative frag difference.

Using the [demo](https://badplace.eu/Game/Download/323545) of a [recent game](https://badplace.eu/game/index/323545/) as example:

At 00:14 the score was as follows:

![ezquake002](https://user-images.githubusercontent.com/32545925/49333813-bf33b700-f5c5-11e8-8b76-d7b03b46ef77.png)

On Anni's POV the score difference (the number right of the game clock at the bottom center of the screen) in the HUD is "1":

![ezquake003](https://user-images.githubusercontent.com/32545925/49333817-c5c22e80-f5c5-11e8-8575-8e2272dad813.png)

On Klice's POV the score difference in the HUD is also "1" instead of "-1":

![ezquake001](https://user-images.githubusercontent.com/32545925/49333802-8a276480-f5c5-11e8-83f6-e8a7aaa40a9b.png)

My `hud_score_difference_*` cvars are:

```
hud_score_difference_align            "center"
hud_score_difference_align_x          "after"
hud_score_difference_align_y          "bottom"
hud_score_difference_colorize         "1"
hud_score_difference_digits           "0"
hud_score_difference_frame            "0"
hud_score_difference_frame_color      "0 0 0"
hud_score_difference_item_opacity     "1.0"
hud_score_difference_order            "11"
hud_score_difference_place            "gameclock"
hud_score_difference_pos_x            "4"
hud_score_difference_pos_y            "0"
hud_score_difference_scale            "1"
hud_score_difference_show             "1"
hud_score_difference_style            "3"
```

`ezquake +version`:

```
ezQuake 3.2-dev r5201~b83dd8ae
exe: Nov 21 2018 12:34:16
Compiled with GCC version 4.2.1 (6138635)
GCC Optimization: Optimized for speed
GCC Optimization: Functions currently inlined into their callers
```

ezQuake 3.1 correctly displays the score difference at Klice's POV as "-1".

**Comment by qirex-rd** [comment]
I was able to identify the commit introducing this bug: f6917ef0def49af8040acbfe75c282f220e2d511

**Comment by meag** [comment]
What values do you have for `/hud_sortrules_includeself` and `/teamlock` please?

**Comment by qirex-rd** [comment]
It's working.  Thanks!

**Comment by mushis** [comment]
will this work on team games?
