### ISSUE TITLE
RULESETS: Allow replacement backpack textures in ruleset thunderdome

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#306]
Requested by Thunderdome admin VVD, 17th December 2018

**Comment by VVD** [comment]
Thanks.
https://github.com/ezQuake/ezquake-source/blob/master/rulesets.c#L42-L52
- return rulesetDef.ruleset == rs_smackdown || rulesetDef.ruleset == rs_thunderdome || rulesetDef.ruleset == rs_qcon;
+ return rulesetDef.ruleset == rs_smackdown || rulesetDef.ruleset == rs_qcon;

But custom models are not allowed!

**Comment by Calinou** [comment]
:+1: — I'd like to display backpacks as simple items to be consistent with the rest of items, but currently this is only possible in the "ezQuake default" ruleset.

**Comment by VVD** [comment]
@Calinou, it's custom texture, not custom model.

**Comment by fourier** [comment]
I agree with @Calinou , if custom texture for backpack is allowed, then the simpleitems is on the backpack should be presented as a simpleitem as well.

**Comment by VVD** [comment]
Agree to allow both - custom textures and simple items for backups in ruleset thunderdome.

**Comment by VVD** [comment]
Thanks!
