### ISSUE TITLE
BUG: Razer Deathadder Chroma mouse not working in 3.1

### ISSUE THREAD

**Issue by NightAvenger** [ezQuake/ezquake-source#307]
Hello

Been using ezQuake for a while with no problems until today using 3.1 for the first time.

Installed the fortressone client which uses 3.1, and noticed no mouse input working at all, messed around with settings, updated my mouse drivers, graphics drivers, nothing, uninstalled mouse drivers, nothing, restarted many times, went thru every mouse variable in the console, nothing.

The only thing is if I turned Raw mouse input OFF it did make it work but it was _completely_ unplayable and you could barely mouselook/move it around, just went all spazzy and weird.

Then I tried my other mouse which is a logitech g400s, and works totally fine.

so I assume there may be an issue with Razer Chroma's 

Hope this helps!

**Comment by NightAvenger** [comment]
Ok so RIGHT after I posted this I randomly moved my Razer mouse and... it now works in game. 

Something weird with having to connect another mouse just to get it to work tho?

**Comment by meag** [comment]
Hi there - can you confirm which operating system you're using please?

**Comment by NightAvenger** [comment]
Windows 10 64bit.

**Comment by meag** [comment]
Hi

This sounds more like a driver error, please let us know if this is still valid.

Thanks,
