### ISSUE TITLE
BUG: ezquake silently crashes to desktop when a "bad"  png file is loaded

### ISSUE THREAD

**Issue by BorisU7** [ezQuake/ezquake-source#317]
Currently error handling for PNG loading is simply disabled. Of course their setjmp method is not nice, but crashing to desktop without any message is worse IMHO. To make things even worse, libpng made some internal changes in version 1.6 leading to some png files considered invalid now, though they were ok in the version 1.4 of the library.
I can fix this but before creating a pull request I'd like to know, if it is worth to fix also the separate dynamically loaded libpng codepath? why it even exists?

**Comment by meag** [comment]
Given

```
#ifdef WITH_PNG
#ifndef WITH_PNG_STATIC
#define WITH_PNG_STATIC
#endif
#endif

#ifdef WITH_JPEG
#ifndef WITH_JPEG_STATIC
#define WITH_JPEG_STATIC
#endif
#endif
```

in quakedef.c, I'd have to say no, there's no point in it and it can be removed.

(If someone else has an opinion please shout now)

**Comment by meag** [comment]
(The dynamically loaded libpng/libjpeg code has been removed)

**Comment by meag** [comment]
Can you supply an example png file?
