### ISSUE TITLE
BUG: `re_trigger`s doesn't work when playing online

### ISSUE THREAD

**Issue by VianTORISU** [ezQuake/ezquake-source#327]
Subj, even with "default" ruleset, also `cfg_save` doesn't save these.
Tried with 3.2-dev r5243~bb70ccb (latest nightly) - same result

**Comment by meag** [comment]
Are you sure they weren't disabled by the server?  That works irrespective of ruleset.

**Comment by meag** [comment]
Closing, please report back if it wasn't the server blocking it.
