### ISSUE TITLE
libpcre.so.1 depedency wont let me run it in Debian 9

### ISSUE THREAD

**Issue by aprekates** [ezQuake/ezquake-source#330]
I installed the nQuake script.
I run it.  pak file found ok . 
ezquake tar buid.
I untar and try to execute ezquake-linux-x86_64 :-1: 
./ezquake-linux-x86_64: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory

Unfortunately in Debian 9 i found only:
libpcre3: /lib/x86_64-linux-gnu/libpcre.so.3
libpcre2-16-0: /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0

**Comment by Calinou** [comment]
As a workaround, you can [build ezQuake from source](https://github.com/ezQuake/ezquake-source/blob/master/COMPILING_ON_LINUX.txt).

**Comment by ciscon** [comment]
fyi, build-linux.sh will install all dependencies for you.

**Comment by aprekates** [comment]
I compiled it. 
homwitt@enous:~/Λήψεις/ezquake/ezquake-source-master$ ./build-linux.sh 
[STEP ] Install/check dependecies (packages)...
[INFO ] You might be prompted to input your password as superuser privileges are required.
[INFO ] Updating apt repo list... (running with sudo)
[sudo] password for chomwitt: 
W: GPG error: http://debian-mirrors.sdinet.de/deb-multimedia stable InRelease: Οι παρακάτω υπογραφές δεν ήταν δυνατόν να επαληθευτούν επειδή δεν ήταν διαθέσιμο το δημόσιο κλειδί: NO_PUBKEY 5C808C2B65558117
W: The repository 'http://debian-mirrors.sdinet.de/deb-multimedia stable InRelease' is not signed.
[INFO ] Checking/installing required packages... (running with sudo)
[STEP ] Cleaning up any previous build files...
[STEP ] Compiling sources (this might take a while, please wait)...

Build completed successfully.
Copy ezquake-linux-x86_64 into your quake directory.

I copied it to the directory i've made following nquake script but now i get:

Error: Couldn't load gfx/palette.lmp

**Comment by ciscon** [comment]
in the directory you have that binary should be an id1 directory, and inside of it pak0.pak and pak1.pak, that error means it couldn't find id1/pak0.pak

**Comment by aprekates** [comment]
Thanks. I thought that because the  nQuake script found the pak file to the path i gave that that step was done. 
Anyway it run. 
Thanks!!

**Comment by h1z1** [comment]
The files are case sensitive.   Might be called PAK01.PAK and PAK02.PAK, works after renamed to lowercase.

**Comment by rhulha** [comment]
I had the same issue on Linux Mint 19.2 (very current version).
I issued the following command:
`sudo apt–get install libpcre3`

And then I went into:
`cd /usr/lib/x86_64-linux-gnu/`

And then I copied the lib:
`sudo cp libpcre.so libpcre.so.1`

And then ezquake started and ran for me.

**Comment by meag** [comment]
Think this is because they've been built in either Arch or an old version of Ubuntu in the past - will be using newer Ubuntu in future.

**Comment by h1z1** [comment]
@meag - Define "newer".   Hopefully you retain backward libc compatibility (2.17)

**Comment by meag** [comment]
@h1z1 what image of Ubuntu would we have to use for that?  https://docs.travis-ci.com/user/reference/overview/

It's getting to the point where we'd have to release about 3 or 4 different versions for both linux & osx.

**Comment by iriki** [comment]
For Mint 21/Ubuntu 20.04:

$ find / -iname libpcre.so\* 2>/dev/null 
/usr/lib/x86_64-linux-gnu/libpcre.so.3
/usr/lib/x86_64-linux-gnu/libpcre.so.3.13.3

$ sudo ln -s /usr/lib/x86_64-linux-gnu/libpcre.so.3 /usr/lib/x86_64-linux-gnu/libpcre.so.1
