### ISSUE TITLE
META: Flatpak support

### ISSUE THREAD

**Issue by Eonfge** [ezQuake/ezquake-source#337]
I was thinking about supporting ezQuake with Flatpak on Flathub:
https://github.com/flathub/flathub/pull/1173

The idea is fairly simple: Flatpak allows anybody to maintain a single Linux distributable, which can be updated any time thanks to the wide system integration of Flathub. As it stands, I have a test-ready version available (See the end of the pull request) but I do want to know if you as a project care about this.

Right now, there are some minor issues that I tackled myself. At the moment, id1 data is for example loaded from the same directory as the executable, but I redirect this to the ~/.ezquake/ directory of the user. In the future, it would be nice if this could be supported mainline, but I also understand that you have other concerns at the moment.

A second point of focus, would be the inclusion of appdata.xml, icons and a .desktop file in your project. I can understand that you have no interest in storing such data in the main project, but with more advanced packaging systems that would be really beneficial.

Anyway, let me know if you run into any problems with the test version and what you think of the idea.

**Comment by meag** [comment]
```
At the moment, id1 data is for example loaded from the same directory as the executable, but I redirect this to the ~/.ezquake/ directory of the user
```

Would this sort of thing help with deployment on MacOS too?

**Comment by fzwoch** [comment]
On macOS we use `-basedir` now to point a specific user directory. Seemed to work fine, but I never tested it thoroughly. But it sounds fine in theory. Besides signing I think deployment on macOS is fine.

**Comment by ciscon** [comment]
this is how the working directory is passed into the appimage build as well, and the debian package also transparently does it.

**Comment by Eonfge** [comment]
Wait, let me re-open this but with a follow-up question.

The Flathub package uses the xdg-desktop standard for files and metadata. In other words, the logo, .desktop file and the metainfo.xml all follow the `io.github.ezQuake` reverse-url slug. Where should I commit these, because it would be preferable to make these a part of the official project?

**Comment by meag** [comment]
`misc/flatpak` ?  Or do they have to be in the root directory?

**Comment by Eonfge** [comment]
O, they can be anywhere really. If you don't have an integrated build system like meson, you can just dump them in `/dist/linux/`. It's quite common to have a `/dist/` folder, where linux, macosx and windows can each have their own set of meta-data.

**Comment by meag** [comment]
Feel free to submit a pull request.  I'd better point out that we have meson build, lest Tuna hunt me down

**Comment by Eonfge** [comment]
I've made a pull request with the files. @meag Directly related to the Meson build... how serious is that? All documentation refers to _make_ and currently the Flathub package also uses it. I don't mind switching to Meson, but I do want to know that it's the 'intended' way to package.

**Comment by meag** [comment]
Thanks for this.

The meson build is supported, I'll get it added to automated builds at some point.  There was a long period where I couldn't get it to work but that was my weird linux installs, had to install fresh and it worked first time.  Had to finally admit @fzwoch hadn't been making it all up and it did actually work, was a very bad day.  But it will be equal with `make` for some time to come I imagine, rather than being preferred over the others.

Thanks again,
