### ISSUE TITLE
Feature request: add possibility to specify a monitor to run on

### ISSUE THREAD

**Issue by turbozapekanka** [ezQuake/ezquake-source#338]
I have two monitors and my gaming monitor is secondary in windows.
Every time I want to play quake I have to go to windows settings and switch it to main, what troubles me a lot.
Please add a possibility to somehow set a monitor in config file or exe parameters and make my life easier.
I will play quake more often If this feature is implemented.
thank you

**Comment by liback** [comment]
This already exists:
vid_displaylist to show available monitors
vid_displaynumber to set monitor
vid_restart for change to take effect

**Comment by meag** [comment]
@turbozapekanka please re-open if Ake's suggestions don't work.
