### ISSUE TITLE
REQ: Restore old feature /berzerk

### ISSUE THREAD

**Issue by blaps** [ezQuake/ezquake-source#339]
Could be enabled by one player, but should probably be votable.

When enabled, berzerk activates when there is 20 seconds left of a match, and:
1. Everyone gets quad for the remaing time (even if you die and respawn)
2. Screen flickers with an epileptic strobe effect each second 
Classic mayhem!

**Comment by fzwoch** [comment]
Isn't that a mod thing?

**Comment by blaps** [comment]
Could've been KTpro or even older server mod.

**Comment by meag** [comment]
Closing: this would have to be implemented in KTX
