### ISSUE TITLE
Texture Filtering stays enabled on viewmodels even when disabled.

### ISSUE THREAD

**Issue by Zungrysoft** [ezQuake/ezquake-source#340]
When I set gl_texturemode to GL_NEAREST, I expect that to apply to viewmodels, like it does with level textures and every other model in the game. However, the model stays filtered.

**Comment by flybitz** [comment]
Hi, some more info would be helpful.

What's your OS? What's your CPU/GPU combination? Are your graphics drivers up to date? What build of ezQuake are you using? Are you using any external textures?

I just compiled from git on Fedora 31 x64 on an i5-3230M and I can confirm gl_texturemode is respecting texture filtering.

![ezquake000](https://user-images.githubusercontent.com/59670984/72223475-c7825380-3534-11ea-9522-66d5d40d8978.png)
![ezquake003](https://user-images.githubusercontent.com/59670984/72223571-ed5c2800-3535-11ea-9b54-81fa2b456003.png)


All I've got in the test setup is id1/pak0.pak v1.06.

If you're on Windows you can try the latest nightly:

http://uttergrottan.localghost.net/ezquake/dev/nightlybuilds/win32/

I recommend copying id1/pak0.pak to a blank folder and testing it, just in case external paks are causing the issue.

**Comment by meag** [comment]
Think this problem arises because viewmodels follow the `/gl_texturemode2d` setting instead of `/gl_texturemode`
If you want to fix that, try `/gl_mipmap_viewmodels 1` (needs `/vid_restart`) in 3.5.

Have replaced with `/gl_texturemode_viewmodels` instead
