### ISSUE TITLE
hud_frags shows self always in 1st

### ISSUE THREAD

**Issue by heeen** [ezQuake/ezquake-source#342]
For some reason I am shown always in the first row, regardless of the actual spot in the scoreboard. This used to work differently where it would show the 3 next players above me (if any).

**Comment by meag** [comment]
Can you see if `/hud_sortrules_includeself` is affecting this?

**Comment by heeen** [comment]
yeah it is affecting it. none of the options restores how it used to work though.

**Comment by heeen** [comment]
am I misremembering how this used to work?

**Comment by heeen** [comment]
actually on my windows machine I found a 3.1 build and it works as I remember it. 3.2 build on my linux machine shows the new behaviour

**Comment by meag** [comment]
That's useful - each hud element had their own sort rules before (or none) so I tried to make them all use a common definition.  Can you upload the demo with the POV & timestamp where it misbehaves for you?

**Comment by heeen** [comment]
![Screenshot_20200212_225125](https://user-images.githubusercontent.com/1699754/74380744-6fb46200-4dea-11ea-9818-0dfd6f2e9d62.png)
here's a screenshot. It shows like this all the time so no demo required. just connect to qw.servegame.org:27500

**Comment by heeen** [comment]
compare to 3.1:
![ezquake014](https://user-images.githubusercontent.com/1699754/74381106-27e20a80-4deb-11ea-8987-3600d46a9e33.png)

**Comment by meag** [comment]
Thanks - can you upload your config please?

**Comment by heeen** [comment]
[config.zip](https://github.com/ezQuake/ezquake-source/files/4195264/config.zip)
that should be everything

**Comment by heeen** [comment]
Hey,

so I updated to master and at least with my config I am still always in first place on the hud. Do I need to change something in my config?

**Comment by heeen** [comment]
ok turns out hud_sortrules_includeself 0 restores how it was before. Thank you for maintaining ezquake!
