### ISSUE TITLE
REQ: Show aliased commands/variables in search/tab-complete

### ISSUE THREAD

**Issue by mr0wnage** [ezQuake/ezquake-source#348]
there is an **loadloc** command for loading a loc file without reconnect

it is not possible to find upon request '/cvarlist *loadloc*'
it is not present at tabulation (i mean type 'loadl' and push TAB)

**Comment by meag** [comment]
Is this a 3.5 issue?

In 3.5 `loadloc`, `saveloc`, `addloc` were all renamed `locations_*` to keep them together, and `loadloc` etc are just internal aliases to the old commands.

**Comment by mr0wnage** [comment]
idk about locations_* commands....
i guess we could close this issue

**Comment by meag** [comment]
This has come up before and causes a bit of confusion, especially with guides from the past floating about.  If they did appear somewhere we could be a bit more aggressive in tidying up.
