### ISSUE TITLE
libGL error: failed to load driver: rockchip (ARM, Pinebook Pro)

### ISSUE THREAD

**Issue by Eonfge** [ezQuake/ezquake-source#350]
I've found an issue running ezQuake on ARM, using the rockchip ARM processors. Project and package details are here:

https://github.com/flathub/io.github.ezQuake/pull/2

**System**
```
System:    Host: pinebookpro Kernel: 4.4.190-1233-rockchip-ayufan-gd3f1be0ed310 aarch64 bits: 32 gcc: 7.4.0
           Console: tty 0 Distro: Ubuntu 18.04.4 LTS
Machine:   No /sys/class/dmi; using dmidecode: no smbios data. Old system?
CPU:       6 core ARMv8 rev 4 (v8l) (-MCP-)  bmips:  arch: ARM
           clock speeds: max: 1512 MHz 1: 408 MHz 2: 408 MHz 3: 408 MHz 4: 408 MHz 5: 408 MHz 6: 408 MHz
Graphics:  Card: Failed to Detect Video Card!
           Display Server: N/A driver: modesetting tty size: 158x75 Advanced Data: N/A out of X
Audio:     Card-1 rk-es8316-spk-sound driver: rk-es8316-spk-s
           Card-2 rk-hdmi-dp-sound driver: rk-hdmi-dp-soun
           Sound: Advanced Linux Sound Architecture v: k4.4.190-1233-rockchip-ayufan-gd3f1be0ed310
Network:   Card: Failed to Detect Network Card!
Drives:    HDD Total Size: NA (-)
           ID-1: /dev/mmcblk1 model: N/A size: 62.5GB
           ID-2: /dev/mmcblk0 model: N/A size: 128.0GB
Partition: ID-1: / size: 118G used: 61G (54%) fs: ext4 dev: /dev/mmcblk0p7
           ID-2: swap-1 size: 0.34GB used: 0.00GB (0%) fs: swap dev: /dev/zram0
           ID-3: swap-2 size: 0.34GB used: 0.00GB (0%) fs: swap dev: /dev/zram1
           ID-4: swap-3 size: 0.34GB used: 0.00GB (0%) fs: swap dev: /dev/zram2
           ID-5: swap-4 size: 0.34GB used: 0.00GB (0%) fs: swap dev: /dev/zram3
           ID-6: swap-5 size: 0.34GB used: 0.00GB (0%) fs: swap dev: /dev/zram4
           ID-7: swap-6 size: 0.34GB used: 0.00GB (0%) fs: swap dev: /dev/zram5
Sensors:   System Temperatures: cpu: 18.8C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 264 Uptime: 1:01 Memory: 560.7/3874.1MB Init: systemd runlevel: 5 Gcc sys: 7.5.0
           Client: Shell (bash 4.4.201) inxi: 2.3.56 
```

**Flatpak package**
```
Flatpak 1.7.2
```
```
default
host
```
**ezQuake package**
```
          ID: io.github.ezQuake
         Ref: app/io.github.ezQuake/arm/test
        Arch: arm
      Branch: test
     Version: 3.1.0
     License: GPL-2.0
      Origin: ezquake-origin
  Collection: org.flathub.Stable.Build17824
Installation: user
   Installed: 22,0 MB
     Runtime: org.freedesktop.Platform/arm/19.08
         Sdk: org.freedesktop.Sdk/arm/19.08

      Commit: 5413763ddbb3803a9bd8a74979696f4a4d4cbf6dfd3c7acb5ad16595d9da08c5
     Subject: Support for ARM (653fabad)
        Date: 2020-04-19 15:13:21 +0000
```

**Logs**
- [ezQuake.stacktrace.arm.txt](https://github.com/ezQuake/ezquake-source/files/4499563/ezQuake.stacktrace.arm.txt)
- [ezQuake.errorlog.arm.txt](https://github.com/ezQuake/ezquake-source/files/4499564/ezQuake.errorlog.arm.txt)

I'm not sure how to proceed, and what info you could use now. Let me know if you need additional info.

**Comment by ciscon** [comment]
Can you try compiling it from source and running it without using a flatpak?

**Comment by Eonfge** [comment]
Got a different issue, DBus related:
[ezQuake.pinebook.arm.txt](https://github.com/ezQuake/ezquake-source/files/4499719/ezQuake.pinebook.arm.txt)

**Comment by ciscon** [comment]
try running build-linux.sh, it should work fine on arm assuming you're host box is actually ubuntu as it appears to be.  i can't say i've ever seen a problem with dbus, i'm assuming that's just appearing because of the actual problem which appears to be a libc call

**Comment by ciscon** [comment]
if you could run it with valgrind that might give you better output without any extra effort, and/or run "bt" when gdb sees it crash out to see if it gives you the actual problem.

**Comment by Eonfge** [comment]
I executed the build script just to be sure, and I ran into the same issue. I've put Valgrind against it, both a summary and a full log with backtraces.

[valgrind-out.txt](https://github.com/ezQuake/ezquake-source/files/4504634/valgrind-out.txt)
[valgrind-out.full.txt](https://github.com/ezQuake/ezquake-source/files/4504637/valgrind-out.full.txt)

**Comment by Eonfge** [comment]
@ciscon On the topic of the Rockchip issue. I also have this issue with GZDoom so that rules EZQuake out as responsible. By the looks of it, the Pinebook Pro does not have fully implemented Open GL drivers.

**Comment by Calinou** [comment]
I think GZDoom has an OpenGL ES 2.0 driver, but ezQuake definitely doesn't. It doesn't even have a software renderer anymore.

**Comment by Eonfge** [comment]
@Calinou they do actually have an issue on that topic:
https://github.com/ptitSeb/gl4es/issues/38

More food for thought

**Comment by jite** [comment]
ezQuake 3.2 (and backwards) uses fixed function pipeline which the Pinebook most certainly doesn’t support.

Ask @meag about OpenGL ES support in his 3.5 version (new renderer).

**Comment by Eonfge** [comment]
Well. I found it the root cause of the libGL error. 

It's nothing OpenGL, ezQuake or GZDoom related. It's because the distribution I was using, Ubuntu 18.04, was not providing the right kernel drivers for Rockchip. I missed the OpenGL drivers, which explained why this issue occurred with multiple applications.

I have found new roadblocks, but this issue is itself closed.
