### ISSUE TITLE
Unable to load custom graphics/skins

### ISSUE THREAD

**Issue by Poorchop** [ezQuake/ezquake-source#352]
I'm on the latest suse Tumbleweed snapshot. I've built ezQuake and it runs just fine but it doesn't load the [FortressOne](https://www.fortressone.org/) custom graphics. The directory is set up properly with the `fortress` folder alongside the `id1` folder, as well as the ezQuake binary in the same folder next to those two.

```
fortressone/
├── fortress/
│   ├── fortressone.pk3
│   ├── ...
│   ├── ...
│   └── ...
├── id1/
└── ezquake-linux-x86_64
```

I'm not sure what I'm doing wrong. In the console, I just get expected errors like `Couldn't load image crosshair"`. The HUD settings as defined in the custom config get loaded so it seems that config files are being read, but I'm not sure why it can't load/find the custom graphics in the fortressone.pk3.

**Comment by meag** [comment]
Hi there

Have you tried launching with `+gamedir fortress` in the commandline?  I don't have the cleanest `fortress` directory in the world but if I launch 3.2 with that I get the TF logo on the menu etc.

- meag

**Comment by Poorchop** [comment]
That did the trick, thank you. For some reason, launching the executable in Windows automatically loads the fortress mod so I assumed that the behavior would've been the same everywhere else.
