### ISSUE TITLE
cl_multiview affects rendered fps

### ISSUE THREAD

**Issue by mushis** [ezQuake/ezquake-source#353]
my settings:
cl_maxfps 1001
vid_vsync 0
ezquake 3.5 alpha 23

cl_multiview 2/3/4 affects rendered fps.
check top right
![ezquake133](https://user-images.githubusercontent.com/3011167/80163803-314bd800-85cf-11ea-9fb2-2e30532a1f1b.png)

so i've made some more tests, changed cl_maxfps to 500
cl_multiview 1 -> fps = 500
cl_multiview 2 -> fps increase to 1000
cl_multiview 3 -> fps increase to 1500
vid_vsync 1 -> correctly activates vsync regardless of cl_multiview value. fps back to monitor refresh rate.

edit: doesn't happen on 3.2

**Comment by meag** [comment]
Confirmed - it was broken in every version but 3.2, it's in the changelog:

`Multiview was trying to cause increase in frames rendered (/cl_maxfps multiplied for each extra view)`

3.5 is based on 3.1 so the bug will be there too - new version with 3.2's changes merged in coming soon.

- meag

**Comment by meag** [comment]
Closing, fixed in 3.2/3.6
