### ISSUE TITLE
BUG EX_Browser_pathfind: max neighbours count reached

### ISSUE THREAD

**Issue by mushis** [ezQuake/ezquake-source#361]
This happened to at least 3 players today. dunno what happened that has triggered this, it wasn't happening before.
What happened:

1. Loading ezQuake as usual, refreshed server browser, connected to a server. after a couple of seconds, client crashed, with error `Classic_LoadParticleTexures: can't load texture`
2. ok, ran ezQuake again. ERROR. `EX_Browser_pathfind: max neighbours count reached`
3. And now its giving that error right after executing ezQuake. I've restarted. I  debuged, tried many things. it happened in all the ezQuake versions i tested (i have multiple versions in my quake folder). 4. If ezquake/configs/config.cfg was deleted, client started normally. so the problem was somewhere in the config
5. I've realized if i deleted the entire "Server Browser" (sb_*) area from my config, it worked normally. Problem solved.

EDIT: 
5. `findroutes 1` seems to be the cause of the problem!! 
end Edit.
More people complained about this happening today!

here is the section i deleted from my config.cfg 
`sb_autohide                           "1"
sb_autoupdate                         "1"
sb_findroutes                         "1"
sb_hidedead                           "1"
sb_hideempty                          "0"
sb_hidefull                           "0"
sb_hidehighping                       "0"
sb_hidenotempty                       "0"
sb_ignore_proxy                       ""
sb_inforetries                        "1"
sb_infospersec                        "200"
sb_infotimeout                        "400"
sb_listcache                          "1"
sb_liveupdate                         "2"
sb_mastercache                        "1"
sb_masterretries                      "3"
sb_mastertimeout                      "1000"
sb_nosockraw                          "0"
sb_pinglimit                          "80"
sb_pings                              "3"
sb_pingspersec                        "200"
sb_pingtimeout                        "400"
sb_proxinfopersec                     "10"
sb_proxretries                        "3"
sb_proxtimeout                        "1000"
sb_showaddress                        "0"
sb_showfraglimit                      "0"
sb_showgamedir                        "0"
sb_showmap                            "1"
sb_showping                           "1"
sb_showplayers                        "1"
sb_showproxies                        "0"
sb_showtimelimit                      "0"
sb_sortplayers                        "92"
sb_sortservers                        "3132"
sb_sortsources                        "3"
sb_sourcevalidity                     "30"
sb_status                             "1"`

**Comment by gr4v3** [comment]
The function in line 114 in file EX_browser_pathfind.c halts the client startup

**Comment by mushis** [comment]
3.5 alpha 24 solves this issue

alternatively, edit your config and set /sb_findroutes 0 to avoid the problem

**Comment by Calinou** [comment]
I set `sb_findroutes 0` in all instances I could find in my ezQuake folder, but I still get this crash on startup with the same message.

**Comment by mushis** [comment]
further instructions here 
https://www.quakeworld.nu/news/1108/ezquake-max-neighbours-count-reache
`WORKAROUND
To circumvent this you can disable the find-best-route feature for now:
Set sb_findroutes 0 in ezquake/config.cfg
Set sb_listcache 0 in ezquake/config.cfg
Rename proxies_data to proxies_data.bak (located in This PC > Documents > ezQuake on Windows)`

**Comment by meag** [comment]
Closing, fixed in [3.2.1](https://github.com/ezQuake/ezquake-source/releases/tag/3.2.1), [3.5-alpha24](https://github.com/meag/ezquake-source/releases/tag/3.5-alpha24), [3.6](https://github.com/ezQuake/ezquake-source/releases/tag/latest)
