### ISSUE TITLE
BUG: `gl_multisamples` has no effect when `vid_framebuffer` is enabled

### ISSUE THREAD

**Issue by Calinou** [ezQuake/ezquake-source#367]
**OS:** Fedora 31
**Graphics card:** NVIDIA GeForce GTX 1080 (driver version 440.82)
**ezQuake version:** https://github.com/ezQuake/ezquake-source/commit/82c44c7060856c66dc27c00c971591278eb3d200

MSAA won't be applied to the framebuffer when it is enabled. Forcing MSAA via the graphics driver also has no effect (this is expected, it can't work in that situation).

I guess this is because the multisample option isn't being passed to the framebuffer. It's probably not too difficult to fix, but I don't know how to do it right away.

I noticed this while working on #366.

**Comment by hemostx** [comment]
I see this too on windows. My workaround is:
vid_framebuffer_scale 0
vid_framebuffer_width 3840
vid_framebuffer_height 2160
(for a target res of 1920*1080). the GTX 1070 can take it.
This gives a touch of SSAA - cleaner than MSAA in many cases, but mostly limited to 4x the res to look any good. I'd love to get a hint of MSAA on top of that to render demo clips.

**Comment by Calinou** [comment]
@hemostx I can confirm this works, but isn't Quake one of the games best served by MSAA? There are very few alpha-tested surfaces to speak of. The only ones I can think about are simple item edges, but you'd be hard pressed to see aliasing on them during gameplay.

**Comment by meag** [comment]
(have fix for this but will wait and see if can get a stable 3.6 and maybe include it in next version)
