### ISSUE TITLE
vid_framebuffer_scale 0 : screenshot at framebuffer dimensions, actual image at different scale

### ISSUE THREAD

**Issue by hemostx** [ezQuake/ezquake-source#370]
Windows 10 1909
ezQuake Build 3.5a24 (c050fa0)/3.6a (82c44c7) indifferent
NV GTX 1070, Game ready driver 442.74 WHQL
```
vid_framebuffer 1 or 2 indifferent
vid_framebuffer_width 3840
vid_framebuffer_height 2160
vid_framebuffer_scale 0
vid_usedesktopres 1 (1920x1080) or 0 + adequate vid_width/height indifferent
```
Using a downscaled framebuffer (ie vid_framebuffer_width/height 3840x2016 -> 1920x1080), screenshots include the downscaled image in the bottom left corner of a screenshot which is vid_framebuffer_width/height sized ; the rest of the picture being black.
![ezquake001](https://user-images.githubusercontent.com/64284375/82584830-56fbdb00-9b95-11ea-8a43-c05f8f8289b4.jpg)
In such cases, we can just crop to have a "correct" screenshot.

Using an upscaled framebuffer (ie vid_framebuffer_width/height 320x240 -> 1920x1080), you get the inverse effect. 
![ezquake007](https://user-images.githubusercontent.com/64284375/82585073-b528be00-9b95-11ea-9b95-7af191f681cc.jpg)

The cropping appears to be from the bottom left corner (the cell pack was in my bottom left corner when I grabbed the screenshot). Also in this situation, we are getting some upscaling in the screenshot.

**Comment by Calinou** [comment]
I can reproduce this on commit https://github.com/ezQuake/ezquake-source/commit/82c44c7060856c66dc27c00c971591278eb3d200 (Fedora 31, NVIDIA GeForce GTX 1080).
