### ISSUE TITLE
BUG: FPS drop in 3.6 OSX

### ISSUE THREAD

**Issue by maniacQW** [ezQuake/ezquake-source#377]
Please search for existing issues and check for potential duplicates before filing yours.

**ezQuake version:**
3.6 alpha r666

**OS/device including version:**
OSX catalina latest, mbp 2020 (intel i9, radeon pro 5500)

**Describe the bug**
FPS drop whenever I take a look onto a player

**Expected behavior**
stable FPS

**Screenshots**
attached cfg.

[meag-fpsdrop.cfg.zip](https://github.com/ezQuake/ezquake-source/files/5068094/meag-fpsdrop.cfg.zip)

**Comment by meag** [comment]
Can't see anything obvious in your config, and testing locally (not on osx) doesn't show up any problems with viewing player model.  You've got polyblend & even r_dynamic switched off.

Does `/gl_simpleitems 0` also trigger this (I'd expect this to cause lower fps, but not lower-compared-to-3.2)
Can you try `/gl_program_aliasmodels 0` and see if that affects it?

Might be useful to record a demo of you standing still on a map, then a player joining and see what the difference in FPS is, so we're measuring the same situation each time.  (give me a shout if you want me to spec and then /join to get this)

**Comment by maniacQW** [comment]
Yes, gl_simpleitems triggers it also and it seems /gl_program_aliasmodels 0 did the trick. After /vid_restart no FPS drops observed with simplitem 0. I'll check with player and update here.

**Comment by meag** [comment]
After a bit of testing on the server: need to optimise `/gl_program_aliasmodels` for classic .glsl rendering path
Will try switching programs to get rid of ugly if statement in fragment shader - hopefully that helps a bit, will test this weekend

**Comment by meag** [comment]
Closing - have done this, but don't think performance is much better.  Leaving decent OSX performance until Vulkan
