### ISSUE TITLE
Bug: IDK if this counts as bugs or errors. But, i came across these errors.

### ISSUE THREAD

**Issue by DOOMMARINE117** [ezQuake/ezquake-source#379]
Please search for existing issues and check for potential duplicates before filing yours.

**ezQuake version:**
(Specify the Git commit hash if using a non-stable build - this is available through the `/version` command)

**OS/device including version:**
Specify GPU model, drivers, and the renderer (classic or modern) if graphics-related.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Also please attach your config (.cfg) file

**Additional context**

Hi, here are my issues: I used google drive by teh way to get the links. 

https://drive.google.com/file/d/12Kj-bldz-JejfmWGsY1_lQQrlbB86NIL/view?usp=sharing

https://drive.google.com/file/d/12Mc2OF2hQH7enAh_lFlFBtmGyt74t2qj/view?usp=sharing

https://drive.google.com/file/d/12EPsmC0sV-zU9df6kBpmVy8MJbrYmDHE/view?usp=sharing

Now this one is not an error btu to see if i got all the files in the right folder. 

https://drive.google.com/file/d/12Dv5eZyvmjp9LQwdpVIAhnYH-yG2ETig/view?usp=sharing

**Comment by meag** [comment]
Is it possible you have an old OPENGL32.dll in your Quake directory that is for Glide/Voodoo2 cards?

Can you try renaming that dll if so and trying again?

Thanks,

**Comment by DOOMMARINE117** [comment]
where cna i get the new file of Opengl32.dll?

**Comment by meag** [comment]
Your graphics card drivers usually install one, if there is an old copy in the Quake directory then it will be used instead.  You shouldn't need to put an OPENGL32.DLL in your Quake directory anymore.

**Comment by DOOMMARINE117** [comment]
well taht works, lol. i  did not realzie those wer ethe issues, lol. 

How do i load the mission packs of quake?

**Comment by meag** [comment]
ezQuake is designed for multiplayer, and doesn't support mission packs etc.
You might want to have a look at FTEQW or quakespasm clients if you want a better single player experience.
