### ISSUE TITLE
BUG: 5f804ef7/GLSL : on startup with vid_renderer 2, screen is completely black

### ISSUE THREAD

**Issue by hemostx** [ezQuake/ezquake-source#382]
**ezQuake version:**
5f804ef7 and -glsl binary/vid_renderer 1 only, not present two commits back at acdb27f1

**OS/device including version:**
W10 release 2004, GTX 1070, drivers 451.67.

**Describe the bug**
When starting ezquake in GLSL with vid_framebuffer 2, the entire screen is black (or any value of gl_clearColor). It is still possible to operate the game blind and i.e to pull out the console and vid_restart for a quick fix. vid_framebuffer 0/1 behaves properly.
If no vid_restart is performed, loading a map will behave opposite to issue #381 : the 3d world is rendered, but no 2d is present, this state persists across map loads until a vid_restart.

**To Reproduce**
1. set vid_framebuffer 2 in config (vid_renderer 1 if necessary)
2. start ezquake-glsl
3. darkness!

**Bonus steps**
4. Start a map
5. witness the game without 2d

**Expected behavior**
2d *and* 3d should show up :)

**Additional context**
[config.txt](https://github.com/ezQuake/ezquake-source/files/5090631/config.txt)

**Comment by meag** [comment]
Hi - can you confirm this is fixed now?

**Comment by hemostx** [comment]
Looking good now. Thanks!
