### ISSUE TITLE
BUG: "Some time on map change, fps is very low (150~200) GLSL, nouveau. Current fix: vid_restart"

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#383]
**ezQuake version:**
3.5 or 3.6, not specified. -glsl version

**OS/device including version:**
Linux (raket)

**Describe the bug**
Some time on map change, fps is very low (150~200) GLSL, nouveau. Current fix: vid_restart

**To Reproduce**
Unknown

**Expected behavior**
Consistent FPS

**Comment by Calinou** [comment]
What's their usual FPS?

**Comment by rakasunka** [comment]
Solved by adding this to xorg.conf: 
    Option "GLXVBlank" "off"
    Option "PageFlip" "off"
    Option "DRI" "3"

(Most likely DRI "3" is fixing things...)

@Calinou: I patched the kernel to support re-clocking on the 980ti with nouveau.

**Comment by meag** [comment]
Closing, solution provided by raket
