### ISSUE TITLE
REQ: <description>

### ISSUE THREAD

**Issue by frehall** [ezQuake/ezquake-source#385]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [there is a hassle with /teamoverlay voting before off-games can get started.]

**Describe the solution you'd like**
New ruleset (GetQuad, or raket maybe). Smackdown ruleset with hud_teaminfo_show 1 disallowed.

**Comment by meag** [comment]
This needs to be disabled server-side, as it's extra data/traffic that's sent by the server - by default in qw protocol there is no sending of health/armor/weapons of other players

**Comment by frehall** [comment]
Oops, thought rulesets was a client thing. By enabling a ruleset you disallow specific commands such as hud_teaminfo_show 1 in this case? And by that you won't be able to use teamoverlay no matter if it's enabled on server.Skickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: meag <notifications@github.com> Datum: 2020-08-31  07:36  (GMT+01:00) Till: ezQuake/ezquake-source <ezquake-source@noreply.github.com> Kopia: frehall <frehall@gmail.com>, Author <author@noreply.github.com> Ämne: Re: [ezQuake/ezquake-source] REQ: <description> (#385) 
This needs to be disabled server-side, as it's extra data/traffic that's sent by the server - by default in qw protocol there is no sending of health/armor/weapons of other players
