### ISSUE TITLE
REQ: Restore old FOV limits

### ISSUE THREAD

**Issue by HangTimeQW** [ezQuake/ezquake-source#389]
**Is your feature request related to a problem? Please describe.**
FOV limit is too low.  In older clients up to 170 was supported but now the cap seems much lower perhaps under 140.  I would like to try higher fov in ezquake. 

**Describe the solution you'd like**
Restore old 170 limit or at least something higher than currently eg 150.

**Describe alternatives you've considered**
Using outdated client

**Additional context**
Easy to reproduce, just test fov 140 then compare with fov 170, it looks the same. 

**Impact on server or mods**
None

**Comment by Calinou** [comment]
I tried to set up ezQuake to play on a 3-monitor surround setup, but any aspect ratio wider than 21:9 is currently unusable due to the FOV limit (since the FOV isn't truly Hor+).

**Comment by meag** [comment]
4:3 ratio, stretched (too fat)
![ezquake089](https://user-images.githubusercontent.com/10936291/99186903-5d859c80-274b-11eb-9c49-2379845a594c.jpg)

dynamic ratio, horizontal fov capped at 140 (current behaviour):
![ezquake088](https://user-images.githubusercontent.com/10936291/99187277-9a529300-274d-11eb-95fc-eaa60a257217.jpg)

dynamic ratio, horizontal fov not capped:
![ezquake087](https://user-images.githubusercontent.com/10936291/99186902-5ced0600-274b-11eb-812b-5b25af1c6011.jpg)

(excuse the cells being missing, i took the last screenshot first)

so capping the horizontal fov at 140 is where this is going wrong, you can see the uncapped version has the same vertical fov as 4:3, which I think is what we're aiming for?

**Comment by Calinou** [comment]
@meag Yes :slightly_smiling_face:

**Comment by HangTimeQW** [comment]
Yes - 3rd screenshot isn't capped at low fov (I'm currently using fov 128
which is pretty much at the limit of horizontal fov - any higher than 129
looks identical)

**Comment by meag** [comment]
![ezquake090](https://user-images.githubusercontent.com/10936291/99193477-16120700-2771-11eb-9207-f76e8a958e0b.jpg)

I'm leaving fov limit at 140 but that's really controlling the vertical fov, upping fovx limit from 140 to 165 (this is calculated based on your screen ratio) - can't let it go any higher than that without changing visibility calculations (can see hall of mirrors on left hand side), also the particle size calculations (they are drawn larger based on how far away they are) starts making the particles look a bit weird.  

I was only hitting that limit in dual-screen and fov 135+ though.  we should maybe look at some other projection models (or panquake) for high fov or multiple monitors
