### ISSUE TITLE
ezquake 3.2.2 got black screen Manjaro 20.01

### ISSUE THREAD

**Issue by timofeika** [ezQuake/ezquake-source#391]
After compiling ezquake 3.2.2 from sources, i got black screen, i can see main menu for like half of second, and after black screen. I can hear sound when i move in menu thru arrow keys. Nothing criminal in console https://i.imgur.com/XOObXRw.png

P.S. 3.2.1 work without any issues.

UPD. If i call console and type for example "map dm6" its finally shows me the game.

**Comment by meag** [comment]
Hi there

Are you definitely on the ezquake_32 branch when compiling?
There should be no commits between 3.2.1 and 3.2.2 that affect rendering (other than thunderdome outlines)
Can you try rewinding to previous 3.2.1 commit, checking that it runs okay and then cherry-picking each commit to see which one causes the problem?

Thanks,

**Comment by timofeika** [comment]
hey, I deleted my /var by an accident, and now I am on windows, so I can't reproduce it, sorry.

**Comment by meag** [comment]
Closing
