### ISSUE TITLE
BUG: LGC3 bot crashes server with current client version 3.2.2 (cl_parseservermessage issue)

### ISSUE THREAD

**Issue by lunchbasket** [ezQuake/ezquake-source#393]
After loading the LGC3 bot mode/config and starting the map, _as soon as I enter the "addbot" command, the server crashes with the following in console_:

Host_Error
Server crashed: cl_parseservermessage: bad server message

Reverting to client version 3.0 fixes this issue.

Here is the lgc3 bot for bugtesting:
https://web.archive.org/web/20111025045627/http://lgc.quakeworld.nu/?action=about
https://web.archive.org/web/20111025045627if_/http://lgc.quakeworld.nu/lgc3.zip

**Comment by meag** [comment]
Hi

Workaround is to use `/cl_pext_floatcoords 0` before starting the map.  Unfortunately the mod is writing coordinates directly into the network packet here, so I don't know if there is an easy fix.  Will leave open for the moment.
