### ISSUE TITLE
BUG: COOP Backpack and Level Transition Items Broken

### ISSUE THREAD

**Issue by hypercube33** [ezQuake/ezquake-source#397]
Please search for existing issues and check for potential duplicates before filing yours.

**ezQuake version:**
(Specify the Git commit hash if using a non-stable build - this is available through the `/version` command)
3.2.2

**OS/device including version:**
Specify GPU model, drivers, and the renderer (classic or modern) if graphics-related.
Windows 10 1909 / Radeon RX 580X / Not a render isssue

**Describe the bug**
Coop game mode. When you die you do not drop what you have in inventory, instead it appears to drop what you started the level with.
When you transition to the next level, you do not take your inventory with. 

**To Reproduce**
1. start the game.
2. We did nightmare E1 / E2 levels and gave up because playing like this sucks
3. have a friend join and have them die and go pick their stuff up and note that they get nothing of what they picked up weapon or ammo wise.

**Expected behavior**
Unless beating a boss at the end of an episode, you should get 100% of what you had on your person dropped as a backpack or taken with to the next level.

**Screenshots**
Also please attach your config (.cfg) file

**Additional context**

**Comment by meag** [comment]
`1. start the game` - can you confirm what mod you are playing?  Is it the generic qwprogs.dat that comes with nquake, ktx, or something else?  I'm not sure this is really a client thing as the internal server is mvdsv, but can look into it.

Thanks,

**Comment by meag** [comment]
Hi

Have just tried this on local server and cannot reproduce.  I think maybe you were accidentally using a mod that didn't support coop?

Will close for now, please re-open if you think this is in error.
