### ISSUE TITLE
BUG: Difference in font smoothing between 3.2 and 3.6

### ISSUE THREAD

**Issue by eb** [ezQuake/ezquake-source#401]
**ezQuake version:**
Comparing between prebuilt releases 3.2.2 and 3.6-dev-alpha2.

**OS/device including version:**
Windows 10 2004, MSI GeForce GTX 1060 6GB with latest NVIDIA drivers, modern renderer,

**Describe the bug**
Check attached screenshots to see that the non-smoothed fonts are identical between 3.2 and 3.6 and the smoothed fonts are different. I've included a diff of the screenshots as well.

**To Reproduce**
1. Open ezQuake 3.2.2 and type /gl_smoothfont 1
2. Do a /screenshot
3. Open ezQuake 3.6 and type /r_smoothtext 1
4. Do a /screenshot
5. Compare the screenshots in your favorite graphics program to see that the smoothing is somewhat different in 3.6. Which makes for an overall less sharp font.

**Expected behavior**
Same font smoothing to maintain the crispness of the font.

[nosmooth.zip](https://github.com/ezQuake/ezquake-source/files/5346566/nosmooth.zip)
[smooth.zip](https://github.com/ezQuake/ezquake-source/files/5346567/smooth.zip)
[config.zip](https://github.com/ezQuake/ezquake-source/files/5346571/config.zip)

**Comment by meag** [comment]
This is the result of older versions of ezQuake not using pre-multiplied alpha and causing errors.  `povo5` font has harsh edges from opaque white RGBA(1,1,1,1) to transparent black (0,0,0,0).  Blending between the two gets (0.5,0.5,0.5,0.5), and then ezQuake < 3.5 multiplies the RGB values by the alpha component again, and you get (0.25,0.25,0.25,0.5).  This leads to much softer edges.

I'll add an option to apply the same alpha logic in the shader for people who are more used to their hud having that effect - I don't think there's anything we can do to the asset to stop it happening.

**Comment by meag** [comment]
`/r_smoothalphahack 1`
