### ISSUE TITLE
BUG: tp_pointpriorities and tp_point do not properly work

### ISSUE THREAD

**Issue by paddern** [ezQuake/ezquake-source#406]
**ezQuake version:**
3.6 alpha3 r6786~88f3154c

**OS/device including version:**
n/a

**Describe the bug**
this might actually be two bugs (?)

1) tp_point (like its cousins tp_pickup and tp_took) does not show the order of the arguments given but sorts it. the given order would be useful to understand tp_pointpriorities however.

2) tp_pointpriorities doesn't seem to always work reliably.

**To Reproduce**
1.1) set tp_point to "mh ra" or "ra mh"
1.2) check with tp_point w/o args
1.3) set tp_pointpriorities to 1
1.4) point to dm2 mega/ra
1.5) toggling between "mh ra" and "ra mh" works as intended while pointing but tp_point always reports "ra mh"

2.1) do the same with sng and quad on dm4
2.2) sng seems to be disregarded

**Expected behavior**
1) tp_point's output shouldn't be sorted

2) given order should be respected for all items

**Comment by meag** [comment]
Hi

Take your point about `tp_point` output being confusing when `tp_pointpriorities 1` is set... when sng is disregarded, was deathmatch 1 set?  Only way I could reproduce the sng/quad problem was setting `deathmatch 3`, which ignores weapons.

Thanks,

**Comment by paddern** [comment]
Shoot, you're right, `deathmatch 3` was set. Sorry for the inconvenience! :)
