### ISSUE TITLE
BUG: sys_disablewinkeys doesn't always disable the windows key; (also, a windows resolution issue when alt-tabbing)

### ISSUE THREAD

**Issue by snedpics** [ezQuake/ezquake-source#41]
sys_disablewinkeys 1 allows me to bind things to the windows key. I have +ssg bound there now, and it usually works fine. In fact, it always works fine right after I start up the client. But for some undiscovered reason the functionality breaks after extended game sessions, causing one to be inadvertently task-switched to the Windows desktop, potentially in the middle of a match. 

My best guess is that the functionality breaks due to something related to alt-tabbing to windows intermittently during the client session. Something related to that process must be "reactivating" the windows keys for some reason, as I don't think it happens until I've alt-tabbed during a session (though it's not very predictable when it will occur - I just alt-tabbed a few times and couldn't reproduce the bug). 

Another (probably unrelated) task switching issue: 

Sometimes, upon alt-tabbing, the Windows desktop will take on the same resolution as the QW client. I play in 800_600, with desktop at 1600 \* 1200. Usually this works fine with alt-tabbing. However, sometimes, for some unknown reason, I alt-tab to find my desktop also at 800_600. 

As far as when this error occurs, it's an all or nothing thing. If alt-tabbing is working fine when I start up the client, the error will not happen later in that session. However, if the error occurs it will begin with the very first alt-tab during a session, and for every alt-tab thereafter. The only workaround is to manually switch back the desktop resolution every time you alt-tab, or reboot Windows. 

OS: Windows 7
Ezquake client: 3.0 Alpha R4606`A91749E Win32:GL  (most recent one posted in qw.nu forums).

**Comment by jite** [comment]
Are you still experiencing this?

**Comment by snedpics** [comment]
I don't have access to my QW computer right now, but when I last checked a few months ago it was still an issue.

**Comment by meag** [comment]
@snedpics - I've been trying to reproduce this but am struggling.  During these extended sessions, would anything else be running in the background that might also try to trap/detect windows keys being pressed?  Another game perhaps?

What we could do is add a flag so that when this did happen, you could enable debugging and send us the results?  Either ezQuake is not receiving the hook messages (this is my suspicion) or it is but not blocking it for some reason.

Sorry this isn't very helpful, just I'm unable to replicate it in order to fix it :(

**Comment by snedpics** [comment]
It might be a few weeks until I have access to my setup again, but I'd be happy to help when I am able. I have no knowledge of programming, however, so you'd need to walk me through the process of enabling debugging and reporting the results.

I certainly suspected another program or background process might have been causing the issue, but I had no luck identifying which one (or even if that was really the case). I tried common sense fixes like closing all programs, but nothing short of restarting the client helped. Actually, restarting the client *always* fixed it (at least for a while), IIRC.

As far as the second issue goes (unwanted desktop resolution changes upon alt-tabbing), I no longer have the CRT, so it's doubtful I'd be able to help with that.
