### ISSUE TITLE
BUG: Random shotgun fire

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#410]
Please search for existing issues and check for potential duplicates before filing yours.

**ezQuake version:**
Believe this is 3.6 only, since server-side weapon scripting

**OS/device including version:**
Presume all

**Describe the bug**
Reported on discord, various users.  Waiting on configs.

**To Reproduce**
Unknown

**Expected behavior**
As per previous versions, when server-side weapon scripting not enabled by server.  Not clear whether server-side weapon scripting needs to be enabled (but not supported?).  Waiting on examples.

**Comment by eb** [comment]
Here's wimpeeh's config... he has this issue a lot
[wimconfig.zip](https://github.com/ezQuake/ezquake-source/files/5705443/wimconfig.zip)

**Comment by eb** [comment]
And a demo... demo_jump 5:35
[duel_wimsuit_vs_eb[dm4]201216-2027.zip](https://github.com/ezQuake/ezquake-source/files/5705471/duel_wimsuit_vs_eb.dm4.201216-2027.zip)

**Comment by meag** [comment]
```
ciscon: yeah, i only had it happen once while testing out pure +fire stuff without any of my aliases, but it was repeatable until i reconnected
ciscon: literally any weapon i attempted firing it would immediate switch to sg (which wasn't even my autohide weapon) after the first fire, while holding down +fire
ciscon: haven't been able to reproduce it since, but then again i also switched back to my normal weapon scripts so who knows
ciscon: i was trying out the simplest stuff- after reconnecting it totally worked, something must have just gotten fouled up with the initial cmd stuff or something
ciscon: it would start firing sg
```

**Comment by meag** [comment]
(+1 for saving his config while fakenicking as Leopold btw)

**Comment by eb** [comment]
Dunno if there's any news for a test server to debug that issue, meag. I was off for some days.
In any case, wimpeeh reported that the issue is gone when using cl_weaponhide 2. So, he is leaving his weapon scripts as they are, but enables weaponhide and then has no SG bug anymore.
Dunno if that's of any help for tracking it down.

**Comment by meag** [comment]
Thanks @eb - there has been progress but then I moved all the logging to server-side and had the client upload extra info.  Which I had an extension for in the past, to measure antilag (and also answer your "can you show the opponents where the server is 'seeing' them" question).  And ... well, in the end no it hasn't left my PC yet and isn't quite finished.

Poor Christmas discipline, just like my diet...

**Comment by meag** [comment]
Have been debugging with BLooD_DoG on london.badplace.eu, which is recording weaponscript info in the .mvd file

To test, use latest builds and try `/cl_debug_weapon_send 1` before connecting (if you have this enabled and the server doesn't support it, you should get a warning during connection).  When viewing the demo back, try `/cl_debug_weapon_view 1` and you should see some very basic messages in the console explaining any weaponscript decisions.

**Comment by meag** [comment]
@eb do you remember what wim thought he did to 'fix' this, or make it happen less often... `/cl_weaponhide x`?

**Comment by meag** [comment]
Sorry, "In any case, wimpeeh reported that the issue is gone when using cl_weaponhide 2." < you put it right there in the comments...

**Comment by meag** [comment]
@eb has there been any more feedback on this?

**Comment by meag** [comment]
Removing 'blocks-release' tag as no-one else has reported this, waiting for ability to reproduce

**Comment by meag** [comment]
Closing - ssws removed.
If it's still happening will need to look at again, was reported on servers without ssws so am presuming at this stage that server side of this wasn't the cause
