### ISSUE TITLE
BUG: powerup glow not synced with player model (3.6 classic)

### ISSUE THREAD

**Issue by liback** [ezQuake/ezquake-source#421]
**ezQuake version:**
3.6-DEV-ALPHA3 R6843~93C6105F

**OS/device including version:**
Geforce GTX 1070 Ti
Driver v.452.06
Classic renderer

**Describe the bug**
Powerup glow around players are no longer synced with the model.

**To Reproduce**
Loaded up a demo with someone having quad and observed in free view, powerup glow now not appearing synced with player model when player moving.

Originally reported by Mulzie in Discord however I (Åke Vader) get the same problem.

(Note: it looks OK in 3.2.2 classic renderer and 3.6 new renderer)

Config used:
[config.zip](https://github.com/ezQuake/ezquake-source/files/5508488/config.zip)

**Expected behavior**

**Screenshots**
![ezquake006](https://user-images.githubusercontent.com/15114487/98507304-f9a03700-2265-11eb-8580-7fd484d949b7.png)

**Additional context**

**Comment by meag** [comment]
Hi Ake - that config has `r_dynamic 0`?

**Comment by meag** [comment]
By 'glow', do you mean the powerup shell?

**Comment by liback** [comment]
Yes the shell, sorry for the confusion :)
