### ISSUE TITLE
BUG: duplicate vid_framebuffer_palette LegacyCommand entries after vid_restarts

### ISSUE THREAD

**Issue by hemostx** [ezQuake/ezquake-source#422]
**ezQuake version:**
3.6 since the move from vid_framebuffer_palette to vid_software_palette

**Describe the bug**
Since GLSL palette correction was made available generally and moved to vid_software_palette, I noticed the legacy cvar mapping vid_framebuffer_palette to vid_software_palette gets added over and over when accumulating vid_restarts (vid_restart -> VID_RegisterLatchCvars() -> Cmd_AddLegacyCommand()).

**To Reproduce**
1. tab complete vid_framebuffer - one entry
2. vid_restart
3. tab complete vid_framebuffer - +1 entry
4. GOTO 2 for more entries

**Additional Context**
I reviewed other Cmd_AddLegacyCommand() calls, my first suspicion was that maybe some sound cvars would get duplicates on s_restart - thankfully, this is not the case.

**Suggested Fix**
If you feel like the LegacyCommand is really needed for such a recent/unexplored var, then this appears to be the cleanest fix:
```
diff --git a/vid_sdl2.c b/vid_sdl2.c
index 4d59b708..d7505199 100644
--- a/vid_sdl2.c
+++ b/vid_sdl2.c
@@ -886,7 +886,6 @@ static void VID_RegisterLatchCvars(void)
 	Cvar_Register(&vid_gl_core_profile);
 	Cvar_Register(&vid_framebuffer);
 	Cvar_Register(&vid_software_palette);
-	Cmd_AddLegacyCommand("vid_framebuffer_palette", vid_software_palette.name);
 	Cvar_Register(&vid_framebuffer_depthformat);
 	Cvar_Register(&vid_framebuffer_hdr);
 	Cvar_Register(&vid_framebuffer_smooth);
@@ -1664,6 +1663,7 @@ void VID_RegisterCommands(void)
 		Cmd_AddCommand("vid_restart", VID_Restart_f);
 		Cmd_AddCommand("vid_displaylist", VID_DisplayList_f);
 		Cmd_AddCommand("vid_modelist", VID_ModeList_f);
+		Cmd_AddLegacyCommand("vid_framebuffer_palette", vid_software_palette.name);
 	}
 }
```
This shouldn't be a problem, as VID_RegisterCommands() gets called after VID_RegisterLatchCvars() during VID_Init() if !host_initialized. It's certainly more efficient than checking with Cmd_IsLegacyCommand() in VID_RegisterLatchCvars()  - let alone on every Cmd_AddLegacyCommand() call, which was my initial reaction...

**Comment by meag** [comment]
Thanks - will fix as you advise.  Ideally they'd all be an enum though, I don't think there's any dynamically created legacy cvars/commands.
