### ISSUE TITLE
BUG: HUD - Radar texture does not clamp

### ISSUE THREAD

**Issue by hemostx** [ezQuake/ezquake-source#424]
**ezQuake version:**
From 3.2 to current (regardless of renderer)

**Describe the bug**
The radar_pic does not clamp => edges bleed to the side, as seen most obviously on aerowalk :

![radarclampz](https://user-images.githubusercontent.com/64284375/98848085-77746600-2451-11eb-9d84-a2ce66b3d4f0.png)
Left to right : unclamped, clamped with https://github.com/hemostx/ezquake-source/commit/16d434f5f62879bdac7150200a5b7134362f157f , reference radar_pic to scale

In this particular case the right edge is wrapping to the right and the bottom edge is wrapping to the top.
Depending on scaling/position of  the radar_pic, bleeding can be observed on various edges. Radar images have been right to the edge without blank borders thus far.
Other 2D elements appear to clamp properly.

**To Reproduce**
1. play an aerowalk demo/spectate on qtv - this has the most convenient radar image
2. play with width/height and pos_x/y to get edges to bleed

**Expected behavior**
The radar image should not wrap, as seems to be the case for virtually everything else 2D in the hud.

**Additional context**
After making borders blatantly obvious on hud numbers and also swapping the radar image with the hud numbers to cross-test the assumptions, I figured those other hud elements actually _do_ clamp properly.
Under the hood, they ended up using the same draw functions as the radar_pic yet looked correct without explicitly setting TextureWrapModeClamp - I couldn't find/trace further references.

I ended up attempting a fix in https://github.com/hemostx/ezquake-source/commit/16d434f5f62879bdac7150200a5b7134362f157f which doesn't seem to yield visible side effects.

**Comment by meag** [comment]
Hi hemo

The others won't be wrapping because they're moved to the hud atlas - I haven't done this for background hud images or radar pictures as they can be very large, and typically only used once a scene.  The only real difference between the commits is that I set the texturemode to clamped once when the image is loaded, rather than before rendering.

Thanks,
meag
