### ISSUE TITLE
BUG: HUD/Radar : square of pixel noise flashing on the radar on boomstick shots

### ISSUE THREAD

**Issue by hemostx** [ezQuake/ezquake-source#425]
**ezQuake version:**
Since at least the official 3.0 build

**OS/device including version:**
Considering the history, shouldn't depend on drivers/OS service packs - has happened through a year of GTX 1070 gameready driver updates and Windows 10 builds

**Describe the bug**
As I started spectating QW again in 2019 I noticed a square of moving white noise showing up on the radar, in a static spot specific to every map, and with what seemed like a random timing.
![radar_noise](https://user-images.githubusercontent.com/64284375/98851795-0fc11980-2457-11eb-8ecb-235d4c93a651.png)
There it is by the air vent/jump pad.
Having poked with the radar lately, I figured the following:
* It's centered on `map_x_intercept` / `map_y_intercept` which are used to reference the 0 point of the map on the radar_pic, in order to convert entity coordinates into pixel coordinates.
* It flashes up (at least) when people fire up the boomstick, even when not tracking the shooting player.
* The duration is not tied to the length of the sound, as it scales with demo_setspeed. Pause the demo, it'll keep on garbling until you unpause.
* The pattern does not pause - it appears to change for every render frame.
* Happens since at least 3.0, and even with a default config in a lightweight debug folder.

Due to this, it's easier to troubleshoot on aerowalk MVDs, as the 0 point is conveniently placed there. Conversely, this explains why that noise appears way out of bounds on DM2 - its zero point is well to the left outside the map ; therefore you have to nudge the radar quite a bit to the right for this to appear on DM2, where a maplock situation might yield more boomsticking and thus more instances of the bug showing up :)

Current unknowns :
* Whether it's only an MVD thing or also shows up on QTV
* Whether it depends on what's within hearing range of the tracked player at this point, multiple runs on the same demo but from different povs may give different results. However sticking to the same pov and demo_jumping to the same good spot yields reliable results.
* Since it may depend on PVS, multiple runs over the same demo might yield different results

**To Reproduce**
1. Play an MVD
2. show radar
3. demo_jump to some point where people shoot the boomstick.
4. play with demo_setspeed

**Expected behavior**
This probably should not be there. If it shows some debug info, it should probably be toggled.

**Comment by meag** [comment]
Hi hemo

This was an interesting one - the gunshots are appearing because of the setting on the hud, but the positions for temporary entities for gunshots was always at the origin for anything but simple (position only) entities.

Nice detective work ;) 

Thanks,
meag
