### ISSUE TITLE
BUG: HUD r/hud_tracker text sticks out of the right boundary

### ISSUE THREAD

**Issue by hemostx** [ezQuake/ezquake-source#427]
**ezQuake version:**
3.6 since ea69ece616d3113d16ae95111f58791c7144d6a2

**OS/device including version:**
Win 10, renderer irrelevant

**Describe the bug**
The frag messages in r_tracker / hud_tracker, when the text is aligned right, now poke outside of the bounding box, which visibly truncates the victim's name when the elements are positioned default/flush with the right border of the screen (respectively).
It used to have a one character inner gap ; the text now actually goes beyond the right edge on top of the inner alignment fix.

Nigve also noticed this, but he reported truncation by two characters, which I guess is due to him moving his tracker out right to compensate for the inner gap that used to be there.

**To Reproduce**
For r_tracker, the default settings are enough.
For hud_tracker, you want 
hud_tracker_align_x right
hud_tracker_align_right 1
Moving the hud element around with hud_editor shows the text poking out of the actual limit.

**Expected behavior**
Tracker text should stay within bounds of the side being aligned to.

**Screenshots**
Showing r_tracker on top, and hud_tracker at 2x scale underneath. The right edge is from the screenshots, not cropped in that direction.
Currently:
![tracker_broken](https://user-images.githubusercontent.com/64284375/99128828-31afcd00-260c-11eb-8ad6-09a0e7bac9ed.png)
Before ea69ece616d3113d16ae95111f58791c7144d6a2:
![tracker_before](https://user-images.githubusercontent.com/64284375/99128834-35dbea80-260c-11eb-8a62-d57ffccd3bd6.png)
If I'd moved the hud element to the left, you'd see the extra chars sticking out.
The same "before" r_tracker alignment can be observed looking back to 3.2, modulo hud_tracker not being available then.

The right alignment with proportional fonts is broken, and this shifts it even further out (Same settings with proportional 1, fontload arial):
![proportional](https://user-images.githubusercontent.com/64284375/99130097-b2bc9380-260f-11eb-8d8b-8ce21a46c47c.png)

Dotted line higlights the "one char back fix" between the two revisions. As expected, the misalignment scales with the font width  of different TTFs.

**Comment by meag** [comment]
Thanks hemo

I'll have to fix the right alignment with proportional fonts in another commit, as I can see it's sharing the display-line code with r_tracker but the cvar is interpreted differently.
