### ISSUE TITLE
BUG: String comparisons regarding locations fail sometimes

### ISSUE THREAD

**Issue by paddern** [ezQuake/ezquake-source#428]
**ezQuake version:**
Checked with 3.6-alpha3 (MinGW and VS) and 3.2.2

**Describe the bug**
String comparisons don't reliably work, when the location contains `$,` as character. This probably isn't limited to that one alone but I haven't looked into further chars yet.

**To Reproduce**
My use case in particular:
1. `bind MWHEELDOWN "if ('$tookatloc' != '$_last_taken') then tp_msgtook; set_ex _last_taken $qt%i$qt"`
2. trigger MWHEELDOWN several times after you took an item at a loc w/o any separator
3. reports just once - as expected
4. repeat step 2 at a loc with separator
5. reports several times, i.e. comparison yields true, although the macro and the cvar contains the same
6. `/set loc_name_separator "-"`
7. repeat step 4
8. it works again :)

**Expected behavior**
String comparisons should work with "funny" chars too.

**Additional context**
I tried with `isin` and `=~` operators too and they also failed.

**Comment by meag** [comment]
Hi

Can you supply the .loc file that you're having trouble with?  Have just tried with dm4, picking up GA at low-tele (`low$loc_name_separatortele`) and it didn't repeat.

what was loc_name_separator set to before step 6?

Thanks,
meag

**Comment by paddern** [comment]
I use the ones from locs.pk3 and tested on DM2 (several locations). With my setup I can make it fail on DM4 at low-tele too (with GA added to tp-took).

According to console output the cvar is set to `$,` (default and current value) before step 6. However, that was set from my config:
```
//User Created Variables
set loc_name_separator               "$,"
```

I deleted that and tried with the default (hypen?) and all works nicely. Then I `set loc_name_separator "$,"` on console and it _still_ works. Seems like a cfg_save is needed beforehand?

I've attached mine ...
[pattah.txt](https://github.com/ezQuake/ezquake-source/files/5542255/pattah.txt)

**Comment by meag** [comment]
Okay - I think you're getting into trouble because `set_ex` resolves 'fun' chars like `$,` before storing the string, whereas we'd really want those to be variables at the point of evaluating an if() statement.

Don't want to make it stop doing that as it might screw up other people's scripts, but will add set_ex2 which doesn't do this.  (feels like a bug but probably one people's scripts will now expect)

You can fix it in your script by turning off funchars before calling `set_ex`, and use:

```bind MWHEELDOWN "if ('$tookatloc' != '$_last_taken') then tp_msgtook; cl_parseFunChars 0; set_ex _last_taken $qt%i$qt; cl_parseFunChars 1"```

**Comment by paddern** [comment]
Ah, I see.  Thanks!

As far as I'm concerned, I don't need an extra function, the workaround seems just fine. :)
