### ISSUE TITLE
BUG: broken teamplay messages in v3.6

### ISSUE THREAD

**Issue by liback** [ezQuake/ezquake-source#430]
**ezQuake version:**
3.6 (works in 3.2.2)

**OS/device including version:**
N/A

**Describe the bug**
Some teamplay cfg things not working in 3.6. Works in 3.2.2.

~~1. locations on lost msg~~
2. report: no weapons and some error message displayed below

Reported by Trygve on Discord.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
https://media.discordapp.net/attachments/179895022366228481/777873001269690398/ezquake014.jpg?width=1204&height=677
https://media.discordapp.net/attachments/179895022366228481/777873004134662144/ezquake015.jpg?width=1204&height=677
https://media.discordapp.net/attachments/179895022366228481/777873006193803284/ezquake016.jpg?width=1204&height=677

**Additional context**
N/A

**Comment by meag** [comment]
Thanks - can you upload your config?  (nigve's config?)

**Comment by liback** [comment]
Forget about the Lost message error - he simply has no tp_name_someplace set and was in prewar.

The unparsed custom variables seem to start working if adding spaces around the second slash in this alias (works without them in 3.2 as mentioned):
`
alias .report                "say_team $\ $tvs_nick_color $tvs_loc $tvs_string_armor/$tvs_string_health $tvs_string_weapon $powerups"
`

Attaching config(s). I guess tvs_tp.cfg and tvs_alias.cfg in /qw is enough.
[trygve config.zip](https://github.com/ezQuake/ezquake-source/files/5548742/trygve.config.zip)

**Comment by liback** [comment]
My spaces observation wasn't valid - it's the first time it doesn't work sometimes for some reason, the aliases don't seem to be loading in the same way as in 3.2.2. Pressing the report button twice will have the variables populated in the second message. :)

To reproduce:
* tvs_tp.cfg and tvs_alias.cfg in /qw
* start ezquake
* exec tvs_tp.cfg
* map dm3
* press 1 (report) - variables in message don't work
* press 1 (report) - variables in message now work

**Comment by meag** [comment]
Thanks

Can confirm that the first `set_tp $tvs_string_armor ...` is executed after `say_team`, but the script is so involved I'll need to keep looking into it.
