### ISSUE TITLE
BUG: /scr_newhud 0 is crashing when r_damagestats is enabled

### ISSUE THREAD

**Issue by eb** [ezQuake/ezquake-source#432]
**ezQuake version:** 8c3eab3

**OS/device including version:** Windows 10

**Describe the bug**
I can't use /scr_newhud 0, because ezQuake is then crashing right away when entering a game.

**To Reproduce**
1. Type /scr_newhud 0 in console (also works with /scr_newhud 2)
2. Enter a game (e.g. /map dm4)
3. Crash

**Expected behavior**
I expect the old HUD to show.

[config.zip](https://github.com/ezQuake/ezquake-source/files/5549933/config.zip)

**Comment by meag** [comment]
r_damagestats 0

**Comment by meag** [comment]
Draw_AMFStatLoss needs to work with hud == NULL which is fine, but it uses the same static vars for 2 hud elements which also needs fixed

**Comment by eb** [comment]
Thanks!

**Comment by meag** [comment]
Fixed by https://github.com/ezQuake/ezquake-source/commit/ac67316c8813b26b783e3b9cedc7db9ed6284347
