### ISSUE TITLE
REQ: Line breaks in the console

### ISSUE THREAD

**Issue by mushis** [ezQuake/ezquake-source#434]
is it possible to prevent the line breaks in the console?
example in the screenshot attached
ez 3.6
![image](https://user-images.githubusercontent.com/3011167/99885596-f2960300-2c2d-11eb-8458-680a51e09653.png)

**Comment by Calinou** [comment]
Off-topic, but where did you get that console font? It looks more readable than any of the built-in nQuake fonts I've tried :slightly_smiling_face:

**Comment by mushis** [comment]
> Off-topic, but where did you get that console font? It looks more readable than any of the built-in nQuake fonts I've tried 🙂

its a ttf font. ezq 3.6 supports ttf fonts

**Comment by meag** [comment]
Hi mushi

This would have to wait until the next version - at the moment the lines are broken up as they are added to memory, not when rendering.

Thanks,
meag
