### ISSUE TITLE
BUG: master is fullbright with vid_renderer 0 on macOS

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#439]
**ezQuake version:**
3.6 ('master')

**OS/device including version:**
macOS

**Describe the bug**
dev: master is fullbright with vid_renderer 0 on macOS

**Comment by meag** [comment]
Hi dev - recent change to binding textures tonight, can you try latest and see if this has improved?  (sorry, no macOS here)

**Comment by meag** [comment]
Can someone on MacOS confirm/deny this with the latest 3.6?

**Comment by fzwoch** [comment]
Is that level light maps or player skins? If it is level light maps - they seem to be okay for me with 3.6-alpha7. Macbook Air M1 in native arm build.

**Comment by meag** [comment]
dev can you upload your config, textures used etc so we can try to reproduce?
