### ISSUE TITLE
BUG: gl_contrast > 1 rendering issue in classic renderer

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#442]
**ezQuake version:**
3.6

![image](https://user-images.githubusercontent.com/10936291/100451262-010d7000-30af-11eb-8816-1405c7402452.png)

vertical fov differences between renderers?

**Comment by meag** [comment]
![ezquake092](https://user-images.githubusercontent.com/10936291/100541508-52973580-323c-11eb-805e-be086c5922f7.jpg)
![ezquake093](https://user-images.githubusercontent.com/10936291/100541510-532fcc00-323c-11eb-882e-fbfbd2a75cc6.jpg)

Must be simpleitems...?

**Comment by meag** [comment]
![ezquake094](https://user-images.githubusercontent.com/10936291/100541592-e23ce400-323c-11eb-9f13-c4323afa5aa2.jpg)
![ezquake095](https://user-images.githubusercontent.com/10936291/100541593-e2d57a80-323c-11eb-9375-3f6473660944.jpg)

@hammer I can't replicate this, can you explain?  Will probably need copies of your config

**Comment by VVD** [comment]
> **ezQuake version:**
> 3.6
> 
> ![image](https://user-images.githubusercontent.com/10936291/100451262-010d7000-30af-11eb-8816-1405c7402452.png)
> 
> vertical fov differences between renderers?

Look like different v_viewheight.

**Comment by meag** [comment]
Thanks, I see it now... `gl_contrast` > 1 causes the triangles to appear criss-crossing the screen (passing through the crosshair but not the cause of it)
