### ISSUE TITLE
BUG: timedemo broken, view doesn't follow player and stays in initial position (?)

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#448]
**ezQuake version:**
3.6, build not specified

**OS/device including version:**
unknown, but complained of lower fps in glsl

**Describe the bug**
```
[01:46]dirtbox:I've had issues with 3.6 tbh
[01:47]dirtbox:i get less fps than 3.5 using GLSL
[01:47]dirtbox:also timedemos are broken
[01:47]dirtbox:so i'm staying put for now
[05:02]blindcant:what do you mean by timedemos being broken?
[05:18]dirtbox:the player pov doesn't follow the player
[05:18]dirtbox:stays on spawn
[05:18]dirtbox: its weird
```

**To Reproduce**
Unable to reproduce

**Comment by dirtboxqw** [comment]
OS: Windows 10 (latest)
Ez: 3.6 alpha4
GPU: RTX 3080 latest drivers (also happened on 1080 TI)

ezquake 3.5 timedemo: https://www.youtube.com/watch?v=bbtWouo4Rlw
ezquake 3.6 timedemo: https://www.youtube.com/watch?v=9MfFs_AC0CQ

The issue also happens on ezquake 3.6 linux with Radeon graphics

**Comment by meag** [comment]
Also on Windows 10, RTX 3080, 3.6-alpha4, same demo, supplied config loaded on startup, starting timedemo through shift-return from demos menu... cannot replicate :(

**Comment by dirtboxqw** [comment]
The section of this bug relating to 3.5 glsl getting higher fps than 3.6 can be safely ignored. I reinstalled windows for unrelated reasons which had the side effect of fps being roughly the same now.

**Comment by meag** [comment]
Can reproduce now, the camera tracking is alternating on/off at high speed, investigating...
