### ISSUE TITLE
BUG: crash on linux when using r_drawflat_mode 2 (maybe)

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#449]
**ezQuake version:**
Not specified, must be 3.6+

**OS/device including version:**
Some form of linux, not specified

**Describe the bug**
[20:51]NinJaA:
```
lolz@h4:~/Games/qw$ ./ezquake-linux-x86_64 
corrupted double-linked list
Received signal 6, exiting...
^CDOUBLE SIGNAL FAULT: Received signal 2, exiting...
```
[20:51]NinJaA:tried r_draw_flat_mode 2

**Comment by dirtboxqw** [comment]
I have tested this on Ubuntu with ezquake 3.6 running on Radeon iGPU and I could not replicate the issue.

**Comment by meag** [comment]
Wonder if this was related to bug found at the bottom of #540 ?  NinJaA, is this still happening for you?

**Comment by meag** [comment]
Closing for now - invalid memory reference in r_drawflat found during #540
NinJaA, please re-open this if it is still happening.
