### ISSUE TITLE
BUG: various hud elements failed to render after coming out of spectator on latest commit (5ae4a869825515ca2dd328eff28ca2e6992b047f)

### ISSUE THREAD

**Issue by ciscon** [ezQuake/ezquake-source#450]
haven't seen this one before
https://nicotinelounge.com/quake/random/ezquake014.png
stuck between maps as well

**Comment by meag** [comment]
Hi @ciscon 

It'll be related to https://github.com/ezQuake/ezquake-source/pull/447

Can you upload your config, and a screenshot of before/after so we can see which elements go missing?

Thanks,
meag

**Comment by ciscon** [comment]
yeah i assumed it was related to that change.  it would appear to be all the same elements that disappear when you go to spec/float
![ezquake015](https://user-images.githubusercontent.com/5131835/101262789-1b7ac580-370f-11eb-83f6-754b72e4a96b.png)
![ezquake016](https://user-images.githubusercontent.com/5131835/101262790-1d448900-370f-11eb-82a2-5d2febb43e44.png)

**Comment by meag** [comment]
Hi @ciscon 

When you say "out of spectator" do you mean "free-floating", and not tracking someone?  Previously I think it just displayed rubbish whatever values the person last tracked had when you went free-floating, is that the behaviour you want back?

Thanks,
meag

**Comment by ciscon** [comment]
once you come out of spectator mode, those same hud elements which are now not displayed while free-floating are gone during gameplay, here's that first screenshot of what it looks like:
![image](https://user-images.githubusercontent.com/5131835/101290948-3d3d8080-37d3-11eb-83b6-655a0aacefe2.png)

**Comment by meag** [comment]
Hi ciscon

Can see it's a problem, just can't see how to make it happen.  If I observe with your config (or mine), the elements disappear but when I do /join they appear again.  Is this only happening some of the time, or is it always?

Thanks,
meag
