### ISSUE TITLE
BUG: RGB HUD stuff

### ISSUE THREAD

**Issue by paddern** [ezQuake/ezquake-source#452]
**ezQuake version:**
3.6-dev-alpha4 r6905~46a0ab77, both MinGW and MSVC (using GLSL)

**OS/device including version:**
Win 10.0.19042.630; NVIDIA 457.51

![info](https://user-images.githubusercontent.com/677138/101532455-dcf63c80-3994-11eb-940f-5d3a4ff1d572.png)
![hud](https://user-images.githubusercontent.com/677138/101532453-dbc50f80-3994-11eb-9f36-e9e0570654a5.png)

[demo.zip](https://github.com/ezQuake/ezquake-source/files/5661475/demo.zip); POV: (1)player; happens already five secs into the round (`/demo_jump 0:04` for the impatient :p)

I noticed the same effect (but with a blueish tone) later on as well but it doesn't seem to be reproducible with this MVD. It was also shorter; maybe that's why? In another game the effect occured relatively long, for about 10 secs I'd guess. So the duration seems to vary.

[config.txt](https://github.com/ezQuake/ezquake-source/files/5661468/config.txt)

**Comment by paddern** [comment]
Oh, colours noticed so far were green, blue and red.

**Comment by meag** [comment]
Not happening here :(  Has this been happening for a while, or is it a recent commit?

**Comment by paddern** [comment]
Most recent one, downloaded it just a few hours ago.

**Comment by meag** [comment]
OK but did it happen in earlier versions of 3.6 or 3.5?  Or is it a recent change?

**Comment by hemostx** [comment]
When this happens, is the console text also gone?
I've seen something like this on map changes since 3.5 with my intel HD4000 laptop, but no colors - only grayscale ; only *sometimes* on the main pc and not for a long time.

**Comment by meag** [comment]
Can you try installing RenderDoc, running Quake through that and then capturing a frame where the bug happens?

Brief explanation of RenderDoc [here](https://github.com/ezQuake/ezquake-source/issues/416#issuecomment-738322129)

**Comment by paddern** [comment]
I'll try the RenderDoc stuff tomorrow.

The console font isn't affected. Checked with -noatlas for a bit, error is gone then. But so are the actual gfx.

Another occurence shows some textures instead of "plain" colours: ![ezquake002](https://user-images.githubusercontent.com/677138/101546533-349ea300-39a9-11eb-8025-5bf13268e7e9.png)

**Comment by paddern** [comment]
> OK but did it happen in earlier versions of 3.6 or 3.5? Or is it a recent change?

First time ever. The last one before was from Nov 27th, also 3.6-dev-alpha4, and worked w/o problems. Same for 3.5 ...

**Comment by paddern** [comment]
Here are my RenderDoc captures ...

While it happens ... [first.zip](https://github.com/ezQuake/ezquake-source/files/5664705/first.zip)
... and after it restored itself (for good measure :p) [restored.zip](https://github.com/ezQuake/ezquake-source/files/5664709/restored.zip)

**Comment by meag** [comment]
Thanks, this is really useful - it is rendering the smoothed items (non-text) using the texture for a player skin, which is why you're seeing it change colour.

Think I can see the problem too (whenever a texture is created the internal texture state isn't being updated - which isn't a problem if your textures are all created at map start but is here)

Hoping the fix to this might fix other random bugs... will get it fixed tonight

**Comment by paddern** [comment]
> [...] it is rendering the smoothed items (non-text) using the texture for a player skin, [...]
> 
> When this happens, is the console text also gone?

JFYI: This reminds me that I disabled smoothing for texts. So, I tested with `r_smoothtext 1` and it'll apply to text as well. :)
