### ISSUE TITLE
BUG: demo_jump freezes client much longer than it used to

### ISSUE THREAD

**Issue by HangTimeQW** [ezQuake/ezquake-source#453]
**ezQuake version:**
3.6 Alpha 4 R6876

**OS/device including version:**
Win10 / 1070ti

**Describe the bug**
In version 3.5 demo_jump 20:10 in a 4on4 demo would only take about 1-2s max to jump to the end of the demo.  In 3.6 alpha 4 it takes about 10s and locks up the client.

**To Reproduce**
Load ezquake
Load 20min 4on4 demo from demo browser
demo_jump 20:10

**Expected behavior**
jumps to 20:10 in the demo in about 1 second

**Comment by meag** [comment]
After an hour of going through commits, it seems to be https://github.com/ezQuake/ezquake-source/commit/fec6355057cd07b36e3d1c974c2f9b37b9aab06c ...
