### ISSUE TITLE
REQ: Make it easier to step to a certain player to spectate.

### ISSUE THREAD

**Issue by Pulseczar1** [ezQuake/ezquake-source#454]
**The Problem**
It's always tedious to select a certain player for tracked spectating. This tedium increases as player count increases. Currently, you have to keep pressing jump until the game "randomly" selects the player you want. If you try to go fast and accidentally skip the desired player, you have to start over.

**Describe the solution you'd like**
I would like a non-random way of selecting a player to spectate. An easy thing to implement, I think, would be to have jump take you to the next player that currently follows the currently tracked player on your scoreboard.

**Describe alternatives you've considered**
There are other ways to do it that would work better, but my suggestion, I think, is very easy to implement, and it would suit me very well, and I imagine, others, too.

**Additional context**
Pressing jump at this point in time (see screenshot), should take you to the player, Data, rather than to a "random" player. This would make it easy to anticipate how many times you have to press jump to get the player you want.
![ezquake005](https://user-images.githubusercontent.com/49758921/101677913-3741dc80-3a2b-11eb-8920-721d8b74edf4.png)

**Impact on server or mods**
I don't think this has anything to do with server-side functionality. My guess is that the client is currently just stepping through players, either by client/edict number, or by user ID.

**Comment by hemostx** [comment]
An alternative to this is an option to enable the mouse when the scoreboard is visible ; you can then click on the player you wish to track. There's a way of doing this in CSGO with a modifier key, I think - I'd have to take another look but IIRC it worked well.

**Comment by Calinou** [comment]
> There's a way of doing this in CSGO with a modifier key, I think - I'd have to take another look but IIRC it worked well.

In CS:GO, it works by right-clicking while the scoreboard is displayed (but you can also change it to use another key).

That said, it sounds difficult to implement in ezQuake considering the mouse-driven menu code is most likely not reusable in the scoreboard.
