### ISSUE TITLE
BUG: vid_renderer doesn't hold value when loaded from config (nQuake)

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#458]
Please search for existing issues and check for potential duplicates before filing yours.

**ezQuake version:**
3.6-alphaX

**OS/device including version:**
using the switchable renderer version, not sure which OS

**Describe the bug**
[03:13]Dusty:any reason why QW wouldn't remember vid_renderer 1 after restarting? very strange
[03:13]dirtbox:I've heard of other people complaining about that @Dusty
[03:13]dirtbox:Put +vid_renderer 1 on your cmdline
[03:13]dirtbox:it still requires a vid_restart though

**Comment by meag** [comment]
Cannot reproduce, neither can eb
Wonder if this is nquake issue where the config file is loaded from another config file and so loaded later than normal

**Comment by liback** [comment]
If it's happening in nQuake installs from before Oct 2017 then it might be the first problem in this list:
https://www.quakeworld.nu/news/1029/nquake-config-updates

**Comment by liback** [comment]
Seems to be an nQuake issue, however the behavior works in ezQuake 3.2.2 but not in 3.6 (using vid_fullscreen as an example that requires a vid_restart and exists in both versions)

To reproduce:
* Start ezQuake 3.6
* vid_fullscreen 0
* vid_restart
* cfg_save
* Close ezQuake
* Start ezQuake 3.6
* vid_fullscreen is now only latched

**Comment by meag** [comment]
Thanks @liback.  Thought it looked like a problem with nquake using default.cfg as that changed fairly recently, but that doesn't seem to be the case (https://github.com/ezQuake/ezquake-source/commit/502c76d2e808825959586408f6c03515551db541)

Very frustrating couple of hours later...

```
Executing: samelevel 8393473 // ffa
Executing: 
Executing: 
Executing: con_bindphysical 1
Executing: exec configs/config.cfg		// From ezquake/configs/
execing C:/nquake/ezquake/configs/config.cfg
Cbuf_InsertText: overflow
Executing: con_bindphysical 1
Executing: 
Executing: con_bindphysical 1
```

Will need to look into why that overflow is happening...

**Comment by meag** [comment]
Not sure this helps, but I get the same behaviour in ezQuake 3.2, if config.cfg exists in the home directory.  The homedir is always searched first during startup, so loaded before nQuake's autoexec.cfg is executed

**Comment by meag** [comment]
Is this still an issue?  I tried today and it was okay, but that was saving to homedir etc, not sure if my settings match nquake defaults

**Comment by meag** [comment]
This still seems to be a problem if homedir config doesn't have the `vid_renderer` value set

**Comment by meag** [comment]
Hoping we can mark this fixed(ish) now?

**Comment by meag** [comment]
Closing, please re-open if still an issue.
