### ISSUE TITLE
BUG: Tiny models

### ISSUE THREAD

**Issue by evhskurk** [ezQuake/ezquake-source#460]
**ezQuake version:**
Noticed after building `r6921~f261a6e6`
Version `r6912~014e11af` does **not** have this problem (not necessarily the last good revision).

**OS/device including version:**
Windows 10 version 2004
NVIDIA GTX1060
Driver version: 460.79 (discovered on 451.48, upgrading did not solve it)
Renderer: GLSL (vid_renderer 1 on a binary built with both)

**Describe the bug**
Models are far too small: weapon/armor pickups, projectiles (rockets, grenades), player models and powerups.
This does not affect bmodels (ammo/health boxes).
The screenshots use brightskins with debug models, but disabling that pk3 and using the defaults does not help.

**To Reproduce**
1. Enter map
2. Be confused about why the fun items are gone
3. Walk over it and pick it up
4. Notice a few pixels when it rotates

or

1. Start demo
2. See `scr_autoid` but no player models

**Expected behavior**
Normal item size

**Screenshots**
![shot-000044](https://user-images.githubusercontent.com/39158438/102014591-03cabf00-3d57-11eb-8cde-928e3c45f2e5.png)
![ezquake131](https://user-images.githubusercontent.com/39158438/102015147-11ce0f00-3d5a-11eb-9088-87fbc499ad46.png)

**Additional context**
Does not affect `vid_renderer 0`
`vid_renderer 0;vid_restart` makes items normal, and they stay that way after `vid_renderer 1;vid_restart` so it is still possible to use GLSL. I'd suspect something isn't getting initialized properly.

**Comment by meag** [comment]
wow :)

**Comment by evhskurk** [comment]
That fixed it, thanks!
