### ISSUE TITLE
BUG: Current fragfile yields a warning in the console

### ISSUE THREAD

**Issue by eb** [ezQuake/ezquake-source#461]
**Describe the bug**
The shipped fragfile yields a warning when entering a map. See attached screenshot.

**To Reproduce**
1. Install the fragfile from the ezQuake website
2. Start ezQuake and type /map dm4
3. See error

**Expected behavior**
The fragfile should be clear of warnings.

**Screenshots**
![ezquake048](https://user-images.githubusercontent.com/183653/102353517-7632dd80-3fa9-11eb-9a91-9ba0748a8544.png)

**Comment by meag** [comment]
Seems to have been added here: (https://github.com/ezQuake/ezquake-source/commit/f665aed2de7b321c04359879803900aecca9094a#diff-a19b293eb13018dfab1a0c7346a388a5d2945555bb974cd2bce84b3907fc7912)
