### ISSUE TITLE
BUG: mvinset crosshair position appears to be hardcoded

### ISSUE THREAD

**Issue by ptdev** [ezQuake/ezquake-source#462]
**ezQuake version:**
latest

**OS/device including version:**
all

**Describe the bug**
When using cl_mvinset with default settings, everything looks ok. But when changing any of the cl_mvinset_sizes, cl_mvinset_offsets or cl_mvinset_right parameters, the inset's crosshair doesn't appear to get updated to the new size/location.

**To Reproduce**
1. Watch some demo or qtv duel and enable with cl_multiview 2; cl_mvinset 1
2. Change, for example, the inset's size with: cl_mvinset_size_x 0.25; cl_mvinset_size_y 0.25
3. The crosshair on the inset picture is not correctly positioned

**Expected behavior**
Crosshair stays at center of inset picture

**Screenshots**
n/a

**Additional context**
I'm not very familiar with C or ezquake's source but from a glance it appears as CL_MultiviewGetCrosshairCoordinates has [some hardcoded values](https://github.com/ezQuake/ezquake-source/blob/56ea11ec68782d8abbde8af9a44463fc0d87752b/cl_multiview.c#L1619-L1625) there that would make it only show correctly with 1/3rd sized window placed at top right and not take into account any of the size, offset or right options.

**Comment by meag** [comment]
Hi @ptdev 

Thanks for reporting this... from a glance at the code you found, I think you're right :) I'll try and have a look at this this week.

Thanks,
meag
