### ISSUE TITLE
REQ: Streamer mode ('asterix to hide password in /password and /spectator password')

### ISSUE THREAD

**Issue by rakasunka** [ezQuake/ezquake-source#466]
**Is your feature request related to a problem? Please describe.**
Would be nice to hide password in /password and /spectator.

**Describe the solution you'd like**
Se above

**Describe alternatives you've considered**
No idea.

**Additional context**
Streaming game from a password protected server without giving out password by accident.

**Impact on server or mods**

**Comment by Calinou** [comment]
I doubt this can be done given how the console works. Instead, ezQuake should be able to use a separate variable (loaded into `autoexec.cfg` or similar) or even a system environment variable as a password (`EZQUAKE_PASSWORD`, `EZQUAKE_SPECTATOR_PASSWORD`).

**Comment by meag** [comment]
(other people have got round this before using aliases in a config file)

I think you're asking for some kind of streaming mode?  We could try and filter characters if certain strings have appeared before them, but it wouldn't be guaranteed to work.  Unless the console was in a different window to the playing window, but that would be a big change.

**Comment by rakasunka** [comment]
Yeah filter it out after a certain string is exactly what i had in mind. But you're right. Putting it in alias/config is a probably a better idea

**Comment by jite** [comment]
Another suggestion would be to have `/password` act like a command instead, so hit /password [ENTER] and then provide an input box that doesn't echo what's being typed, not even * (to avoid giving away number of chars).
