### ISSUE TITLE
BUG: Scoreboard / TO text distorted when entering water in spec mode

### ISSUE THREAD

**Issue by HangTimeQW** [ezQuake/ezquake-source#473]
**ezQuake version:**
3.6 alpha 5

**OS/device including version:**
Win10 1070ti 461.09

**Describe the bug**
Scoreboard and teamoverlay text gets distorted when you are spectating a player and they become submerged in water

**To Reproduce**
1. Spectate a match on a map with submersive water
2. Enable teamoverlay or +showteamscores
3.Track a player
4. Observe text getting distorted on entering fluids, like it makes the text slightly fatter

**Expected behavior**
Scoreboard and teamoverlay text remains unchanged when entering water

Screenshots and cfg  attached, look at the "praxismo" player name for a good example:

![water](https://user-images.githubusercontent.com/71505905/104827596-3cc6e980-5857-11eb-9b13-9e1082288a86.png)
![normal](https://user-images.githubusercontent.com/71505905/104827599-3df81680-5857-11eb-832e-3ef7bf319695.png)
[config.cfg.txt](https://github.com/ezQuake/ezquake-source/files/5825322/config.cfg.txt)

**Comment by Calinou** [comment]
This only occurs for text that is placed in front of the water surface.

Does it improve if you disable solid water surface and use a standard textured water surface instead?

**Comment by meag** [comment]
Testing today, it seems to be that you have `/r_novis 0` but `/gl_turbalpha 0.1` on a non-water-vissed map?
I get far worse graphical conditions that you do do at the moment but not sure if you were watching a .mvd or just spectating on the server when taking screenshots.
Fix coming later today, this seems a long-ages bug in old renderer (pre-3.5) too
