### ISSUE TITLE
BUG: "Failed to create array size 256x128x2", exit to desktop

### ISSUE THREAD

**Issue by meag** [ezQuake/ezquake-source#475]
**ezQuake version:**
3.6 alpha 5

**OS/device including version:**
i9-9900k, 64gb, RTX 2070 Super FTW3 Gaming.

**Describe the bug**
Failed to create array size 256x128x2
"Frequently crashes after game is complete and scores are shown once it resets the map"

**To Reproduce**
"Frequently crashes after game is complete and scores are shown once it resets the map."
"It doesn't always happen. I can play the map 4x in a row and it loads fine the first 3 then crashes the fourth. Sometimes it crashes the first try. Sometimes it crashes before the first map I play even loads. Even crashes sometimes when I try loading maps locally."

**Screenshots**
![image](https://user-images.githubusercontent.com/10936291/105672613-a476d780-5edc-11eb-9f99-8bbcaff54031.png)

Reported by 5h4ddoW on discord
[shaddow.zip](https://github.com/ezQuake/ezquake-source/files/5864788/shaddow.zip)

**Comment by meag** [comment]
Looking into this - looks like the glGetError() is returning OUT_OF_MEMORY multiple times, so even when it reduces the size of the array, it keeps reporting a failure.  Need to clear it out the errors before trying again but will see if there's obvious reason why it's happening first.

**Comment by meag** [comment]
Am hoping this has improved with https://github.com/ezQuake/ezquake-source/commit/63acd285a12691ce5d8aecb90a67ab0a9e21ccae

**Comment by meag** [comment]
Closing, will look at again if it is reported

**Comment by dusty-qw** [comment]
I'm still getting this error on about 50% of map changes... I believe it also happens occasionally during demo jumps.

**Comment by BLooD-DoG** [comment]
I guess this should be reopened since it's still affecting Dusty and a couple other people trying to move to 3.6?

**Comment by meag** [comment]
@dusty-qw Can you:

1) compile with WITH_RENDERING_TRACE defined
2) run with `-dev -r-trace`
3) change maps a few times until text files in `qw/trace/` contains ERROR
4) upload that zipped directory

please?

**Comment by meag** [comment]
bump - @dusty-qw it would be good to do the `-dev -r-trace` thing to find where the OpenGL error was coming from

**Comment by meag** [comment]
bump - still looking for someone affected to

- compile with WITH_RENDERING_TRACE defined
- run with `-dev -r-trace` in command line
- change maps a few times until text files in `./qw/trace/` contains ERROR
- upload that zipped directory

**Comment by dusty-qw** [comment]
Sure. I'm currently out of town, but I'll do it as soon I'm back (wednesday).

**Comment by meag** [comment]
Hi @dusty-qw 

Any chance of uploading some log files so I can try and debug this weekend?

Thanks,
meag

**Comment by dusty-qw** [comment]
@meag I don't see any error messages in the logs. My client only seems to crash between matches, either when map reloads after score screen or after a vote map change. I can't seem to reproduce it by just joining a server and changing maps a bunch of times.

But I can still upload the logs if you think it's helpful.

**Comment by meag** [comment]
Thanks @dusty-qw 

If there definitely no errors in the logs, could you try again and maybe play a few 1-minute bot matches in a row and see if that will trigger it?

Is it still happening with latest source?

**Comment by meag** [comment]
Hi @dusty-qw 

Is this bug still happening for you in latest versions?  I'll close it again for now if we can't reproduce.

Thanks,

**Comment by meag** [comment]
Closing again due to lack of feedback
