### ISSUE TITLE
BUG: Chaticons.png insists on 256x256

### ISSUE THREAD

**Issue by timbergeron** [ezQuake/ezquake-source#477]
Hi! I created a custom graphic for these icons for players when they are typing and AFK. Any file larger than 256x256 is not allowed. With current graphics and resolutions it would be nice for a higher res support. Thanks!

![ezquake001](https://user-images.githubusercontent.com/68674590/106322358-9e5d5f80-622a-11eb-9774-e507d031cda7.jpg)

**Comment by Calinou** [comment]
Here's an AI upscaled `chaticons.png` for testing purposes:

![chaticons_4x_UniversalUpscaler-Soft_190000_G pth](https://user-images.githubusercontent.com/180032/106325622-629eb600-627b-11eb-9e02-7d9a88cc1c08.png)

**Comment by timbergeron** [comment]
Awesome thanks!
