### ISSUE TITLE
REQ: <r_shadows model exclusion list>

### ISSUE THREAD

**Issue by timbergeron** [ezQuake/ezquake-source#479]
It's a nice effect to have shadows under item pickups but I bit distracting when shooting projectiles. The option would add an exclusion list for models. Perhaps also an opacity option. 

See image below of shadow of rocket in air:

![ezquake001](https://user-images.githubusercontent.com/68674590/106366999-5c005500-62f4-11eb-8995-4fcf1a751a59.jpg)

**Comment by Calinou** [comment]
I like having this shadow personally as it makes it easier to see how far the projectile is from the ground/a wall. Without shadows, you have no visual indication for that.
