### ISSUE TITLE
BUG: /record "works" when not connected => /stop crashes to desktop

### ISSUE THREAD

**Issue by hemostx** [ezQuake/ezquake-source#481]
**ezQuake version:**
Reproduced down to 3.0 with default config.
Win 10, but I expect this is irrelevant.

**Describe the bug**
It is "possible" to `record filename` when not ingame/connected to a server, as the recording to file allegedly begins.
When /stopping, the client crashes to desktop with `SZ_GetSpace: overflow without allowoverflow set (0/1/0)`.

**To Reproduce**
1. Start ezQuake, don't connect anywhere or run /map. If ingame, /disconnect.
2. `/record crash` - says "Recording to crash.qwd".
3. `/stop`
4. *boom*
5. (a demo file with only the header may be generated).

Interestingly, if you initiate record from nothing *then* join a server and stop recording while connected, a demo is produced ; so there is maybe some odd script relying on this somewhere.

If you /record something then just quit the game, there is no crash message. This must tell it to stop recording cleanly as /disconnect appears to, but it doesn't visibly crash.
Logging to -condebug doesn't say anything special one way or the other, besides "shutting down audio".
(I tried forcing it to screw up the gamma on a crash to make it obvious, but it just wouldn't even on 3.2 :) )

**Expected behavior**
- This should probably just `break` to a warning in the console when not ingame, unless there is a real use case for starting before connected, in which case
- This should not crash.

**Comment by meag** [comment]
Wonder how far back this goes... you used to **have** to `/record` before connecting to the server, which is why there are no demos available of F9's sensational win vs ACME in the UKCL cup.  (Other games were probably lost too but that was the one that hurts the most).
