### ISSUE TITLE
REQ: different projection types aka playable fov 180

### ISSUE THREAD

**Issue by mushis** [ezQuake/ezquake-source#484]
FTE has a really cool feature that is the support for multiple projection types, for example Steregraphic, fisheye, panoramic, among others.
**This enables playable fov 180**, which for ultrawide monitors is a must. It's really cool, even for 16:9 monitors, i suggest you to try it (get AfterQuake from FTE website)

**Is your feature request related to a problem? Please describe.**
no. only that fov from 130 or 140 is unplayable in all quake engines, except the ones that have different projection types.

**Describe the solution you'd like**
copy/paste whatever FTE has ;)

**Describe alternatives you've considered**
nop

**Additional context**
![image](https://user-images.githubusercontent.com/3011167/107023910-331e0b00-679f-11eb-8aaf-db4fbc9db409.png)
fov 150, panini projection. this screenshot was taken 5 years ago, projection support in FTE is better now.

**Impact on server or mods**
none

EDIT: Attached a zip with screenshots (comparison between different projection types)
[screenshots.zip](https://github.com/ezQuake/ezquake-source/files/5933687/screenshots.zip)

**Comment by meag** [comment]
Moved to discussions: https://github.com/ezQuake/ezquake-source/discussions/491
