### ISSUE TITLE
BUG: Apple Bluetooth Mouse does not work in-game

### ISSUE THREAD

**Issue by dhdanno** [ezQuake/ezquake-source#489]
**ezQuake version:**
3.22 MacOS

**OS/device including version:**
M1 Pro, Big Sur 11.1

**Describe the bug**
The Apple Bluetooth wireless mouse works in the menu screen (cursor works properly) but not in-game...

Played around with various mouse related settings to no avail.

Touchpad works fine. USB wired mouse works fine.

**To Reproduce**
Start the game, move the mouse

**Expected behavior**
Screen should move

**Comment by fzwoch** [comment]
It is a `in_raw 1` problem then. So it is either listed as a different kind of input device, or not routed through macOs's HID system at all.

**Comment by meag** [comment]
@dhdanno have you tried `/in_raw 0` ?

**Comment by dhdanno** [comment]
yes i tried in_raw and all other related mouse commands i could find

**Comment by gfelisberto** [comment]
I have tried several mouses on the M1 and none works.

**Comment by fzwoch** [comment]
Plugged in Steelseries Sensei 310. M1 MacBook Air. in_raw 1. No problem.

**Comment by fzwoch** [comment]
P.s. make sure you gave ezQuake or the terminal, depending on how you start the game to monitor input via Control Panel -> Privacy.

**Comment by dhdanno** [comment]
Regular cheap USB gaming mouse works fine.

Bluetooth Apple mouse does not work. in_raw does not fix it

**Comment by const-void** [comment]
Experiencing similar issue w/OSX M1 silicon except with trackpad / no external mouse: menus are fine, in game is not.

console says unable to initialize SDL mouse when raw is "1".   +mlook has no effect with raw "0" or "1"...any ideas or suggestions?  using nquake w/ezquake brew build (which was very clean, nice job!)

**Comment by fzwoch** [comment]
I did a test. For me in_raw 1 works fine. Check whether you gave correct input monitoring permissions to ezQuake/Terminal depending on how you start it.

in_raw 0 on the other hand did not work for me though. I didn't get any SDL errors as far as I could tell.

**Comment by const-void** [comment]
thank you - that was itl

 "System Settings -> Security and Privacy -> Input Monitoring -> "allow the apps below to monitor input from your keyboard even while using other apps", give a checkbox to "sh".

**Comment by meag** [comment]
@dhdanno @gfelisberto 

Can you confirm you enabled input monitoring?

```
"System Settings -> Security and Privacy -> Input Monitoring -> "allow the apps below to monitor input from your keyboard even while using other apps", give a checkbox to "sh".
```

**Comment by gfelisberto** [comment]
With that it works for me. Can be closed on my side.

**Comment by dhdanno** [comment]
This was already set properly.
I tried the latest version also.
I tried the setting "turn off trackpad when mouse is detected"

Still the same results. Mouse works in the menu, clicks work, but no mouselook :(

**Comment by meag** [comment]
Hi @dhdanno 

Can you try grabbing the latest version and trying again please?  What you're describing is what I could reproduce using `in_raw 0`.

Thanks,
meag

**Comment by dhdanno** [comment]
I tried with the latest code but i get `Error: Couldn't load gfx/palette.lmp` (i have copied pak0.pak ,pak1.pak into Contents/Resources/id1

**Comment by meag** [comment]
Thanks @dhdanno ... I'm a mac novice and don't know the best way to debug, I've been compiling and then running with `-basedir ../quake` in the command line where that directory has id1/pak0.pak etc.

(Hopefully Tuna turns up and suggests something else...)

**Comment by dhdanno** [comment]
It works!

I added -basedir and ran it, with in_raw 0 it works great!

Thanks so much :)
