### ISSUE TITLE
External textures not loading

### ISSUE THREAD

**Issue by liback** [ezQuake/ezquake-source#50]
Using the same config as i have for ezQuake 2.x my 24-bit textures from nQuake/qw/textures/ will not get loaded in ezQuake 3.0.

I have gl_externaltextures_world set to 1 but still get the deault low res textures.

Version: nightly build ezquake-1df22c7

**Comment by liback** [comment]
When replacing my textures in **.jpg** format with textures from nQuake, which uses **.tga**, it works.

Has jpg support been dropped?

**Comment by anderslindmark** [comment]
That's probably my bad, I think I might have forgotten to include the jpeg lib in the build environment for nightlies. I'll investigate.

**Comment by jite** [comment]
jpeg support certainly hasn't been dropped :) Most likely a lib issue indeed. Let me know if you can't find anything wrong anders. Did you use the library I provided btw or your own for jpg?

**Comment by anderslindmark** [comment]
There was no libjpeg in the archive you provided, but I'm gonna try a build now with libjpeg-turbo-1.4.1.

**Comment by anderslindmark** [comment]
Although CONFIG_JPEG should probably be added to the .config_windows file

**Comment by anderslindmark** [comment]
@liback please try with http://uttergrottan.localghost.net/ezquake/dev/nightlybuilds/win32/2015-10-13-d2ec3bf-ezquake.7z and see if you can load .jpg textures using that build.

@jite I realized a few things I need to change about the nightly build system. I can change those, update the .config_windows and make a PR tomorrow provided the jpg-issue is resolved now.

**Comment by jite** [comment]
@anderslindmark Great! Yeah I saw that too. I might have gotten an old .config for windows :/ It's not good to take break from things because they apparantly break other things too :)

**Comment by liback** [comment]
I can confirm that it now works using jpg textures with the version that Anders linked.

**Comment by JoakimSoderberg** [comment]
Fixalicious! :shipit:
