### ISSUE TITLE
BUG: +cl_wp_stats doesn't work until you shoot whilst it is enabled

### ISSUE THREAD

**Issue by HangTimeQW** [ezQuake/ezquake-source#530]
**ezQuake version:**
3.6 alpha 7 win64

**OS/device including version:**
Win10 Pro

**Describe the bug**
If you press +cl_wp_stats during a match, it shows zero for all weapons and only updates when you start shooting.  Once it has 'activated' it will then work OK from then on.

**To Reproduce**
1. Join a server in prewar
2. Shoot lg and register a hit on an opponent
3. Press +cl_wp_stats.  Observe that it says 0.0 for lg
4. Hold down +cl_wp_stats and shoot lg and register a hit on an opponent.  Observe that it now says >0.0 for lg
5. Observe that +cl_wp_stats will now show the correct value from that point forwards

**Expected behavior**
+cl_wp_stats to always show accurate stats regardless of whether you have fired whilst it is being displayed or not

**Comment by meag** [comment]
Closing: this is a KTX bug, as it doesn't send new stats to the client when wpsx userinfo toggled
