### ISSUE TITLE
BUG: 'status' command of the client overrides the 'status' command (cmd 012) of KTX

### ISSUE THREAD

**Issue by tcsabina** [ezQuake/ezquake-source#532]
Not sure from which client version the 'status' command is available (currently I am using 3.6-alpha X).

There is also a 'status' command for KTX (cmd 012), which is not called when you type 'status' on the console of the client.

There is a workaround:
/cmd status
or
/cmd 12

**Comment by meag** [comment]
Is this a recent problem?

![image](https://user-images.githubusercontent.com/10936291/110939141-dc22cd00-832c-11eb-9f61-fe22fd42ad22.png)

In this particular instance, we can make it be `/sv_status` in the cleint, but changing KTX would fix it for old clients too, if it is old.  We can't really have mods re-writing client commands, as then a mod could redefine `/quit` etc...

**Comment by tcsabina** [comment]
I am not sure, meag. I just discovered it today...

I know that 'status' and 'status2' were commands in kt-pro (pre ktx) already.
Maybe align with @deurk on this...

**Comment by ciscon** [comment]
pretty sure it's always been this way, always remember having to type cmd status, while status2 wasn't overwritten with the local server command.  could add another alias for it, perhaps status1?

**Comment by meag** [comment]
Am I okay to close this as to be fixed in KTX?
Only thought I had was to flag all the commands (apart from `map`?) as server-only and then ignore them if the local server wasn't enabled... but might well break some configs as some things look like cvars but are actually commands.

**Comment by tcsabina** [comment]
Issue in KTX to tackle this: https://github.com/deurk/ktx/issues/177
