### ISSUE TITLE
REQ: Filter non-ktx servers on server browser

### ISSUE THREAD

**Issue by Matrix-QW** [ezQuake/ezquake-source#537]
**Is your feature request related to a problem? Please describe.**
There is no filter for qtv and/or mods.
Browser ends up showing many servers we don't want.

**Describe the solution you'd like**
Create a filter for gamedir. Any additional filters would be good.
The client could have some presets but also allow the user to customize filters.

**Additional context**
[https://www.quakeworld.nu/forum/topic/6653/filtering-the-ezquake-server-browse](url)

I use Game Scanner in desktop. It allows to customize filters and has features like buddy list and monitor servers for specific events.

![gamescanner](https://user-images.githubusercontent.com/19843957/111392997-0a4f3680-86b8-11eb-84e4-83f11dd6af5a.jpg)

**Comment by dirtboxqw** [comment]
+1 for this issue

**Comment by Calinou** [comment]
@dirtboxqw Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.
