### ISSUE TITLE
BUG: gl_polyblend related performance

### ISSUE THREAD

**Issue by ciscon** [ezQuake/ezquake-source#538]
gl_polyblend related - i'm hoping one of you can tell me if there's a reason not to do this, as the shifting has already happened and continuing on to apply them to the gamma doesn't actually accomplish anything other than slowing things down.

```
diff --git a/cl_view.c b/cl_view.c
index d516cd81..bfa75317 100644
--- a/cl_view.c
+++ b/cl_view.c
@@ -627,7 +627,9 @@ void V_UpdatePalette (void)
                v_gamma.modified = false;
                old_gamma = current_gamma;
                new = true;
-       }
+       } else {
+    return;
+    }

        current_contrast = bound (1, v_contrast.value, 3);
        if (current_contrast != old_contrast) {
```

**Comment by meag** [comment]
How are `/gl_contrast`/`/gl_hwblend` changes applied if we return after checking gamma?
If nothing has changed, doesn't `new == false` and we return on line 644?

**Comment by ciscon** [comment]
you're right, what it should be is just that the hwblend check is removed, as it doesn't appear to do anything anymore as it's always done beforehand regardless of what it's set to, so doing it again is not only more work, but slows things down significantly (regardless of what it's set to) at least in mesa.

**Comment by ciscon** [comment]
sorry, it's the vblend logic at the beginning that needs to be commented out, or maybe wrapped in a hwblend==1 check, though whatever is doing the blending before that also needs to be wrapped in that apparently as it just always does it making doing anything to do with it here superfluous.

**Comment by namtsui** [comment]
on windows 6800xt unezquake 1.0.4 with `gl_polyblend 1`, fps drops from 1155 to ~1058 when I rocket jump. Shafting a bot and having it shaft back (causing screen tinting) causes it to dip to ~585 fps.

`gl_polyblend 0` stays at 1155 in both scenarios.

**Comment by namtsui** [comment]
After raket's suggestion, `vid_hwgammacontrol 0` and `gl_polyblend 1` also fixes the issue.

To recap:
vid_hwgammacontrol 2 and gl_polyblend 1: fps drops when taking damage (rocket jumping and getting shafted)
vid_hwgammacontrol 2 and gl_polyblend 0: good
vid_hwgammacontrol 0 and gl_polyblend 1: good

**Comment by meag** [comment]
I seem to have misunderstood this - fixes setting the values too often but ciscon reports that it is being set twice if `/gl_hwblend` disabled

need to look at team fortress as it looks like hardware palette shifts are disabled there and so R_PolyBlend always kicks in (safer for flash effects etc?)
also - does `/gl_hwblend` clash with `/vid_software_palette`?  Got very different effects switching between the two

**Comment by ciscon** [comment]
can't say i know what affect vid_software_palette has if any, it just appears that gl_hwblend doesn't actually do anything at this point as it always does it in software and hardware regardless, perhaps because of the tf stuff- which is actually fine as the software blending is plenty fast, if it were me i'd just remove all the hwblend stuff.

**Comment by meag** [comment]
Closing - raket mentioned on the commit that it's fixed for him. (https://github.com/ezQuake/ezquake-source/commit/f21a9f4952820d167fb209db08c772b9565ebf89#commitcomment-53073812)
Please re-open if any problems.
