### ISSUE TITLE
REQ: Stop powerup glow from disappearing when you get close to it

### ISSUE THREAD

**Issue by HangTimeQW** [ezQuake/ezquake-source#542]
**ezQuake version:**
3.6 alpha7

**OS/device including version:**
1070ti GLSL

**Describe the bug**
When you move very close to a powerup glow (either from the powerup itself or a player with that powerup) the glow disappears.  This is very annoying as it can lead you to thinking you have collected a powerup when you haven't.  Most recently this occurred in GQ KI2 game on Rock between Hooligans and Pulsar.  HangTime was waiting for quad, thought he'd collected it and was firing down at meagot below.  It's universally accepted by analysts with a 99.82% probability that had this bug not existed HangTime would have realised, collected the quad sooner, killed meagot and led Hooligans to a glorious 2-0 victory.  This problem also occurred in KI1 on ukcldm2 where a player thought he'd collected quad, exited the room through the teleporter next to quad and then realised he'd left it behind...

Another issue caused by this is in close quarters combat the glow around enemy powerups disappears making it harder to track which player has quad, although this is less of an issue due to powerupshells / powerup skins.

**To Reproduce**
1) Set r_dynamic 2, gl_flashblend 1
2) Edge closer to quad without collecting it
3) Observe that the glow disappears when you get close but haven't collected it.

**Expected behavior**
Powerup glow never disappears

**Comment by hemostx** [comment]
I remember seeing code in flashblend that says when you enter the sphere, it turns off and hands over to the the screen blend.

**Comment by meag** [comment]
`It's universally accepted by analysts with a 99.82% probability that had this bug not existed HangTime would have realised, collected the quad sooner, killed meagot and led Hooligans to a glorious 2-0 victory`

I think you need to get new analysts if you thinking me dying will have any effect on a pulsar match.

Hemo is right, the last time this came up we traced it right back to original glquake ... once inside the bubble, `/gl_polyblend` takes over instead.  Are you asking for `/gl_polyblend 2` where it only applies in this case, and not in the other cases?

**Comment by HangTimeQW** [comment]
Yes I discussed with hemo on discord and a solution would be to have gl_polyblend only apply when inside a sphere, not when you actually pick up a powerup. 

My brain has been tuned to think that 'when glow disappears, it means someone has collected powerup' but actually it might just be that I'm in very close proximity.

Thinking about it, I would probably want this behaviour to change only for powerup items, not for powerup glows on other players.  I. E if another player takes a powerup, and I'm inside the sphere, it's fine to disable the glow as currently.

**Comment by meag** [comment]
https://github.com/ezQuake/ezquake-source/commit/d1670fa4ea5031bf1f60e73df30a27739d620b52

@HangTimeQW can you have a play about and see if it's what you meant?

**Comment by HangTimeQW** [comment]
I've not been able to get it to work, have tried v_dlightshift 1, v_dlightcshiftpercent 100 but the flashblend bubble still disappears when I get close to the quad.  CFG attached.
[v_dlight.cfg.txt](https://github.com/ezQuake/ezquake-source/files/7008305/v_dlight.cfg.txt)

**Comment by meag** [comment]
Hi @HangTimeQW - `gl_polyblend` needs to be enabled, it's the master setting that turns on/off all the palette shifting.

**Comment by HangTimeQW** [comment]
Got it thanks, it is working now :)
