### ISSUE TITLE
REQ: drop CURL_OPENSSL_3 dependency

### ISSUE THREAD

**Issue by nvtkaszpir** [ezQuake/ezquake-source#545]
**Is your feature request related to a problem? Please describe.**
on ubuntu focal fossa (20.04) when trying to run ezquake-ubuntu-3.2.3-full.tar.gz I get error about missing library

```bash
./ezquake-linux-x86_64: /lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./ezquake-linux-x86_64)
```

**Describe the solution you'd like**
Looks like ezquake uses old libcurl3, while new distros switched to libcurl4

**Describe alternatives you've considered**
Downgrading packages, but that opens another can of worms with existing apps.

**Additional context**
Used default nquake install from official page, then downloaded latest availabe ezquake release (3.2.3)

**Impact on server or mods**
Unable to start the game.

**Comment by nvtkaszpir** [comment]
I see the master branch has `libcurl4-openssl-dev` in the travis, so this is even more intrguing.

**Comment by meag** [comment]
Hi @nvtkaszpir 

In the notes for the PR you say this is partially fixed, is it still a problem in master?

Thanks,

**Comment by nvtkaszpir** [comment]
I wrote 'partialy fixed' because I tested this only with building inside docker under ubuntu 20.04 (focal fossa).
Full fix would require reviewing if the code compiles on other distributions and under Windows.

**Comment by ciscon** [comment]
i'd suggest going ahead and closing this, there shouldn't be any compilation issues on any of the major distros (and even gentoo/alpine with minor makefile/environment variable adjustments)

**Comment by meag** [comment]
Thanks @ciscon
