### ISSUE TITLE
BUG: cl_weaponhide probably b0rked

### ISSUE THREAD

**Issue by paddern** [ezQuake/ezquake-source#548]
Please search for existing issues and check for potential duplicates before filing yours.

**ezQuake version:**
3.6-alpha7

**Describe the bug**
I use cl_weaponhide 2 and it doesn't seem to work on Foppa (and maybe other servers)? This seems to depend on the KTX version in use.

**To Reproduce**
1. Go to Foppa and set 4on4
2. Make sure cl_weaponhide is 2 (or 1)
3. Fire RL in prewar
4. (I also got a demo where I distribute a ton of RLs, just in case)

**Expected behavior**
Should just work - it does so locally and e.g. london.badplace.eu.

Shall just Forsberg be nudged to update or does this need a fix in ezQuake as well?

**Comment by meag** [comment]
Are you using `/cl_pext_serversideweapon`?  If so I'd stop until the great BLooD_DoG-config-disaster is fixed (london.badplace.eu is the latest but still has problems)

**Comment by paddern** [comment]
I do, will set it to 0 then. Thanks!

**Comment by meag** [comment]
Closing this, #408 has morphed into a fix for the full stack and not just ezQuake
