### ISSUE TITLE
BUG: ezquake issues with certain tf maps

### ISSUE THREAD

**Issue by lordee** [ezQuake/ezquake-source#551]
**ezQuake version:**
tested on multiple: 3.2 (patched for larger lightmap limit), 3.6

**OS/device including version:**
confirmed issues on windows and linux

**Describe the bug**
pineapple: cannot see player models in demo
cathedral: cannot see walls in demo (this map has a lot of func_walls and possibly structural/normal brushes with no textures on them, which appear transparent in ezquake)

both of these maps have a large number of entities - pineapple has some clock thing on the wall made of i don't know how many entities and cathedral makes use of a large number of func_walls

mvd was recorded on fteserver
[cathedral.zip](https://github.com/ezQuake/ezquake-source/files/6441308/cathedral.zip)
[pineapple.zip](https://github.com/ezQuake/ezquake-source/files/6441310/pineapple.zip)

**Comment by meag** [comment]
Hi - I'm missing the models to play these, what mod is it?

**Comment by meag** [comment]
Scrap that - got it working after some fortress-one downloads...

**Comment by meag** [comment]
More changes to come unfortunately - classic renderer + alpha surfaces was never completed, and is currently worse than 3.2

**Comment by meag** [comment]
Didn't link this very well in the commit text...

**Cathedral**
https://github.com/ezQuake/ezquake-source/commit/f0607afd258362e300d9c9fd9ca6a69483b8f6ea - FTE's first entity packet was read into frame 1 and the first delta packet referenced it, ezquake read the first packet into 0... applied workaround where first packet is read into both.  FTE & ezQuake's code to make the difference so this seems to be a long running problem, not sure why it hasn't come up before.

Also some fixes for the alpha-tested surfaces... our handling of these is still pretty poor though (https://github.com/ezQuake/ezquake-source/commit/8cf3fed6917115625c44cff17cafec8a14887511, https://github.com/ezQuake/ezquake-source/commit/aa04fd5f7beae2240218094bc2117e5a09a9f59a, https://github.com/ezQuake/ezquake-source/commit/6f5854c41ad6abb2674bf8aa7e93b549c3790543)

**Comment by meag** [comment]
**Pineapple**
Players not visible - might need to check with Spike for the true solution to this (it's an FTE extension), but can't see how the extended model limits handle the player.mdl index being > 256.  When playing there's the high bit set in the player skin but that's not present in mvd.  Have applied hack where if the 256 + <index> is the player model, and the current player model is a brush model then we assume it's broken and update.  Am also looking for the skin flag now but it's not set in the demo.

Please reopen if there are any problems.
