### ISSUE TITLE
REQ: Disable explosion bubbles in liquids/teles

### ISSUE THREAD

**Issue by Matrix-QW** [ezQuake/ezquake-source#553]
**Is your feature request related to a problem? Please describe.**
RL/GL explosions at teles or in water show bubbles.
I don't remember if it was always like this or started happening after some update (bug?).

**Describe the solution you'd like**
A variable to disable these bubbles.
![ezquake000](https://user-images.githubusercontent.com/19843957/119684470-d07f7680-be44-11eb-9e14-c54a06649786.jpg)

**Comment by meag** [comment]
Can you upload your config please?
I think bubbles have always happened, but they're being rendered incorrectly there (opaque background)

**Comment by Matrix-QW** [comment]
The particles.png I used didn't have a transparency layer for the background, it was black.
I added it and bubbles are now shown correctly.
On teles is harder to see but will depend on textures/settings.
[config.txt](https://github.com/ezQuake/ezquake-source/files/6719308/config.txt)
