### ISSUE TITLE
BUG: "Load Game"-Button does not work

### ISSUE THREAD

**Issue by GrosserKaese** [ezQuake/ezquake-source#560]
**ezQuake version:**
3.6 Dev-Alpha7 R666

**OS/device including version:**
Windows 10/PC

**Describe the bug**
You can not use the "Load" button, neither in the main menu or in the in-game-menu to load your games, despite having saved some within the version. It simply does nothing. When entering the "Save" Menu, the saves are actually there.

**To Reproduce**
Just try to click "load". It does not work.

**Expected behavior**
The load menu should appear.

**Comment by meag** [comment]
Hi

I can't replicate this - but looking at the code, this will fail if it can't load `spprogs.dat` (the single player game logic).
Is it possible your Quake dir doesn't have this?

Can you try `fs_locate spprogs.dat` at the console and see what it says?

Thanks,
meag

**Comment by GrosserKaese** [comment]
Hi meag,

it simply says "Not found", so it seems to be right. Why does the "official" repo doesnt provide that? And how can I get that file?

Thank you!

**Comment by meag** [comment]
Not sure why it's not here, or what the license is on it... [http://quaketastic.com/files/multiplayer/spprogs.dat](http://quaketastic.com/files/multiplayer/spprogs.dat) should be the right one (Courtesy of [VuRkka](https://www.celephais.net/board/view_thread.php?id=61696#11))

**Comment by GrosserKaese** [comment]
That solved it, thanks! Just put it into the main directory (where ezQuake.exe is located).

Thanks for the help!
