### ISSUE TITLE
REQ: Option to prevent demo playback exiting at end of demo

### ISSUE THREAD

**Issue by HangTimeQW** [ezQuake/ezquake-source#564]
**Is your feature request related to a problem? Please describe.**
When you play back a demo, if you demo_jump beyond the end of the demo, the demo exits.  This means you have to know the the length of the demo to avoid getting dumped back to console if you choose too long a jump.  This is a problem if you launched a demo from windows/cmdline because the client has no way of easily reloading the demo (probably has a complex filepath).  You have to e.g. tab back out to windows and re-open the demo.

Similarly if you let a demo playout you get dumped to console.

A common scenario when viewing demos is I want to skip to near the end so I can see the scores / endgame print etc.  With a standard 20min 4v4 mvd this is fine you can demo_jump 20:10 but some demos are odd lengths e.g. if recorded manually, or the game terminated early for some reason.

**Describe the solution you'd like**
A command that will skip to e.g. 5s before the end of a demo, or a cvar that will halt at the end of a demo without dumping you to console.  Basically a way of avoiding "premature eject" of the demo file...

I'm open-minded about approach for this as long as it provides a way to reliably skip to the end / near the end of a demo regardless of demo length.

**Describe alternatives you've considered**
Using the demo player alleviates some of these problems but it is a bit less user friendly e.g. sometimes I download a demo and just want to check it quickly, I don't want to have to move it into my demos folder and then find it with some random name/timestamp etc.  Likewise to use /playdemo you have to move it somewhere under Quake directory hierarchy.

**Comment by meag** [comment]
Quick hack in the meantime...

```
alias demo_jump_end_go "demo_jump $demo_near_end;cl_demospeed 0"
alias demo_jump_end "set_calc demo_near_end $demolength - 5;demo_jump_end_go"
```

then `demo_jump_end`?

Will try and make the "disconnect" command simply pause the demo if it's found during demo_jump but not sure it will always be reliable.

**Comment by meag** [comment]
Hi @HangTimeQW 

I think this should give you almost what you want: you should be able to `/demo_jump_end` and it will stop as it hits intermission, or 2 seconds before the end of the demo.

One thing - do you want it to pause as well?

meag

**Comment by HangTimeQW** [comment]
Yes I think it would make sense to pause it at that point, thanks.
