### ISSUE TITLE
BUG: in_raw 0 crashes on MacOS

### ISSUE THREAD

**Issue by DiskPoppy** [ezQuake/ezquake-source#565]
Please search for existing issues and check for potential duplicates before filing yours.

**ezQuake version:**
3.2.3

**OS/device including version:**
macOS 11.4, MacBook Pro - late 2013

**Describe the bug**
A crash

**To Reproduce**
Type /in_raw 0 in console or turn off raw mouse input in options

**Comment by DiskPoppy** [comment]
It started working when I enabled 'sh' to monitor keyboard presses even when outside the application in System Preferences. However /in_raw 0 makes you unable to turn the camera, just like /in_raw 1 before enabling 'sh' to monitor etc.

**Comment by meag** [comment]
Hi there

`/in_raw 0` should be working on latest if you build from source, can you try?

Thanks,

**Comment by meag** [comment]
Closing - believe this was reported fixed in #489 
Please re-open if not the case
