### ISSUE TITLE
BUG: unable to create lightmap texture array: error 1281

### ISSUE THREAD

**Issue by Matrix-QW** [ezQuake/ezquake-source#571]
**ezQuake version:**
ezQuake 3.6-dev-alpha9-dev 7120~090e6d75 Jul 30 2021, 04:32:29

**Describe the bug**
Client runs but can't load maps.
The issue seems to be in the size of texture files.
I'm using ibar.png 1x1. It Loads with 8x8.

**Additional context**

Talking to Ciscon on Discord he seems to know why it works on GLSL but not on STD.
Ciscon:
"yeah he doesn't even check whether or not it returned an error in glsl [18:50]
let me see if that fixes it [18:51]
it does- that's why it works in glsl, it just ignores the failure [18:51]
i think it's because it's indexed but the only "color" is transparency heh [18:58]
ibar.png: PNG image data, 1 x 1, 8-bit/color RGB, non-interlaced [18:58]
if i convert it to rgb it's fine [18:59]
colormap is also usually perfectly fine, but a 1 bit colormap is probably what's throwing it heh [18:59]"

Matrix: still same error [19:04]
Ciscon: oh i still have a return where the error is, it just makes it not segfault when you exit [19:05]

[ibar.zip](https://github.com/ezQuake/ezquake-source/files/6918559/ibar.zip)

**Comment by meag** [comment]
Don't suppose ciscon fancies pasting the temporary fix? :)

**Comment by ciscon** [comment]
in glm_lightmaps.c, no check is performed after GL_TexStorage3D, so i just did that:

glc_lightmaps.c:
127     if (error != GL_NO_ERROR) {                                                                                   
128         //Sys_Error("Unable to create lightmap texture array: error %u\n", error);
129         return;
130     }
