### ISSUE TITLE
REQ: Keep interpolation climbing stairs with cl_nolerp 1 in 3.6 like in 3.2.3

### ISSUE THREAD

**Issue by Matrix-QW** [ezQuake/ezquake-source#572]
**Is your feature request related to a problem? Please describe.**

With 3.2.3, cl_nolerp 1 keeps the screen smooth while climbing stairs. The rest of textures don't seem to get interpolated.
With 3.6 the screen gets jumpy, impossible to aim during that time. If the client loads with cl_nolerp 0 and inside a map I change to cl_nolerp 1 the stairs stay interpolated but the moment I enter a teleport it gets disabled.
Why would anyone would use cl_nolerp 1?
To reduce the input/screen delay.
I know people who use it with 3.2.3.
I opened this as a request from a player that refuses to use 3.6 due to this.

https://www.quakeworld.nu/forum/topic/4698/interpolation-buffering-clnolerp-0
According to Qqshka, "players are treated specially and not only interpolated but also extrapolated".
I assume cl_nolerp 0 also interpolates players, don't know what moving objects implies.

**Describe the solution you'd like**
Let players decide where they want interpolation.
But to keep it simple:

cl_nolerp 0 interpolate everything
cl_nolerp 1 interpolate like 3.2.3 (stairs, nothing else I suppose?)

**Describe alternatives you've considered**

cl_nolerp 0 interpolate everything
cl_nolerp 1 stairs
cl_nolerp 2 stairs + textures (map and items)
cl_nolerp 3 stairs + projectiles
cl_nolerp 4 stairs + players
cl_nolerp 5 stairs + textures + projectiles
cl_nolerp 6 stairs + players + projectiles

**Comment by Calinou** [comment]
PS: The link you posted is broken, as it's formatted like this:

`[https://www.quakeworld.nu/forum/topic/4698/interpolation-buffering-clnolerp-0](url)`

Replace it with this:

`https://www.quakeworld.nu/forum/topic/4698/interpolation-buffering-clnolerp-0`

**Comment by meag** [comment]
There is 'crouch' adjustment code for going up and down stairs, I have been asked to disable that in the past.

I'm not sure what interpolated textures means?  As far as I'm aware `cl_nolerp` has always only affected players/entities.  The only change I would have thought 3.6 had for lerping would be the fixes for going through teleporters (and even that isn't 100% fixed) and when you die on a spawn point (where you rise up from the floor instead of respawning at normal height).  Might well have broken something though if you say this kicks in after going through a teleporter.

**Comment by Matrix-QW** [comment]
By interpolated textures I mean the map, how textures of walls, teleports, etc, look smooth while moving.
Is this the result of cl_nolerp 0 interpolating my own player?
I thought it would affect only other players and the interpolation of the screen was treated differently..
R_drawentities 0 removes players so they are treated as an item.

Yes, it kicks in after a teleport or a map change. You can try it to see the effect.
Load with cl_nolerp 0, change it inside a map, walk over stairs they are still smooth. Enter a tele and climb stairs.
Ezq 3.2.3 has cl_pext_lagteleport and stairs work. Not sure if you are refering to this.

**Comment by HangTimeQW** [comment]
I just did some testing in 3.6, a good way to demonstrate this is:
1) Set cl_nolerp 0
2) map dm2
3) Climb the stairs below quad, notice it is relatively smooth
4) Set cl_nolerp 1
5) Climb the stairs below quad again, notice it is the same as step #3 
6) Go to bigroom and go through one of the teleporters at the side
7) Now climb the stairs below quad again, notice how it is quite 'jerky' in terms of height adjustment.

I don't personally have a view on whether this is good or bad, or what should be changed, just helping reproduce the issue.
