### ISSUE TITLE
REQ: Variable to update servers status only

### ISSUE THREAD

**Issue by Matrix-QW** [ezQuake/ezquake-source#574]
**Is your feature request related to a problem? Please describe.**
I use sb_autoupdate 0 with cl_onload menu_multiplayer.
To update their status I need to press space. It only updates status, not pings/proxies, wich is what I want.

**Describe the solution you'd like**
A variable (sb_refreshstatus) to update status (no ping/proxies) without having to press space.
The reason is I don't want to update pings and proxies everytime I run the game.
So I would use: cl_onload "menu_multiplayer;sb_refreshstatus".

**Additional context**
This request is related to this:
https://github.com/ezQuake/ezquake-source/issues/529

**Comment by meag** [comment]
Hi @Matrix-QW - Isn't this `sb_refresh info`?

**Comment by Matrix-QW** [comment]
Just tried it. This is exactly what I want.
Seems no one knew about this but you. Should be added to the variable help description.
You can close the request.
