### ISSUE TITLE
Request: player gender cvar / appropriate obit pronouns

### ISSUE THREAD

**Issue by seascape** [ezQuake/ezquake-source#58]
I'm returning to QuakeWorld after not playing seriously for about 13 years and I really like the features and usability of eqQuake (via nQuake). But being female, I'm surprised it hasn't implemented a player gender cvar.

Upon dying in-game, I very quickly noticed the jarring obit "Lisa* was looking good until he killed himself," which prompted me to investigate gender settings. But there doesn't seem to be an option.

I see a brief reference to player gender in vx_tracker.c, but am unsure how that relates to the rest of the project. Could you kindly implement player gender in the future? It has been pretty standard in these games since at least Quake II, and it seems like it'd be simple to add. Thank you!

*Not my real name.

**Comment by JoakimSoderberg** [comment]
@meag  implemented this here: https://github.com/ezQuake/ezquake-source/pull/60

**Comment by seascape** [comment]
Wonderful. Thank you very much.

I will post again if I notice bugs.

**Comment by meag** [comment]
Unfortunately it will need server support - not all userinfo fields are sent back to the clients, so we need server updates before this will work properly.  Default is now "Player was looking good, then committed suicide", but if the server supports it and the client sends gender, you should see correct messages in future.

**Comment by seascape** [comment]
Ah, I figured that might be so. It should serve nicely with the Frog Bot and such in the meantime, though.
