### ISSUE TITLE
BUG: Couldn't save game to "/opt/quake/qw"

### ISSUE THREAD

**Issue by githubtefo** [ezQuake/ezquake-source#586]
Hi! I'm trying to save my game progress on single player mode, although Quake tries to do it on /opt/quake/qw and it has not permissions to do it. How can I specify a different directory on my /home?
Thanks!

**Comment by Calinou** [comment]
Which ezQuake version are you using, and how did you install it? ezQuake should be installed to a path that is writable by your user.

**Comment by ciscon** [comment]
this is what the aur script does i'm fairly certain, if you're using that you should probably just set cfg_use_home 1 so it saves to ~/.ezquake

**Comment by githubtefo** [comment]
Hi @Calinou, I'm using ezquake 3.2.3-1, from https://aur.archlinux.org/packages/ezquake/

Hi @ciscon, thanks for your input.
You are right, this is from AUR. I set cfg_use_home 1, and my config.cfg it is saved in ~/.ezquake. But that is not the case for the game progress.

**Comment by ciscon** [comment]
not really sure what to tell you other than to modify /opt/quake so it's writable by you (or a group you belong to), or just create a proper quake directory in your homedir and use that instead.

**Comment by meag** [comment]
Could look at adding `/cl_save_home` or something...  would need to update sv_save.c/SV_SaveGameFileName (make sure there's a sub-directory per gamedir) and update the menus to look in the same place.

**Comment by githubtefo** [comment]
Hi @ciscon, thanks for the feedback. I conceded rw permissions to my user for the save folder.
@meag, I couldn't find the "cl_save_home" command in the console, if that what you were referring to.

Thanks for all your help! should I consider this issue solved?

**Comment by meag** [comment]
Re-opening if that's okay - I think we should support the binaries being in a read-only directory and user data being elsewhere.
