### ISSUE TITLE
BUG: speed value contaminating armor/ammo3/ammo4 HUD on QTV dmm4 pregame

### ISSUE THREAD

**Issue by hemostx** [ezQuake/ezquake-source#590]
**ezQuake version:**
a8947421cad3c33727a3fc2e9ce2cb277f45dd28 - master at time of writing
vstudio build, x64 rls-modern
hud_armor_hidezero, new to this patch, is set to the default 0
hud_armor_pent_666 default 1

**OS/device including version:**
W10 20H2 GTX1070 461.70

**Describe the bug**
After an undetermined trigger, my HUD while tracking someone over QTV started showing the player's speed in the hud_armor element, as well as also influencing ammo3 and 4 (which would still be within the bounds of max ammo, it seemed).

**To reproduce**
I'd been casting a comp game on a few standard maps through QTV with no issues. When I switched to some *end* action somewhere else, (so, dmm4) everything was fine for a match or two.
On one map reload, my client started showing the speed in the armor field in unexpected fields as seen on this clip https://www.twitch.tv/videos/1141091619 (and not "percentages" as I mistakenly said live).

- The buggy hud values froze on countdown, and then started working normally during the match.
- On the following reload after the end of the match, the behaviour surfaced again.
- Xantom switched maps/DMM and it still happened.
- Could not reproduce on the built-in ezquake server, nor on a local ktx.
- I tried joining one of the other free irc.qw.ax ports to be as close as possible, but couldn't reproduce it as a player.

No one around to QTV on end after that :)

**Comment by meag** [comment]
That's a KTX feature, sh_speed?

**Comment by hemostx** [comment]
It is indeed (and a bit of a *wat* moment pondering the thing - I figure it predates even the strings hud, or something like that).
So it appears the ammo values show vertical speed. I'm not sure what is the point of displaying that data several times at different precisions, but, well: it is what it is.
Another reminder that a ktx reference might be more important to get going (since it... doesn't exist), and to probably look at a refreshed "ezquaktx" client+server *manual* that joins the two, since the QW architecture keeps them separate...
