### ISSUE TITLE
ISSUE: Received signal 11

### ISSUE THREAD

**Issue by filimanistr** [ezQuake/ezquake-source#594]
**ezQuake version:**
git commit hash: 5fe700576887d0646910bfe88b07eca958b6c582

**OS/device including version:**
raspberry pi 4b 4gb
distro: archlinux armv7

**Describe the bug**
After building the ezquake-linux-arm binary file and moving it to the game folder (with id1 folder and others) the client did not run

**To Reproduce**
1. Build ezquake:
git clone https://github.com/ezQuake/ezquake-source newfolder
cd newfolder
make -j3 
2. Move ezquake file to the quake older
mv ezquake-linux-arm ../quake_folder
3. run
./ezquake-linux-arm

**Expected behavior**
ezquake works without any troubles

![1 First run](https://user-images.githubusercontent.com/38727441/136519622-f1310cdb-4ca4-49a3-9434-b0181dcec7a1.jpg)
![2 After 3th run](https://user-images.githubusercontent.com/38727441/136519759-0e9a2e22-fb19-4d31-b7ec-753bf00fa2c3.jpg)
![3](https://user-images.githubusercontent.com/38727441/136519781-c386d47a-88a6-411c-8ba1-da3e0b6c645a.jpg)

**Comment by meag** [comment]
Hi @filimanistr - can you try getting latest and confirming if that's fixed?
