### ISSUE TITLE
REQ: Warn users about cvars that need texture reload to take effect

### ISSUE THREAD

**Issue by hemostx** [ezQuake/ezquake-source#602]
**Is your feature request related to a problem? Please describe.**
This came up while investigating #601 (latching gl_no24bit not getting applied), where it appeared that some GFX variables which take effect with a vid_restart do not mention this in the console, as only CVARs registered with the `CVAR_LATCH_GFX` property warn the user in the console about needing a vid_restart.

**Describe the solution you'd like**
Treat the gl_vars that require a vid_restart as latching cvars to get the prompt and latching behavior.

These following cvars declared in `r_texture_cvars.c` fit this description:
- gl_max_size
- gl_miptexLevel
- gl_picmip
- gl_scaleModelTextures
- gl_scaleModelSimpleTextures
- gl_scaleTurbTextures
- gl_scaleskytextures
- gl_lerpimages //unsure about this one
- gl_externalTextures_world
- gl_externalTextures_bmodels

**Caveats**
- I was looking around that area, so found some obvious "need restart" cvars I knew about. There may be others across other files that I'm missing entirely.
- There are special cases on `gl_max_size` and `gl_miptexlevel` : they also need an *OnChange* action to warn about allowed texture sizes etc. and AFAICT it's one or the other in the cvar_t typedef (at least I failed to get both going naively  :) ).
- As-is, merely adding `CVAR_LATCH_GFX` in the initial cvar declaration gives the "vid_restart" warning, but the switch becomes ineffective. They also need to be pulled out of `if (!host_initialized) {}`.
I have a partial patch which does this for the cvars I understand, know are latching and don't need to pick between a flag or OnChange

**Describe alternatives you've considered**
In terms of implementation, I'm not sure. Adding `Com_printf("need vid_restart")` in the *OnChange* actions feels like a dirty hack, because it is - we don't get the desired value latched when describing the cvar, nothing gets queued.

**Impact on server or mods**
There should not be :)

**Comment by hemostx** [comment]
Half-baked patch at https://github.com/hemostx/ezquake-source/commit/35586c4cf432c6c17e8fbacd49cda53494bc075c - I haven't dared PR it

**Comment by meag** [comment]
Closing, CVAR_RELOAD_GFX flag has been added
