### ISSUE TITLE
BUG: Occasional console corruption on vid_reloads

### ISSUE THREAD

**Issue by hemostx** [ezQuake/ezquake-source#611]
**ezQuake version:**
3.6a10 since vid_reload was introduced in 219f2a56

**OS/device including version:**
W10 20H2 GTX1070 472.12
GLSL (not tested STD)

**Describe the bug**
On some vid_reloads, the console gets visibly corrupted. A further reload usually fixes this.

**To Reproduce**
1. Start the game, start a map.
2. Change a cvar_reload_gfx cvar i.e. gl_picmip
3. With some luck, the console gets corrupted.

I can not reproduce this reliably. For a moment, it seemed like the quicker I tried after starting the exe, the more likely it was to happen. I'll try to brute force an occurence in renderdoc if needed.

**Expected behavior**
No console corruption.

**Screenshots**
- conback changes to sky
![reload_conback](https://user-images.githubusercontent.com/64284375/141688547-2192f0b7-864a-430a-9d69-37b1db0ad16d.jpg)
- conback changes to sky, console font changes to conback IIRC
(seen it, but didn't screenshot 🤦‍♂️ - will try to reproduce)

**Comment by hemostx** [comment]
I got it first try with the new patches...
![console-charset-reloadbreakage](https://user-images.githubusercontent.com/64284375/141696295-bd8dca84-9c17-4638-9b07-958aa0f7295f.jpg)
... luckily, running through renderdoc.
Two interesting points:
1. The charset is messed up in the hud pass - we just can't see it through the sky console.
Interestingly, there is only one input texture on that stage - the 2D atlas. Upon closer inspection, it's been generated with the conback texture instead of the charset texture (the alt. glyphs for cyrillic are unscathed).
![oopsie](https://user-images.githubusercontent.com/64284375/141696621-e8af8e40-2ae4-4547-bd9c-c5956a70792f.PNG)

2. On the conback draw pass, the one input texture is the sky proper
3. The console text draw pass has one input texure - the same broken 2D atlas from earlier.

**Comment by meag** [comment]
Can't reproduce this, can you upload your config?

**Comment by hemostx** [comment]
[config.txt](https://github.com/ezQuake/ezquake-source/files/7534709/config.txt)

**Comment by meag** [comment]
Hi hemo - can you try latest and see if this is still happening for you?  on `vid_reload/refresh`, the console background mpic_t had corrupt data... I'm hoping that was the cause

**Comment by meag** [comment]
Thanks hemo
