### ISSUE TITLE
BUG: hiding hud element also hides all other elements placed on it

### ISSUE THREAD

**Issue by kslen** [ezQuake/ezquake-source#619]
**ezQuake version:**
3.2.3 and 3.6 alphas have the same behavior

**Describe the bug**
hud_netgraph_show 0 also hides other hud elements which are placed on netgraph.

**To Reproduce**
1. hud_fps_place netgraph
2. hud_recalculate
3. hud_netgraph_show 0

**Expected behavior**
The fps element should remain visible while netgraph is hidden.

The current logic would be within expected behavior if a group with one or more of these elements placed on it were hidden, but not when individually hiding elements that happen to have others placed on it.

**Additional context**
Sample problem from a user experience perspective; new user who is happy with the hud in general but wants to disable the face or iarmor element, would have to place elements tied to them on other visible elements (or screen, then set pos values) to achieve the expected result.

In single player, the iarmor element is not drawn unless the player has armor. For a hud designed to be used in both single and multiplayer, this becomes problematic when using relative alignment to iarmor.

**Comment by meag** [comment]
This is by design - I think you're asking for a new `_render` option on each hud element, to process & measure content but then display nothing?  We can't place hud elements relative to elements that are hidden, as they have no size.
