### ISSUE TITLE
REQ: hud_x_mp 0/1 to determine if element is drawn during localhost single player campaigns

### ISSUE THREAD

**Issue by kslen** [ezQuake/ezquake-source#620]
**Is your feature request related to a problem? Please describe.**
Designing a hud for multiplayer and keeping a minimalist aesthetic is not possible if the same hud is also to be used in single player. At least without maintaining two huds and forcing the user to toggle between them.

**Describe the solution you'd like**
A new hud_x_mp cvar that will result in an element only being drawn when connected to mvdsv.

**Describe alternatives you've considered**
Reverse if connected to localhost and mvdsv is not present.

**Additional context**
When playing localhost single player campaigns, elements such as gameclock, frags, net and netgraph are not required and thus would contribute to immersion if hidden.

**Comment by meag** [comment]
Closing, fixed in https://github.com/ezQuake/ezquake-source/commit/7c561086ab5a5b2d36ef544f33a6ca541045483c
