### ISSUE TITLE
REQ: Better support for Skyboxes [mapping]

### ISSUE THREAD

**Issue by inf1niti** [ezQuake/ezquake-source#629]
**Is your feature request related to a problem? Please describe.**
Skyboxes can only be loaded in EZQuake manually by the end-user, by having them enter a `r_skyname` value.   Since skyboxes are often meant to be loaded with specific map (instead of globally), this doesn't usually make sense.  

Furthermore, the orientation of the skybox in ezquake does not match that of other engines.  This is problematic when a map's `sunlight_mangle` value is set to match the skybox.

**Describe the solution you'd like**
Ideally skyboxes load automatically on map load from the worldspawn `_sky` property (if present).  The end user should still be able to decide whether they want to load this - for example, other engines will load skybox by default unless `r_fastsky 1` is selected.  Orientation of skyboxes should also be consistent with other engines.

**Impact on server or mods**
This should have no real negative impact.  If a user likes to use a custom sky as a fallback when a map doesn't specify a skybox, the `r_skyname` value should still be supported.  If a user doesn't like loading skyboxes, they should have the option to disable it in their config.

**Comment by meag** [comment]
Can you supply an example .bsp with the worldspawn `_sky` property?
Also: "Orientation of skyboxes should also be consistent with other engines" - can you supply example assets, and are you saying the orientation of existing uploads to gfx.quakeworld.nu etc are also rendered incorrectly?

**Comment by inf1niti** [comment]
## Example Map
I have a [WIP map](https://drive.google.com/file/d/1KNIzdRA4G7fJRkuw2Tr7phfqduv3rurL) that uses the `_sky` property.  It's not the best example (it's a big map), but it is packaged with the skybox being used.

## Usage & Support
The `_sky` key in the worldspawn has become a standard key in SP engines, and is commonly used for referencing skyboxes in the single player mapping community.  If you check out the maps in any of the major SP mods (AD, Alkaline, Dwell, etc.) they use this key to ref skyboxes as well.  

QS, QSS, FTE, MHQuake, VKQuake, Ironwail (and likely other engines), support loading skyboxes from the worldspawn with this key.
Example of [worldspawn skybox loading in QSS](https://github.com/Shpoike/Quakespasm/blob/9ffca1dedc47061ec4c2b7c230c44aa23a591226/quakespasm/Quake/gl_sky.c#L284-L285).

## Skybox Orientation Issue
re: orientation, using the map provided above as an example you can see the effect I'm talking about.  Skyboxes are standardized file sets: they just a series of 6 image with `_bk`, `_lf`, `_ft`, `_rt`, `_up`, `_dn` postfixes.  As such any asset (whether uploaded to gfx.quakeworld.nu or not) would experience the same orientation inconsistency mentioned here.

| Engine | Screenshot |
| ------------- | ------------- |
| **QSS**  | ![qssm0496](https://user-images.githubusercontent.com/67801374/151648632-802d5c26-0d5f-411e-9abe-a8f6df28c966.jpg) |
| **FTE**  | ![fte-20220128231237-0](https://user-images.githubusercontent.com/67801374/151648547-de29c4f0-b86f-4190-97e9-5ec2b7b10529.png)  |
| **VKQuake** | ![vkquake0002](https://user-images.githubusercontent.com/67801374/151648488-4048d3b2-c3c9-404f-ba24-52c479d1c645.png) |
| **QRack** | ![qrack998](https://user-images.githubusercontent.com/67801374/151648624-32056612-868f-4331-aaa6-bce9c0fac7cd.jpg) |
| **EZQuake** | ![ezquake032](https://user-images.githubusercontent.com/67801374/151648463-d9ae6b2c-72fe-4059-99f2-aca9499fa911.png) |

Further details from discussion on discord with Lurq
![image](https://user-images.githubusercontent.com/67801374/151648895-541ddd65-2a3d-4d1d-9a01-bedb17ea97db.png)

**Comment by zigg1zagg1** [comment]
I guess it would make sense to support per map fog settings also? 
Most singleplayer oriented quake engines support setting custom fog values with a `fog` key in the worldspawn, similar to how skyboxes are done.

Seems like fog is bugged in the new renderer tho, so maybe this is something to add later.
