### ISSUE TITLE
BUG: fix.cfg crashes quake

### ISSUE THREAD

**Issue by rakasunka** [ezQuake/ezquake-source#640]
**ezQuake version:**
commit f4af135b088bfc9cc42747a5971ba4ea8bc23bae

**OS/device including version:**
Windows ezquake, linux ezquake

**Describe the bug**
quake crashes with bug with cfg supplied.
```
Error: SV_Error: ED_LoadFromFile: found 
"wad" "gfx/base.wad"
"classname" "worldspawn"
"worldtype" "2"
"sounds" "6"
"message" "The Abandoned Base"
 when expecting {
**To Reproduce**
Steps to reproduce the behavior:
```
When executing /map dm3

**Expected behavior**
:)

**Screenshots**
See above 

**Additional context**
crashes for both me (raket) and fix
Tried with both nquake release of quake and normal release with just id1/pak{0,1}.pak and ezquake/config/fix.cfg
[fixcfg.zip](https://github.com/ezQuake/ezquake-source/files/8237578/fixcfg.zip)

**Comment by ciscon** [comment]
paradoks mentioned that this happens with cl_curlybraces 1
