### ISSUE TITLE
REQ: Remove useless error message and none-wanted behavior as spectator when spectating disconnected players

### ISSUE THREAD

**Issue by rakasunka** [ezQuake/ezquake-source#643]
**Is your feature request related to a problem? Please describe.**
When joining or being in a game as spectator where people(s) has/have disconnected when changing pov to the one(s) disconnected and we track nothing but a zombie getting the useless error message "Invalid client to track" which is just annoying and really not useful at all.

**Describe the solution you'd like**
What if we just silent ignore the disconnected player(s) remove the none interesting error message and just automatic to change next player? It's not likely anyone want to see the error message or really want to spectate a zombie.

A toggle command would be useful. Something like /cl_useless_spectator_behavior 1|0

**Comment by meag** [comment]
Hi raket

It's mvdsv sending back the message, not the client.

KTX doesn't tell the client who is a ghost and who isn't... we could make the client skip the name prefix but then anyone choosing that prefix (`/name $a meag`) wouldn't be able to be tracked.

Maybe raise this is in the KTX repo (to insert *ghost=1 into the userinfo) and then the client could skip them reliably.

- meag
