### ISSUE TITLE
BUG: no more __LITTLE_ENDIAN - Endianess detection broken on Linux with GCC

### ISSUE THREAD

**Issue by libTorrentUser** [ezQuake/ezquake-source#655]
**ezQuake version:**
latest release and current master.

**OS/device including version:**
Linux (Alpine)

**Describe the bug**
[The endianess detection in q_shared.h](https://github.com/ezQuake/ezquake-source/blob/6c0f284375c66d9733943cf367585fa83f31b09e/q_shared.h#L142) fails because GCC no longer defines `__LITTLE_ENDIAN` nor `__BIG_ENDIAN`. Those were replaced by ´__ORDER_LITTLE_ENDIAN__' and ´__ORDER_BIG_ENDIAN__´

This happens when using GCC 11.2. CLang also seems to use `__ORDER_LITTLE_ENDIAN__` and `__ORDER_BIG_ENDIAN__` but, as far as I know, it doesn't define `__FLOAT_WORD_ORDER`. So... it is a mess :)

You can check what those compilers define with
`clang   -dM -E -x c /dev/nul | grep ENDIAN`
`gcc   -dM -E -x c /dev/null | grep ENDIAN`

I'm using GCC so, for me, it was just a matter of replacing the symbols to get it to compile.

**Comment by ciscon** [comment]
should be addressed in: https://github.com/ezQuake/ezquake-source/pull/658
