### ISSUE TITLE
REQ: Make console font (charset) not tied to vidcon_height / con_width

### ISSUE THREAD

**Issue by f-o-o-g-s** [ezQuake/ezquake-source#71]
This has always bothered me. 

Notice how the slash and R are distorted http://i.imgur.com/yJ8uFrz.png

They wouldnt be distorted if I used a half resolution con_width/height.

**Comment by meag** [comment]
Hi there

Not sure how to action this - what would we replace it with?  What settings are you using at the moment?  Found this last night: http://ezquake.sourceforge.net/docs/?fonts, is that describing the same problem?

**Comment by meag** [comment]
Can you give any more detail on this please?

**Comment by meag** [comment]
Closing - don't really understand the issue described.
