### ISSUE TITLE
BUG: Serverbrowser crashes

### ISSUE THREAD

**Issue by onethree7** [ezQuake/ezquake-source#72]
SB crashes on Windows, using alpha/latest and past versions.

It appears to crash more frequently when files.txt and the dummy are selected. 
I suspected multithreading issue here, but also happens when only 1 core assigned.

Crash happens when refreshing.

**Comment by meag** [comment]
Can you try with the latest version and see if it's a bit more stable?  It does need more work but I'm hoping https://github.com/ezQuake/ezquake-source/commit/019b73d50baa30ce6ae28770228bf0fed2aa0740 did some good in reducing crashes and race conditions.

**Comment by onethree7** [comment]
i´ve been testing this a bit, and couldnt reproduce crashes anymore, no matter what sourcefiles i select, no matter what settings i use with my current installation/config
I will try to reproduce this again this WE with an nquake freshinstall and an alternative EZQ manual install to check if this is really clean.

Also, the scans are getting close to all servers now. On the very early 3.0 builds, i couldn´t even use a simple text file with all IP´s in it and get all servers. even on highest source/info timeout settings. Some were always missing.

Another thought on this bug where i got the crashes in SB. Is it possible (as i was the dude using gl_no24bit 1) that this setting was producing the crashes and the bug might have been fixed by that too?

**Comment by meag** [comment]
Thanks for replying.

I'm confident that the `gl_no24bit 1` problem was different than this.  There were a variety of problems with the server browser with freeing memory more than once, so if you were touching the dummy file at all then there was a high chance of the client crashing.  There's a lot more work to be done (it's on to the todo list for an overhaul) but it should be more stable at least, that's all I can say.

Will leave open for you to do more testing, let us know how you get on.

**Comment by meag** [comment]
Did you manage to get a chance to do some more testing?

Are you okay with me closing this, and we can look at it again if it's still an issue in recent versions?

**Comment by onethree7** [comment]
i couldnt get it to crash in either way!
nice job again. plz close!
