### ISSUE TITLE
BUG: Reloading video might crash on Linux (gamma related?)

### ISSUE THREAD

**Issue by jite** [ezQuake/ezquake-source#74]
From qirex:
20:35:21 < qirex> dimman: i've been retrying ezquake on linux
20:35:28 < qirex> vid_restart make it crash
20:35:37 < qirex> as well as vid_fullscreen 0

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (XFree86-VidModeExtension)
  Minor opcode of failed request:  17 (XF86VidModeGetGammaRamp)
  Value in failed request:  0x1e00009
  Serial number of failed request:  307
  Current serial number in output stream:  311

**Comment by jite** [comment]
Just noting here, it's due to gammaramp sizes being != 256

**Comment by jite** [comment]
Hopefully fixed with: https://github.com/ezQuake/ezquake-source/commit/18b7f8fde5deee28656360fec60e982ac91a1713 and https://github.com/ezQuake/ezquake-source/commit/0e13ebef20d0436ef90b84a0f98fbf2b78a1b250

**Comment by meag** [comment]
Closing (confirmed as fixed via IRC)
