### ISSUE TITLE
BUG: Default keymap not detected upon startup (only after entering server)

### ISSUE THREAD

**Issue by liback** [ezQuake/ezquake-source#90]
When starting ezQuake and seeing the console upon startup, ezQuake won't detect that my keyboard layout is Swedish.

When entering game (/map dm3) the keymap is correct.

Version: ezQuake 3.0 r4844~7f46613

**Comment by meag** [comment]
Looking through code to see what might cause this - can you send the values of /cl_startupdemo & /cl_onload cvars please?

**Comment by liback** [comment]
cl_startupdemo = ""
cl_onload = "sb_refresh"

**Comment by liback** [comment]
cl_onload = "menu" works when i exit menu and go to console, then keyboard layout is Swedish.

**Comment by meag** [comment]
Confirmed... if cl_onload is set to console command, the destination for keypresses was still the default (game) and so keyboard layout was ignored.  When you connect to the game and press the key for console that obviously rectifies itself and so everything is okay.

Fix imminent...

**Comment by liback** [comment]
Verified that this now works with Swedish keyboard using values:
cl_onload "browser"
cl_onload "console"
cl_onload "menu"
cl_onload "sb_refresh"

Version: ezQuake 3.0.1-dev r4855~bbfc34b Jun 10 2016, 02:01:55

**Comment by meag** [comment]
Excellent, thanks for confirming.
